// Generated by AI (UnitTest MCP)
//! Optional asynchronous LLM consolidation via a local, OpenAI-compatible model
//! server (Ollama's `/v1`, LM Studio, llama.cpp's server, …).
//!
//! The deterministic pipeline handles the write path with zero tokens. This
//! worker is the "sleep-phase" consolidation layer: it compresses batches of raw
//! logs into a single high-level `intent` node using a small local model
//! (e.g. `glm4:9b` / `codegeex4:9b`) and never leaves the machine.

use std::collections::HashSet;

use serde::{Deserialize, Serialize};

use crate::error::{MindLeakError, Result};
use crate::graph::{GraphStore, WriteOutcome};
use crate::ingest::{normalize_path, short_hash};
use crate::model::{Edge, Node, NodeType, RelationType};

const MAX_IMPACTED_FILES: usize = 200;
const MAX_IMPACTED_PATH_BYTES: usize = 1_024;

/// One file the consolidated intent touched, with the model's chosen relation.
///
/// Deserialization is tolerant of the LLM boundary: the model may return either a
/// bare path string or a `{ "path": ..., "relation": ... }` object. The relation
/// is advisory — [`consolidation_relation`] validates it deterministically before
/// any edge is created, so the engine (not the model) decides the final relation.
#[derive(Debug, Clone, Serialize)]
pub struct ImpactedFile {
    pub path: String,
    pub relation: String,
}

impl<'de> Deserialize<'de> for ImpactedFile {
    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum Raw {
            Path(String),
            Object {
                path: String,
                #[serde(default)]
                relation: String,
            },
        }
        Ok(match Raw::deserialize(deserializer)? {
            Raw::Path(path) => ImpactedFile {
                path,
                relation: String::new(),
            },
            Raw::Object { path, relation } => ImpactedFile { path, relation },
        })
    }
}

/// Structured summary the model is asked to return.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntentSummary {
    pub intent_label: String,
    #[serde(default)]
    pub impacted_files: Vec<ImpactedFile>,
    #[serde(default)]
    pub status: String,
}

/// Deterministic graph facts derived after model inference succeeds.
#[derive(Debug, Clone)]
pub struct ConsolidationFacts {
    pub intent_id: String,
    pub nodes: Vec<Node>,
    pub edges: Vec<Edge>,
}

/// An OpenAI-compatible consolidation client (points at a local server by default).
#[derive(Debug, Clone)]
pub struct Consolidator {
    /// OpenAI-compatible base URL, e.g. `http://localhost:11434/v1` (Ollama).
    pub base_url: String,
    pub model: String,
    /// Optional bearer token for hosted servers; empty means no auth header.
    pub api_key: String,
}

impl Default for Consolidator {
    fn default() -> Self {
        let base_url = std::env::var("MINDLEAK_LLM_URL")
            .unwrap_or_else(|_| "http://localhost:11434/v1".to_string());
        let model = std::env::var("MINDLEAK_MODEL").unwrap_or_else(|_| "glm4:9b".to_string());
        let api_key = std::env::var("MINDLEAK_LLM_API_KEY").unwrap_or_default();
        Consolidator {
            base_url,
            model,
            api_key,
        }
    }
}

impl Consolidator {
    pub fn new(base_url: impl Into<String>, model: impl Into<String>) -> Self {
        Consolidator {
            base_url: base_url.into(),
            model: model.into(),
            api_key: String::new(),
        }
    }

    /// Call the OpenAI-compatible `/chat/completions` endpoint with a JSON
    /// `response_format` and parse the returned summary.
    pub fn consolidate(&self, logs: &[String]) -> Result<IntentSummary> {
        self.consolidate_with_cancel(logs, || false)
    }

    pub fn consolidate_with_cancel<F>(
        &self,
        logs: &[String],
        should_cancel: F,
    ) -> Result<IntentSummary>
    where
        F: Fn() -> bool,
    {
        let body = serde_json::json!({
            "model": self.model,
            "stream": false,
            "response_format": { "type": "json_object" },
            "messages": [
                {
                    "role": "system",
                    "content": "You are a background graph extraction engine. Compress raw execution logs into a single structured intent node. Respond with ONLY a JSON object with keys: intent_label (string), impacted_files (array of objects, each with keys path (string) and relation (string)), status (string). For each impacted file choose exactly one relation from this closed set: \"fixed\", \"refactored\", \"relates_to\". Use \"fixed\" for a file addressed by a fix:/bug line, \"relates_to\" for a file tied to a DECISION:/WHY: rationale marker, and \"refactored\" otherwise. Do not invent relation names outside that set."
                },
                { "role": "user", "content": logs.join("\n") }
            ]
        });

        let url = format!("{}/chat/completions", self.base_url.trim_end_matches('/'));
        let value = crate::net::post_json_with_cancel(
            &crate::net::HttpConfig::default(),
            &url,
            &self.api_key,
            &body,
            should_cancel,
        )?;
        let content = value
            .get("choices")
            .and_then(|c| c.get(0))
            .and_then(|c| c.get("message"))
            .and_then(|m| m.get("content"))
            .and_then(|c| c.as_str())
            .ok_or_else(|| {
                MindLeakError::Http("chat completion missing choices[0].message.content".into())
            })?;

        let summary: IntentSummary = serde_json::from_str(extract_json(content))?;
        Ok(summary)
    }

    /// Consolidate a batch of logs and write the resulting intent into the graph,
    /// linked to each impacted artifact. Returns the created intent id + counts.
    pub fn consolidate_and_store(
        &self,
        store: &GraphStore,
        logs: &[String],
        now: i64,
    ) -> Result<(String, WriteOutcome)> {
        let summary = self.consolidate(logs)?;
        let facts = facts_from_summary(&summary, logs.len(), now)?;
        let mut outcome = store.upsert_facts(&facts.nodes, &facts.edges)?;
        outcome.node_ids.push(facts.intent_id.clone());
        Ok((facts.intent_id, outcome))
    }
}

/// Convert a model summary into deterministic graph facts. Kept separate so
/// signal consolidation can commit these facts and raw acknowledgement in one
/// SQLite transaction.
pub fn facts_from_summary(
    summary: &IntentSummary,
    source_event_count: usize,
    now: i64,
) -> Result<ConsolidationFacts> {
    let label = summary.intent_label.trim();
    if label.is_empty() {
        return Err(MindLeakError::Other(
            "consolidation summary has an empty intent_label".to_string(),
        ));
    }
    let intent_id = format!("intent:{}", short_hash(label));
    let status = summary.status.trim().replace(['\r', '\n'], " ");
    let intent = Node::new(
        &intent_id,
        NodeType::Intent,
        crate::ingest::clamp(label, 200),
        now,
    )
    .with_content(format!(
        "status={}\nsource_events={source_event_count}",
        crate::ingest::clamp(&status, 200)
    ));
    let mut nodes = vec![intent];
    let mut edges = Vec::new();
    let mut seen = HashSet::new();
    for file in summary.impacted_files.iter().take(MAX_IMPACTED_FILES) {
        let path = normalize_path(&file.path);
        if path.trim().is_empty()
            || path.len() > MAX_IMPACTED_PATH_BYTES
            || !seen.insert(path.clone())
        {
            continue;
        }
        let artifact_id = format!("artifact:{path}");
        nodes.push(Node::new(
            &artifact_id,
            NodeType::Artifact,
            path.clone(),
            now,
        ));
        edges.push(Edge::new(
            &intent_id,
            &artifact_id,
            consolidation_relation(&file.relation),
            now,
        ));
    }
    Ok(ConsolidationFacts {
        intent_id,
        nodes,
        edges,
    })
}

/// Map the model's advisory relation string onto the closed set of relations
/// valid for a consolidation intent -> artifact edge. The engine — not the LLM —
/// decides the final [`RelationType`]: anything outside `fixed` / `refactored` /
/// `relates_to` (omitted, unknown, or a structural/execution relation the model
/// should never emit here) is coerced to the safe `refactored` default. The match
/// is exhaustive so a newly added [`RelationType`] variant forces a decision here
/// rather than being silently swallowed.
fn consolidation_relation(model_relation: &str) -> RelationType {
    let Some(parsed) = RelationType::from_tag(model_relation.trim()) else {
        return RelationType::Refactored;
    };
    match parsed {
        RelationType::Fixed => RelationType::Fixed,
        RelationType::RelatesTo => RelationType::RelatesTo,
        RelationType::Refactored => RelationType::Refactored,
        RelationType::Modified
        | RelationType::FailedOn
        | RelationType::Calls
        | RelationType::Contains
        | RelationType::Observed
        | RelationType::Imports
        | RelationType::Extends
        | RelationType::Implements
        | RelationType::DependsOn => RelationType::Refactored,
    }
}

/// Extract the first JSON object from model content that may be wrapped in a
/// markdown code fence or surrounded by prose (glm4 and others do this even with
/// `response_format: json_object`). Braces are ASCII, so byte slicing is safe.
fn extract_json(content: &str) -> &str {
    match (content.find('{'), content.rfind('}')) {
        (Some(start), Some(end)) if end >= start => &content[start..=end],
        _ => content.trim(),
    }
}

#[cfg(test)]
mod tests {
    // Generated by AI (UnitTest MCP)
    use super::*;

    #[test]
    fn extract_json_pulls_object_from_fence_or_prose() {
        assert_eq!(extract_json("```json\n{\"a\":1}\n```"), "{\"a\":1}");
        assert_eq!(extract_json("Sure:\n{\"a\":1} done"), "{\"a\":1}");
        assert_eq!(extract_json("{\"a\":1}"), "{\"a\":1}");
    }

    #[test]
    fn new_sets_fields() {
        let c = Consolidator::new("http://host:1234", "codegeex4:9b");
        assert_eq!(c.base_url, "http://host:1234");
        assert_eq!(c.model, "codegeex4:9b");
    }

    #[test]
    fn intent_summary_defaults_missing_fields() {
        let s: IntentSummary =
            serde_json::from_str(r#"{"intent_label":"fix null token"}"#).unwrap();
        assert_eq!(s.intent_label, "fix null token");
        assert!(s.impacted_files.is_empty());
        assert_eq!(s.status, "");
    }

    #[test]
    fn intent_summary_parses_full_payload() {
        // Tolerant at the LLM boundary: accepts both an object with a relation and
        // a bare path string (which yields an empty, later-defaulted relation).
        let json = r#"{"intent_label":"refactor auth","impacted_files":[{"path":"src/auth.rs","relation":"fixed"},"src/util.rs"],"status":"PASSING"}"#;
        let s: IntentSummary = serde_json::from_str(json).unwrap();
        assert_eq!(s.impacted_files.len(), 2);
        assert_eq!(s.impacted_files[0].path, "src/auth.rs");
        assert_eq!(s.impacted_files[0].relation, "fixed");
        assert_eq!(s.impacted_files[1].path, "src/util.rs");
        assert_eq!(s.impacted_files[1].relation, "");
        assert_eq!(s.status, "PASSING");
    }

    #[test]
    fn summary_facts_normalize_and_deduplicate_impacted_files() {
        let summary = IntentSummary {
            intent_label: "fix auth".to_string(),
            impacted_files: vec![
                ImpactedFile {
                    path: "src\\auth.rs".to_string(),
                    relation: String::new(),
                },
                ImpactedFile {
                    path: "src/auth.rs".to_string(),
                    relation: String::new(),
                },
            ],
            status: "passing".to_string(),
        };

        let facts = facts_from_summary(&summary, 1, 100).unwrap();

        assert!(facts.intent_id.starts_with("intent:"));
        assert_eq!(facts.nodes.len(), 2);
        assert_eq!(facts.edges.len(), 1);
        assert_eq!(facts.edges[0].target_id, "artifact:src/auth.rs");
        let content = facts.nodes[0].content.as_deref().unwrap();
        assert_eq!(content, "status=passing\nsource_events=1");
        assert!(!content.contains("test passed"));
    }

    #[test]
    fn summary_facts_reject_empty_label_and_ignore_blank_paths() {
        let empty = IntentSummary {
            intent_label: "  ".to_string(),
            impacted_files: vec![],
            status: String::new(),
        };
        assert!(facts_from_summary(&empty, 1, 100).is_err());

        let valid = IntentSummary {
            intent_label: "gist".to_string(),
            impacted_files: vec![ImpactedFile {
                path: "  ".to_string(),
                relation: String::new(),
            }],
            status: String::new(),
        };
        let facts = facts_from_summary(&valid, 1, 100).unwrap();
        assert_eq!(facts.nodes.len(), 1);
        assert!(facts.edges.is_empty());
    }

    #[test]
    fn summary_facts_bound_model_supplied_files_and_paths() {
        let mut impacted_files: Vec<ImpactedFile> = (0..250)
            .map(|index| ImpactedFile {
                path: format!("src/file-{index}.rs"),
                relation: String::new(),
            })
            .collect();
        impacted_files[0].path = "x".repeat(MAX_IMPACTED_PATH_BYTES + 1);
        let summary = IntentSummary {
            intent_label: "bounded gist".to_string(),
            impacted_files,
            status: String::new(),
        };

        let facts = facts_from_summary(&summary, 20, 100).unwrap();

        assert_eq!(facts.edges.len(), MAX_IMPACTED_FILES - 1);
        assert_eq!(facts.nodes.len(), MAX_IMPACTED_FILES);
    }

    #[test]
    fn fix_relation_maps_to_fixed_not_refactored() {
        // Regression: fix:/bug work must not be mislabelled as `refactored`.
        let summary = IntentSummary {
            intent_label: "fix null token".to_string(),
            impacted_files: vec![ImpactedFile {
                path: "src/auth.rs".to_string(),
                relation: "fixed".to_string(),
            }],
            status: "passing".to_string(),
        };
        let facts = facts_from_summary(&summary, 1, 100).unwrap();
        assert_eq!(facts.edges[0].relation, RelationType::Fixed);
    }

    #[test]
    fn decision_rationale_maps_to_relates_to_not_refactored() {
        // Regression: a DECISION:/WHY: rationale link is `relates_to`, not `refactored`.
        let summary = IntentSummary {
            intent_label: "record decision".to_string(),
            impacted_files: vec![ImpactedFile {
                path: "src/lib.rs".to_string(),
                relation: "relates_to".to_string(),
            }],
            status: String::new(),
        };
        let facts = facts_from_summary(&summary, 1, 100).unwrap();
        assert_eq!(facts.edges[0].relation, RelationType::RelatesTo);
    }

    #[test]
    fn out_of_vocabulary_relation_coerces_to_the_default() {
        // The engine, not the model, decides: an unknown string is not persisted verbatim.
        let summary = IntentSummary {
            intent_label: "weird".to_string(),
            impacted_files: vec![ImpactedFile {
                path: "src/x.rs".to_string(),
                relation: "teleported".to_string(),
            }],
            status: String::new(),
        };
        let facts = facts_from_summary(&summary, 1, 100).unwrap();
        assert_eq!(facts.edges[0].relation, RelationType::Refactored);
    }

    #[test]
    fn structural_relation_is_not_a_valid_consolidation_edge() {
        // A valid RelationType that is nonetheless wrong for an intent -> artifact
        // edge (a structural/execution relation) is coerced to the safe default.
        let summary = IntentSummary {
            intent_label: "misclassified".to_string(),
            impacted_files: vec![ImpactedFile {
                path: "src/y.rs".to_string(),
                relation: "modified".to_string(),
            }],
            status: String::new(),
        };
        let facts = facts_from_summary(&summary, 1, 100).unwrap();
        assert_eq!(facts.edges[0].relation, RelationType::Refactored);
    }

    #[test]
    fn omitted_relation_defaults_to_refactored() {
        let summary = IntentSummary {
            intent_label: "no relation given".to_string(),
            impacted_files: vec![ImpactedFile {
                path: "src/z.rs".to_string(),
                relation: String::new(),
            }],
            status: String::new(),
        };
        let facts = facts_from_summary(&summary, 1, 100).unwrap();
        assert_eq!(facts.edges[0].relation, RelationType::Refactored);
    }

    /// Live round-trip against a running OpenAI-compatible server (Ollama +
    /// `glm4:9b` by default). Ignored in normal runs; exercise with
    /// `cargo test -p mindleak-core -- --ignored`. Proves the model honours our
    /// JSON `response_format` contract end to end.
    #[test]
    #[ignore = "requires a running local model (e.g. `ollama run glm4:9b`)"]
    fn live_consolidate_round_trip() {
        let logs = vec![
            "$ cargo test  ->  exit 101".to_string(),
            "thread 'auth' panicked at src/auth.rs:42: token was null".to_string(),
            "$ cargo test  ->  exit 0 (after null-guarding the JWT path)".to_string(),
        ];
        let summary = Consolidator::default()
            .consolidate(&logs)
            .expect("live consolidation should return a parsed IntentSummary");
        assert!(
            !summary.intent_label.trim().is_empty(),
            "model returned an empty intent_label: {summary:?}"
        );
        eprintln!("live consolidate -> {summary:?}");
    }
}
