// Generated by AI (UnitTest MCP)
//! End-to-end integration tests over the Lodestar facade, including a real
//! multi-connection claim race that proves collision-free coordination.

use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use lodestar_core::{
    now_unix, CodeBindingMode, ConformanceEvidence, EvidenceProvenance, GoalKind, Lodestar,
    TaskStatus, Verdict,
};

/// A unique temp DB path per test (file-backed so multiple connections share it).
fn temp_db(tag: &str) -> String {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let mut p = std::env::temp_dir();
    p.push(format!("lodestar-{tag}-{}-{nanos}.db", std::process::id()));
    p.to_string_lossy().into_owned()
}

fn cleanup(path: &str) {
    let _ = std::fs::remove_file(path);
    let _ = std::fs::remove_file(format!("{path}-wal"));
    let _ = std::fs::remove_file(format!("{path}-shm"));
}

#[test]
fn goal_task_claim_complete_flow() {
    let engine = Lodestar::open_in_memory().unwrap();
    let g = engine
        .define_goal(GoalKind::Objective, "Ship search", "Add FTS search", None)
        .unwrap();
    let t = engine.create_task(&g.id, "wire fts", "tests pass").unwrap();
    engine
        .link_goal_to_code(
            &g.id,
            &["artifact:src/search.rs".into()],
            CodeBindingMode::Governed,
        )
        .unwrap();

    assert!(engine.claim_task(&t.id, "agent-a", 300).unwrap());
    let claim = engine.store().get_task(&t.id).unwrap().unwrap();
    let evidence = evidence(
        &t.id,
        "agent-a",
        "artifact:src/search.rs",
        claim.claim_started_at.unwrap(),
    );
    let (completed, conformance) = engine.complete_task(&t.id, "agent-a", &evidence).unwrap();
    assert!(completed);
    assert_eq!(conformance.verdict, Verdict::Aligned);
    assert_eq!(
        engine.store().get_task(&t.id).unwrap().unwrap().status,
        TaskStatus::Done
    );

    // The completion leaves a durable, resolvable evidence link: the task's
    // conformance history returns the exact bundle that proved it done.
    let history = engine.conformance_history(&t.id).unwrap();
    assert_eq!(history.len(), 1);
    let record = &history[0];
    assert!(record.id > 0);
    assert_eq!(record.verdict, Verdict::Aligned);
    let recorded: ConformanceEvidence = serde_json::from_str(&record.evidence).unwrap();
    assert_eq!(recorded.task_id.as_deref(), Some(t.id.as_str()));
    assert_eq!(recorded.changed_node_ids, vec!["artifact:src/search.rs"]);
}

fn evidence(
    task_id: &str,
    agent: &str,
    changed_node_id: &str,
    started_at: i64,
) -> ConformanceEvidence {
    ConformanceEvidence {
        schema_version: 1,
        task_id: Some(task_id.into()),
        agent_id: agent.into(),
        started_at,
        ended_at: now_unix(),
        changed_node_ids: vec![changed_node_id.into()],
        failed_node_ids: Vec::new(),
        execution_ids: vec!["execution:proof".into()],
        successful_execution_ids: vec!["execution:proof".into()],
        commit_ids: Vec::new(),
        summary: format!("changed {changed_node_id}"),
        provenance: vec![
            EvidenceProvenance {
                source_id: format!("agent:{agent}"),
                target_id: "execution:proof".into(),
                relation: "observed".into(),
            },
            EvidenceProvenance {
                source_id: "execution:proof".into(),
                target_id: changed_node_id.into(),
                relation: "modified".into(),
            },
        ],
    }
}

#[test]
fn missing_evidence_stays_in_review() {
    let engine = Lodestar::open_in_memory().unwrap();
    let goal = engine
        .define_goal(GoalKind::Objective, "Ship auth", "change auth", None)
        .unwrap();
    engine
        .link_goal_to_code(
            &goal.id,
            &["artifact:src/auth.rs".into()],
            CodeBindingMode::Governed,
        )
        .unwrap();
    let task = engine.create_task(&goal.id, "change auth", "").unwrap();
    engine.claim_task(&task.id, "agent-a", 300).unwrap();
    let claim = engine.store().get_task(&task.id).unwrap().unwrap();
    let empty = ConformanceEvidence {
        schema_version: 1,
        task_id: Some(task.id.clone()),
        agent_id: "agent-a".into(),
        started_at: claim.claim_started_at.unwrap(),
        ended_at: now_unix(),
        changed_node_ids: Vec::new(),
        failed_node_ids: Vec::new(),
        execution_ids: Vec::new(),
        successful_execution_ids: Vec::new(),
        commit_ids: Vec::new(),
        summary: "no activity".into(),
        provenance: Vec::new(),
    };

    let (completed, result) = engine.complete_task(&task.id, "agent-a", &empty).unwrap();
    assert!(!completed);
    assert_eq!(result.verdict, Verdict::NeedsHuman);
    assert_eq!(
        engine.store().get_task(&task.id).unwrap().unwrap().status,
        TaskStatus::InReview
    );
}

#[test]
fn wrong_goal_drift_stays_in_review() {
    let engine = Lodestar::open_in_memory().unwrap();
    let task_goal = engine
        .define_goal(GoalKind::Objective, "Ship auth", "change auth", None)
        .unwrap();
    let other_goal = engine
        .define_goal(GoalKind::Objective, "Ship billing", "change billing", None)
        .unwrap();
    engine
        .link_goal_to_code(
            &other_goal.id,
            &["artifact:src/billing.rs".into()],
            CodeBindingMode::Governed,
        )
        .unwrap();
    let task = engine
        .create_task(&task_goal.id, "change auth", "")
        .unwrap();
    engine.claim_task(&task.id, "agent-a", 300).unwrap();
    let claim = engine.store().get_task(&task.id).unwrap().unwrap();
    let evidence = evidence(
        &task.id,
        "agent-a",
        "artifact:src/billing.rs",
        claim.claim_started_at.unwrap(),
    );

    let (completed, result) = engine
        .complete_task(&task.id, "agent-a", &evidence)
        .unwrap();
    assert!(!completed);
    assert_eq!(result.verdict, Verdict::Drift);
    assert_eq!(
        engine.store().get_task(&task.id).unwrap().unwrap().status,
        TaskStatus::InReview
    );
}

#[test]
fn forbidden_change_blocks_completion() {
    let engine = Lodestar::open_in_memory().unwrap();
    let goal = engine
        .define_goal(
            GoalKind::Invariant,
            "Protect schema",
            "schema cannot change",
            None,
        )
        .unwrap();
    engine
        .link_goal_to_code(
            &goal.id,
            &["artifact:src/schema.sql".into()],
            CodeBindingMode::ForbidChange,
        )
        .unwrap();
    let task = engine.create_task(&goal.id, "inspect schema", "").unwrap();
    engine.claim_task(&task.id, "agent-a", 300).unwrap();
    let claim = engine.store().get_task(&task.id).unwrap().unwrap();
    let evidence = evidence(
        &task.id,
        "agent-a",
        "artifact:src/schema.sql",
        claim.claim_started_at.unwrap(),
    );

    let (completed, result) = engine
        .complete_task(&task.id, "agent-a", &evidence)
        .unwrap();
    assert!(!completed);
    assert_eq!(result.verdict, Verdict::Violation);
    assert_eq!(
        engine.store().get_task(&task.id).unwrap().unwrap().status,
        TaskStatus::Blocked
    );
}

#[test]
fn cross_agent_and_out_of_window_evidence_are_rejected() {
    let engine = Lodestar::open_in_memory().unwrap();
    let goal = engine
        .define_goal(GoalKind::Objective, "Ship auth", "change auth", None)
        .unwrap();
    engine
        .link_goal_to_code(
            &goal.id,
            &["artifact:src/auth.rs".into()],
            CodeBindingMode::Governed,
        )
        .unwrap();
    let task = engine.create_task(&goal.id, "change auth", "").unwrap();
    engine.claim_task(&task.id, "agent-a", 300).unwrap();
    let claim = engine.store().get_task(&task.id).unwrap().unwrap();

    let wrong_agent = evidence(
        &task.id,
        "agent-b",
        "artifact:src/auth.rs",
        claim.claim_started_at.unwrap(),
    );
    assert!(engine
        .complete_task(&task.id, "agent-a", &wrong_agent)
        .is_err());

    let outside = evidence(
        &task.id,
        "agent-a",
        "artifact:src/auth.rs",
        claim.claim_started_at.unwrap() - 1,
    );
    assert!(engine.complete_task(&task.id, "agent-a", &outside).is_err());
    assert_eq!(
        engine.store().get_task(&task.id).unwrap().unwrap().status,
        TaskStatus::Claimed
    );
}

#[test]
fn claim_is_collision_free_across_connections() {
    let path = temp_db("race");
    {
        let engine = Lodestar::open(&path).unwrap();
        let g = engine
            .define_goal(GoalKind::Objective, "Race", "one winner only", None)
            .unwrap();
        let t = engine.create_task(&g.id, "contended", "").unwrap();

        let wins = Arc::new(AtomicUsize::new(0));
        let mut handles = Vec::new();
        for i in 0..8 {
            let path = path.clone();
            let task_id = t.id.clone();
            let wins = Arc::clone(&wins);
            handles.push(std::thread::spawn(move || {
                let e = Lodestar::open(&path).unwrap();
                if e.claim_task(&task_id, &format!("agent-{i}"), 60).unwrap() {
                    wins.fetch_add(1, Ordering::SeqCst);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        // Exactly one of eight racing agents may hold the claim.
        assert_eq!(wins.load(Ordering::SeqCst), 1);
    }
    cleanup(&path);
}

#[test]
fn shared_db_is_visible_across_worktree_connections() {
    let path = temp_db("shared");
    {
        // "Worktree A" defines intent...
        let a = Lodestar::open(&path).unwrap();
        let g = a
            .define_goal(GoalKind::Invariant, "Zero token", "no llm on ingest", None)
            .unwrap();
        a.create_task(&g.id, "enforce", "").unwrap();

        // ..."worktree B" (a separate connection) sees it.
        let b = Lodestar::open(&path).unwrap();
        assert_eq!(b.get_constitution().unwrap().len(), 1);
        let next = b.next_task().unwrap().unwrap();
        assert_eq!(next.goal_id, g.id);
    }
    cleanup(&path);
}
