// Generated by AI (UnitTest MCP)

use std::time::{Duration, SystemTime};

use ackplane_protocol::delegation::DelegatedAction;

use super::super::{
    DelegationGrantRequest, DelegationProjectionStatus, DelegationRevocationRequest,
    DelegationStore,
};

fn unique_scope(label: &str) -> (String, String) {
    let mut bytes = [0_u8; 8];
    getrandom::getrandom(&mut bytes).expect("the OS random source should be available");
    let suffix: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    (
        format!("tenant-delegation-read-{label}-{suffix}"),
        format!("repository-delegation-read-{label}-{suffix}"),
    )
}

fn grant_request(tenant_id: String, repository_id: String, label: &str) -> DelegationGrantRequest {
    let now = SystemTime::now();
    DelegationGrantRequest {
        tenant_id,
        repository_id,
        verified_issuer_principal_id: format!("principal:human-{label}"),
        delegatee_session_id: format!("session:v1:agent-{label}"),
        project_id: Some(format!("project:{label}")),
        task_id: Some(format!("task:{label}")),
        goal_id: format!("goal:{label}"),
        goal_digest: vec![1; 32],
        policy_version: "policy:v1".to_string(),
        policy_digest: vec![2; 32],
        constitution_version: "constitution:v1".to_string(),
        constitution_digest: vec![3; 32],
        allowed_actions: vec![DelegatedAction::RetrieveContext],
        max_token_budget: 1_024,
        max_actions_per_session: 8,
        source_protocol_version: 1,
        effective_at: now - Duration::from_secs(1),
        expires_at: now + Duration::from_secs(600),
        idempotency_key: format!("delegation:read-{label}"),
    }
}

#[tokio::test]
async fn list_returns_current_projections_in_durable_order_and_keeps_scopes_isolated() {
    let Some(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL").ok() else {
        println!("skipped: ACKPLANE_TEST_DATABASE_URL not set");
        return;
    };
    let (tenant_id, repository_id) = unique_scope("primary");
    let (foreign_tenant_id, foreign_repository_id) = unique_scope("foreign");
    let mut store = DelegationStore::connect(&database_url)
        .await
        .expect("the test database should accept delegation connections");

    assert_eq!(
        store
            .list(&tenant_id, &repository_id)
            .await
            .expect("empty delegation list"),
        Vec::new()
    );

    let first = store
        .grant(grant_request(
            tenant_id.clone(),
            repository_id.clone(),
            "first",
        ))
        .await
        .expect("grant first delegation");
    let second = store
        .grant(grant_request(
            tenant_id.clone(),
            repository_id.clone(),
            "second",
        ))
        .await
        .expect("grant second delegation");
    let revoked = store
        .revoke(DelegationRevocationRequest {
            tenant_id: tenant_id.clone(),
            repository_id: repository_id.clone(),
            delegation_id: first.projection.delegation_id.clone(),
            verified_revoker_principal_id: "principal:human-revoker".to_string(),
            reason: "scope no longer approved".to_string(),
            expected_version: 1,
            idempotency_key: "delegation:read-revoke".to_string(),
        })
        .await
        .expect("revoke first delegation");

    assert_eq!(
        store
            .list(&tenant_id, &repository_id)
            .await
            .expect("list current delegation projections"),
        vec![second.projection, revoked.projection]
    );
    assert_eq!(
        store
            .list(&foreign_tenant_id, &repository_id)
            .await
            .expect("foreign tenant list"),
        Vec::new()
    );
    assert_eq!(
        store
            .list(&tenant_id, &foreign_repository_id)
            .await
            .expect("foreign repository list"),
        Vec::new()
    );
    assert_eq!(
        store
            .get(&tenant_id, &repository_id, &first.projection.delegation_id)
            .await
            .expect("read revoked delegation")
            .expect("revoked delegation remains projected")
            .status,
        DelegationProjectionStatus::Revoked
    );
}
