// Generated by AI (UnitTest MCP)
use std::path::PathBuf;

use crate::db;
use crate::model::{Goal, GoalKind, TaskStatus, Verdict};

use super::{ConformanceAudit, LodestarStore};

pub(super) const NOW: i64 = 1_000_000;
pub(super) const HOUR: i64 = 3600;

pub(super) fn store() -> LodestarStore {
    LodestarStore::new(db::open_in_memory().unwrap())
}

pub(super) fn goal(s: &LodestarStore) -> Goal {
    s.define_goal(
        GoalKind::Objective,
        "Ship the thing",
        "Do it well",
        None,
        NOW,
    )
    .unwrap()
}

pub(super) fn complete_aligned(store: &LodestarStore, task_id: &str, agent: &str, now: i64) {
    assert!(store.claim_task(task_id, agent, 60, now).unwrap());
    assert!(store
        .record_conformance_and_transition(
            task_id,
            agent,
            ConformanceAudit {
                evidence_schema_version: 1,
                evidence: "{}",
                verdict: Verdict::Aligned,
                findings: "",
            },
            TaskStatus::Done,
            now,
        )
        .unwrap());
}

pub(super) fn temporary_database(name: &str, iteration: usize) -> PathBuf {
    let path = std::env::temp_dir().join(format!(
        "lodestar-{name}-{}-{iteration}.db",
        std::process::id()
    ));
    let _ = std::fs::remove_file(&path);
    path
}
