// Generated by AI (UnitTest MCP)
//! Graph storage and decay-aware traversal over SQLite.

use rusqlite::Connection;

use crate::config::{
    DecayPolicy, DEFAULT_WORKING_SET_SIZE, MAX_WORKING_SET_SIZE, MIN_WORKING_SET_SIZE,
};

mod evidence;
mod lifecycle;
mod query;
mod signal;
#[cfg(test)]
mod test_support;
mod types;
mod writes;

pub use types::{
    AgentActivity, ArtifactStub, ConformanceEvidence, Direction, EvidenceProvenance, ForgetOutcome,
    GraphExport, PromotionCandidate, PruneOutcome, ResetOutcome, ScoredNode, SignalCandidate,
    SignalConsolidationOutcome, Subgraph, WeightedEdge, WorkingSetItem, WriteOutcome,
};

/// The persistent graph store.
pub struct GraphStore {
    pub(crate) conn: Connection,
    decay_policy: DecayPolicy,
    working_set_size: usize,
}

impl GraphStore {
    pub fn new(conn: Connection) -> Self {
        GraphStore {
            conn,
            decay_policy: DecayPolicy::default(),
            working_set_size: DEFAULT_WORKING_SET_SIZE,
        }
    }

    pub fn with_decay_policy(mut self, decay_policy: DecayPolicy) -> Self {
        self.decay_policy = decay_policy;
        self
    }

    pub fn decay_policy(&self) -> &DecayPolicy {
        &self.decay_policy
    }

    pub fn with_working_set_size(mut self, size: usize) -> Self {
        self.working_set_size = size.clamp(MIN_WORKING_SET_SIZE, MAX_WORKING_SET_SIZE);
        self
    }

    pub fn working_set_size(&self) -> usize {
        self.working_set_size
    }
}
