//! Minimal MCP stdio transport: newline-delimited JSON-RPC 2.0.

use std::io::{self, BufRead, Write};

use mindleak_core::MindLeak;
use mindleak_session::SessionRegistry;
use serde_json::{json, Value};

use crate::maintenance::ActivitySignal;
use crate::tools;

const PROTOCOL_VERSION: &str = "2024-11-05";

/// Run the blocking request/response loop until stdin closes.
pub fn run(
    engine: MindLeak,
    sessions: SessionRegistry,
    activity: ActivitySignal,
) -> anyhow::Result<()> {
    let stdin = io::stdin();
    let mut reader = stdin.lock();
    let stdout = io::stdout();
    let mut out = stdout.lock();

    let mut line = String::new();
    loop {
        line.clear();
        let read = reader.read_line(&mut line)?;
        if read == 0 {
            break; // EOF
        }
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let _request_activity = activity.begin_request();

        let request: Value = match serde_json::from_str(trimmed) {
            Ok(v) => v,
            Err(e) => {
                write_message(
                    &mut out,
                    &error_response(Value::Null, -32700, &format!("parse error: {e}")),
                )?;
                continue;
            }
        };

        if let Some(response) = handle(&engine, &sessions, &request) {
            write_message(&mut out, &response)?;
        }
    }
    Ok(())
}

fn handle(engine: &MindLeak, sessions: &SessionRegistry, req: &Value) -> Option<Value> {
    let id = req.get("id").cloned();
    let method = req.get("method").and_then(Value::as_str).unwrap_or("");
    let params = req.get("params").cloned().unwrap_or(Value::Null);

    match method {
        "initialize" => Some(result_response(id?, initialize_result())),
        "notifications/initialized" | "notifications/cancelled" => None,
        "ping" => Some(result_response(id?, json!({}))),
        "tools/list" => Some(result_response(id?, json!({ "tools": tools::list() }))),
        "tools/call" => {
            let id = id?;
            let response = match tools::bind_session(&params, sessions)
                .and_then(|bound| tools::call(engine, &bound))
            {
                Ok(content) => content,
                Err(msg) => tool_error(&msg),
            };
            Some(result_response(id, response))
        }
        "shutdown" => Some(result_response(id?, Value::Null)),
        other => match id {
            Some(id) if !id.is_null() => Some(error_response(
                id,
                -32601,
                &format!("method not found: {other}"),
            )),
            _ => None,
        },
    }
}

fn initialize_result() -> Value {
    json!({
        "protocolVersion": PROTOCOL_VERSION,
        "capabilities": { "tools": { "listChanged": false } },
        "serverInfo": {
            "name": "mindleak-mcp",
            "version": format!(
                "{}+{}",
                env!("CARGO_PKG_VERSION"),
                env!("MINDLEAK_BUILD_SHA")
            )
        }
    })
}

fn tool_error(message: &str) -> Value {
    json!({
        "content": [{ "type": "text", "text": message }],
        "isError": true
    })
}

fn result_response(id: Value, result: Value) -> Value {
    json!({ "jsonrpc": "2.0", "id": id, "result": result })
}

fn error_response(id: Value, code: i64, message: &str) -> Value {
    json!({ "jsonrpc": "2.0", "id": id, "error": { "code": code, "message": message } })
}

fn write_message(out: &mut impl Write, value: &Value) -> io::Result<()> {
    let text = serde_json::to_string(value).unwrap_or_else(|_| "{}".to_string());
    out.write_all(text.as_bytes())?;
    out.write_all(b"\n")?;
    out.flush()
}

#[cfg(test)]
mod tests {
    // Generated by AI (UnitTest MCP)
    use super::*;
    use mindleak_core::MindLeak;

    fn engine() -> MindLeak {
        MindLeak::open_in_memory().unwrap()
    }

    fn sessions() -> SessionRegistry {
        SessionRegistry::new("test").unwrap()
    }

    #[test]
    fn initialize_reports_server_info() {
        let req = json!({ "jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {} });
        let resp = handle(&engine(), &sessions(), &req).unwrap();
        assert_eq!(resp["result"]["serverInfo"]["name"], "mindleak-mcp");
        assert_eq!(
            resp["result"]["serverInfo"]["version"],
            format!(
                "{}+{}",
                env!("CARGO_PKG_VERSION"),
                env!("MINDLEAK_BUILD_SHA")
            )
        );
        assert_eq!(resp["result"]["protocolVersion"], PROTOCOL_VERSION);
    }

    #[test]
    fn tools_list_returns_tool_array() {
        let req = json!({ "jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {} });
        let resp = handle(&engine(), &sessions(), &req).unwrap();
        assert!(resp["result"]["tools"].as_array().unwrap().len() >= 10);
    }

    #[test]
    fn tools_call_returns_content() {
        let req = json!({
            "jsonrpc": "2.0", "id": 3, "method": "tools/call",
            "params": { "name": "graph_stats", "arguments": {} }
        });
        let resp = handle(&engine(), &sessions(), &req).unwrap();
        assert!(resp["result"]["content"][0]["text"].is_string());
    }

    #[test]
    fn notification_produces_no_response() {
        let req = json!({ "jsonrpc": "2.0", "method": "notifications/initialized" });
        assert!(handle(&engine(), &sessions(), &req).is_none());
    }

    #[test]
    fn ping_returns_empty_result() {
        let req = json!({ "jsonrpc": "2.0", "id": 4, "method": "ping" });
        let resp = handle(&engine(), &sessions(), &req).unwrap();
        assert_eq!(resp["result"], json!({}));
    }

    #[test]
    fn unknown_method_returns_method_not_found() {
        let req = json!({ "jsonrpc": "2.0", "id": 5, "method": "does_not_exist" });
        let resp = handle(&engine(), &sessions(), &req).unwrap();
        assert_eq!(resp["error"]["code"], -32601);
    }

    #[test]
    fn multiplexed_sessions_produce_distinct_evidence() {
        let engine = engine();
        let sessions = sessions();
        for (id, token, sha, path) in [
            (
                10,
                "00112233445566778899aabbccddeeff",
                "session-a",
                "src/a.rs",
            ),
            (
                11,
                "ffeeddccbbaa99887766554433221100",
                "session-b",
                "src/b.rs",
            ),
        ] {
            let open = json!({
                "jsonrpc": "2.0", "id": id, "method": "tools/call",
                "params": { "name": "open_session", "arguments": { "session_id": token } }
            });
            handle(&engine, &sessions, &open).unwrap();
            let ingest = json!({
                "jsonrpc": "2.0", "id": id + 10, "method": "tools/call",
                "params": { "name": "ingest_commit", "arguments": {
                    "session_id": token,
                    "agent": "impersonator",
                    "message": sha,
                    "sha": sha,
                    "changed_files": [path],
                    "timestamp": 100
                }}
            });
            handle(&engine, &sessions, &ingest).unwrap();
        }

        let evidence = |id, token: &str| {
            let request = json!({
                "jsonrpc": "2.0", "id": id, "method": "tools/call",
                "params": { "name": "evidence_for", "arguments": {
                    "session_id": token, "started_at": 90, "ended_at": 110
                }}
            });
            let response = handle(&engine, &sessions, &request).unwrap();
            serde_json::from_str::<Value>(
                response["result"]["content"][0]["text"].as_str().unwrap(),
            )
            .unwrap()
        };
        let first = evidence(30, "00112233445566778899aabbccddeeff");
        let second = evidence(31, "ffeeddccbbaa99887766554433221100");
        assert_ne!(first["agent_id"], second["agent_id"]);
        assert_ne!(first["agent_id"], "impersonator");
        assert!(first["agent_id"]
            .as_str()
            .unwrap()
            .starts_with("session:v1:test:"));
        assert_eq!(first["commit_ids"], json!(["intent:session-a"]));
        assert_eq!(second["commit_ids"], json!(["intent:session-b"]));
        assert_eq!(first["changed_node_ids"], json!(["artifact:src/a.rs"]));
        assert_eq!(second["changed_node_ids"], json!(["artifact:src/b.rs"]));
    }
}
