// Generated by AI (UnitTest MCP)
use ackplane_protocol::v1::{node_frame, Hello, NodeFrame};
use prost::Message;

#[test]
fn hello_frame_round_trips_through_the_v1_wire_contract() {
    let frame = NodeFrame {
        frame: Some(node_frame::Frame::Hello(Hello {
            tenant_id: "tenant-a".into(),
            repository_id: "repository-a".into(),
            producer_id: "node-a".into(),
            last_accepted_position: 42,
            capabilities: vec!["receipts.v1".into()],
        })),
    };

    let encoded = frame.encode_to_vec();
    let decoded = NodeFrame::decode(encoded.as_slice()).unwrap();

    assert_eq!(decoded, frame);
}
