// Generated by AI (UnitTest MCP)
//! Offset-preserving masking for source text that regex extractors inspect.

/// Mask comments and literals for the non-JavaScript languages handled by the
/// AST extractor. Unsupported extensions keep their original source.
pub(crate) fn mask_non_code(extension: &str, content: &str) -> String {
    match extension {
        "rs" => mask_c_like_non_code(content, true),
        "cs" | "go" | "java" | "kt" => mask_c_like_non_code(content, false),
        "py" => mask_python_non_code(content),
        _ => content.to_string(),
    }
}

/// Blank comments and literals while preserving every byte offset and newline.
fn mask_c_like_non_code(content: &str, rust: bool) -> String {
    let bytes = content.as_bytes();
    let mut masked = bytes.to_vec();
    let mut index = 0usize;
    while index < bytes.len() {
        if bytes[index..].starts_with(b"/*") {
            let end = nested_block_comment_end(bytes, index);
            mask_range(&mut masked, index, end);
            index = end;
            continue;
        }
        if bytes[index..].starts_with(b"//") {
            let start = index;
            while index < bytes.len() && bytes[index] != b'\n' {
                index += 1;
            }
            mask_range(&mut masked, start, index);
            continue;
        }
        if let Some(end) = rust_raw_string_end(bytes, index) {
            mask_range(&mut masked, index, end);
            index = end;
            continue;
        }
        if bytes[index..].starts_with(b"@\"") {
            let end = quoted_end(bytes, index + 1, b'"', 1, true);
            mask_range(&mut masked, index, end);
            index = end;
            continue;
        }
        if rust && bytes[index] == b'\'' {
            if let Some(end) = rust_char_literal_end(content, index) {
                mask_range(&mut masked, index, end);
                index = end;
            } else {
                // A lifetime (`'a`, `'static`) is code, not a character
                // literal. Leave it visible to definition and brace scans.
                index += 1;
            }
            continue;
        }
        if matches!(bytes[index], b'\'' | b'"' | b'`') {
            let delimiter_len = if bytes[index] != b'`'
                && bytes.get(index + 1) == Some(&bytes[index])
                && bytes.get(index + 2) == Some(&bytes[index])
            {
                3
            } else {
                1
            };
            let end = quoted_end(bytes, index, bytes[index], delimiter_len, false);
            mask_range(&mut masked, index, end);
            index = end;
            continue;
        }
        index += 1;
    }
    String::from_utf8(masked).expect("masking preserves UTF-8")
}

fn rust_char_literal_end(content: &str, start: usize) -> Option<usize> {
    let bytes = content.as_bytes();
    let value_start = start + 1;
    if bytes.get(value_start) == Some(&b'\\') {
        let end = quoted_end(bytes, start, b'\'', 1, false);
        return (bytes.get(end.checked_sub(1)?) == Some(&b'\'')).then_some(end);
    }
    let character = content.get(value_start..)?.chars().next()?;
    let close = value_start + character.len_utf8();
    (bytes.get(close) == Some(&b'\'')).then_some(close + 1)
}

/// Blank Python comments and single/triple-quoted strings.
fn mask_python_non_code(content: &str) -> String {
    let bytes = content.as_bytes();
    let mut masked = bytes.to_vec();
    let mut index = 0usize;
    while index < bytes.len() {
        if bytes[index] == b'#' {
            let start = index;
            while index < bytes.len() && bytes[index] != b'\n' {
                index += 1;
            }
            mask_range(&mut masked, start, index);
            continue;
        }
        if matches!(bytes[index], b'\'' | b'"') {
            let delimiter_len = if bytes.get(index + 1) == Some(&bytes[index])
                && bytes.get(index + 2) == Some(&bytes[index])
            {
                3
            } else {
                1
            };
            let end = quoted_end(bytes, index, bytes[index], delimiter_len, false);
            mask_range(&mut masked, index, end);
            index = end;
            continue;
        }
        index += 1;
    }
    String::from_utf8(masked).expect("masking preserves UTF-8")
}

fn nested_block_comment_end(bytes: &[u8], start: usize) -> usize {
    let mut index = start + 2;
    let mut depth = 1usize;
    while index < bytes.len() && depth > 0 {
        if bytes[index..].starts_with(b"/*") {
            depth += 1;
            index += 2;
        } else if bytes[index..].starts_with(b"*/") {
            depth -= 1;
            index += 2;
        } else {
            index += 1;
        }
    }
    index.min(bytes.len())
}

fn rust_raw_string_end(bytes: &[u8], start: usize) -> Option<usize> {
    let mut prefix = start;
    if matches!(bytes.get(prefix), Some(b'b' | b'c')) {
        prefix += 1;
    }
    if bytes.get(prefix) != Some(&b'r') {
        return None;
    }
    let mut opening_quote = prefix + 1;
    while bytes.get(opening_quote) == Some(&b'#') {
        opening_quote += 1;
    }
    if bytes.get(opening_quote) != Some(&b'"') {
        return None;
    }
    let hashes = opening_quote - prefix - 1;
    let mut index = opening_quote + 1;
    while index < bytes.len() {
        if bytes[index] == b'"'
            && bytes
                .get(index + 1..index + 1 + hashes)
                .is_some_and(|suffix| suffix.iter().all(|byte| *byte == b'#'))
        {
            return Some(index + 1 + hashes);
        }
        index += 1;
    }
    Some(bytes.len())
}

fn quoted_end(
    bytes: &[u8],
    start: usize,
    quote: u8,
    delimiter_len: usize,
    doubled_quote_escape: bool,
) -> usize {
    let mut index = start + delimiter_len;
    while index < bytes.len() {
        if doubled_quote_escape
            && bytes.get(index) == Some(&quote)
            && bytes.get(index + 1) == Some(&quote)
        {
            index += 2;
            continue;
        }
        if !doubled_quote_escape && bytes[index] == b'\\' {
            index = (index + 2).min(bytes.len());
            continue;
        }
        if bytes
            .get(index..index + delimiter_len)
            .is_some_and(|delimiter| delimiter.iter().all(|byte| *byte == quote))
        {
            return index + delimiter_len;
        }
        index += 1;
    }
    bytes.len()
}

fn mask_range(bytes: &mut [u8], start: usize, end: usize) {
    for byte in &mut bytes[start..end] {
        if *byte != b'\n' {
            *byte = b' ';
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_lifetimes_remain_code_while_character_literals_are_masked() {
        // The regression: treating `'a` as an opening quote hid everything up
        // to the next apostrophe, dropping otherwise valid Rust definitions.
        let source = "fn borrow<'a>(value: &'a str) -> &'a str { let close = '}'; value }\n";
        let masked = mask_non_code("rs", source);

        assert_eq!(masked.len(), source.len());
        assert!(masked.contains("borrow<'a>"));
        assert_eq!(masked.matches("&'a").count(), 2);
        assert!(!masked.contains("'}'"));
    }

    #[test]
    fn rust_masking_preserves_offsets_through_nested_comments_and_raw_strings() {
        let source =
            "fn café() { /* outer /* nested } */ */ let text = r#\"ghost() }\"#; real(); }\n";
        let masked = mask_non_code("rs", source);

        assert_eq!(masked.len(), source.len());
        assert_eq!(
            masked
                .match_indices('\n')
                .map(|(index, _)| index)
                .collect::<Vec<_>>(),
            source
                .match_indices('\n')
                .map(|(index, _)| index)
                .collect::<Vec<_>>()
        );
        assert!(masked.contains("fn café()"));
        assert!(masked.contains("real()"));
        assert!(!masked.contains("ghost()"));
        assert!(!masked.contains("nested"));
    }

    #[test]
    fn python_masking_hides_hash_comments_and_triple_quoted_strings() {
        let source = "def caller():\n    '''ghost()'''\n    # ghost()\n    real()\n";
        let masked = mask_non_code("py", source);

        assert_eq!(masked.len(), source.len());
        assert_eq!(masked.lines().count(), source.lines().count());
        assert!(!masked.contains("ghost()"));
        assert!(masked.contains("real()"));
    }
}
