// Generated by AI (UnitTest MCP)
//! Environment-driven configuration for the idle maintenance scheduler.

use std::time::Duration;

const DEFAULT_IDLE_SECS: u64 = 300;
const DEFAULT_MIN_INTERVAL_SECS: u64 = 3_600;
const DEFAULT_MAX_NODES: usize = 20;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct MaintenanceConfig {
    /// Model-dependent maintenance (signal consolidation + embedding index).
    /// Off by default: it spends local-model tokens.
    pub enabled: bool,
    /// Deterministic, zero-token graph hygiene (prune decayed edges + reap
    /// orphaned nodes, ADR-0021). On by default: it costs nothing and keeps the
    /// graph from growing unbounded between manual `prune_graph` calls.
    pub prune_enabled: bool,
    pub idle: Duration,
    pub min_interval: Duration,
    pub max_nodes: usize,
}

impl MaintenanceConfig {
    pub(crate) fn from_environment() -> Self {
        Self::resolve(|name| std::env::var(name).ok())
    }

    pub(super) fn resolve<F>(environment: F) -> Self
    where
        F: Fn(&str) -> Option<String>,
    {
        let enabled = environment("MINDLEAK_AUTONOMOUS_CONSOLIDATION")
            .map(|value| value.trim().eq_ignore_ascii_case("true"))
            .unwrap_or(false);
        // Deterministic prune is safe (zero-token) so it defaults ON; set
        // MINDLEAK_AUTONOMOUS_PRUNE=false to opt out.
        let prune_enabled = environment("MINDLEAK_AUTONOMOUS_PRUNE")
            .map(|value| !value.trim().eq_ignore_ascii_case("false"))
            .unwrap_or(true);
        Self {
            enabled,
            prune_enabled,
            idle: Duration::from_secs(bounded_u64(
                &environment,
                "MINDLEAK_CONSOLIDATE_IDLE_SECS",
                DEFAULT_IDLE_SECS,
                30,
                86_400,
            )),
            min_interval: Duration::from_secs(bounded_u64(
                &environment,
                "MINDLEAK_CONSOLIDATE_MIN_INTERVAL_SECS",
                DEFAULT_MIN_INTERVAL_SECS,
                60,
                86_400,
            )),
            max_nodes: bounded_usize(
                &environment,
                "MINDLEAK_CONSOLIDATE_MAX_NODES",
                DEFAULT_MAX_NODES,
                1,
                200,
            ),
        }
    }
}

fn bounded_u64<F>(environment: &F, name: &str, default: u64, minimum: u64, maximum: u64) -> u64
where
    F: Fn(&str) -> Option<String>,
{
    let Some(raw) = environment(name) else {
        return default;
    };
    match raw.trim().parse::<u64>() {
        Ok(0) | Err(_) => default,
        Ok(value) => value.clamp(minimum, maximum),
    }
}

fn bounded_usize<F>(
    environment: &F,
    name: &str,
    default: usize,
    minimum: usize,
    maximum: usize,
) -> usize
where
    F: Fn(&str) -> Option<String>,
{
    let Some(raw) = environment(name) else {
        return default;
    };
    match raw.trim().parse::<usize>() {
        Ok(0) | Err(_) => default,
        Ok(value) => value.clamp(minimum, maximum),
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use super::*;

    #[test]
    fn configuration_is_off_by_default_and_bounded_when_enabled() {
        let disabled = MaintenanceConfig::resolve(|_| None);
        assert!(!disabled.enabled);
        // Zero-token prune defaults ON so the graph self-cleans.
        assert!(disabled.prune_enabled);
        assert_eq!(disabled.idle, Duration::from_secs(DEFAULT_IDLE_SECS));

        let values = HashMap::from([
            ("MINDLEAK_AUTONOMOUS_CONSOLIDATION", "TRUE".to_string()),
            ("MINDLEAK_CONSOLIDATE_IDLE_SECS", "1".to_string()),
            (
                "MINDLEAK_CONSOLIDATE_MIN_INTERVAL_SECS",
                "999999".to_string(),
            ),
            ("MINDLEAK_CONSOLIDATE_MAX_NODES", "500".to_string()),
        ]);
        let enabled = MaintenanceConfig::resolve(|name| values.get(name).cloned());

        assert!(enabled.enabled);
        assert!(enabled.prune_enabled);
        assert_eq!(enabled.idle, Duration::from_secs(30));
        assert_eq!(enabled.min_interval, Duration::from_secs(86_400));
        assert_eq!(enabled.max_nodes, 200);
    }

    #[test]
    fn prune_can_be_opted_out_and_consolidation_stays_independent() {
        let no_prune = MaintenanceConfig::resolve(|name| {
            (name == "MINDLEAK_AUTONOMOUS_PRUNE").then(|| "false".to_string())
        });
        assert!(!no_prune.prune_enabled);
        assert!(!no_prune.enabled);
    }

    #[test]
    fn invalid_numeric_configuration_falls_back_to_defaults() {
        let values = HashMap::from([
            ("MINDLEAK_CONSOLIDATE_IDLE_SECS", "soon".to_string()),
            ("MINDLEAK_CONSOLIDATE_MAX_NODES", "0".to_string()),
        ]);
        let config = MaintenanceConfig::resolve(|name| values.get(name).cloned());

        assert_eq!(config.idle, Duration::from_secs(DEFAULT_IDLE_SECS));
        assert_eq!(config.max_nodes, DEFAULT_MAX_NODES);
    }
}
