// Generated by AI (UnitTest MCP)
//! The idle maintenance runtime: activity signalling and the consolidation worker.

use std::sync::mpsc::{self, Receiver, RecvTimeoutError};
use std::sync::{Arc, Condvar, Mutex};
use std::thread::JoinHandle;
use std::time::{Duration, Instant};

use mindleak_core::config::DecayPolicy;
use mindleak_core::{MindLeak, MindLeakError};
use serde_json::json;

use super::config::MaintenanceConfig;

const SHUTDOWN_GRACE: Duration = Duration::from_secs(2);
#[cfg(test)]
const WORKER_TEST_TIMEOUT: Duration = Duration::from_secs(30);

#[cfg(test)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum WorkerEvent {
    WaitingForIdle,
    Pruned,
    Consolidated,
}

#[derive(Clone)]
pub(crate) struct ActivitySignal {
    shared: Arc<(Mutex<ActivityState>, Condvar)>,
}

struct ActivityState {
    last_request: Instant,
    active_requests: usize,
    shutdown: bool,
    #[cfg(test)]
    worker_events: Vec<WorkerEvent>,
}

impl ActivitySignal {
    pub(crate) fn new() -> Self {
        Self {
            shared: Arc::new((
                Mutex::new(ActivityState {
                    last_request: Instant::now(),
                    active_requests: 0,
                    shutdown: false,
                    #[cfg(test)]
                    worker_events: Vec::new(),
                }),
                Condvar::new(),
            )),
        }
    }

    pub(crate) fn begin_request(&self) -> RequestActivity {
        let (state, condition) = &*self.shared;
        let mut state = state.lock().unwrap_or_else(|error| error.into_inner());
        state.active_requests = state.active_requests.saturating_add(1);
        state.last_request = Instant::now();
        condition.notify_all();
        RequestActivity {
            activity: self.clone(),
        }
    }

    pub(crate) fn shutdown(&self) {
        let (state, condition) = &*self.shared;
        let mut state = state.lock().unwrap_or_else(|error| error.into_inner());
        state.shutdown = true;
        condition.notify_all();
    }

    fn is_shutdown(&self) -> bool {
        self.shared
            .0
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .shutdown
    }

    #[cfg(test)]
    fn record_worker_event(&self, event: WorkerEvent) {
        let (state, condition) = &*self.shared;
        let mut state = state.lock().unwrap_or_else(|error| error.into_inner());
        state.worker_events.push(event);
        condition.notify_all();
    }

    #[cfg(test)]
    fn wait_for_worker_event(&self, expected: WorkerEvent) {
        let deadline = Instant::now() + WORKER_TEST_TIMEOUT;
        let (state, condition) = &*self.shared;
        let mut state = state.lock().unwrap_or_else(|error| error.into_inner());
        loop {
            if let Some(index) = state
                .worker_events
                .iter()
                .position(|event| *event == expected)
            {
                state.worker_events.swap_remove(index);
                return;
            }
            let remaining = deadline.saturating_duration_since(Instant::now());
            assert!(!remaining.is_zero(), "worker did not report {expected:?}");
            let result = condition
                .wait_timeout(state, remaining)
                .unwrap_or_else(|error| error.into_inner());
            state = result.0;
            assert!(
                !result.1.timed_out() || state.worker_events.contains(&expected),
                "worker did not report {expected:?}"
            );
        }
    }
}

pub(crate) struct RequestActivity {
    activity: ActivitySignal,
}

impl Drop for RequestActivity {
    fn drop(&mut self) {
        let (state, condition) = &*self.activity.shared;
        let mut state = state.lock().unwrap_or_else(|error| error.into_inner());
        state.active_requests = state.active_requests.saturating_sub(1);
        state.last_request = Instant::now();
        condition.notify_all();
    }
}

pub(crate) struct MaintenanceRuntime {
    activity: ActivitySignal,
    worker: Option<(JoinHandle<()>, Receiver<()>)>,
}

impl MaintenanceRuntime {
    pub(crate) fn disabled() -> Self {
        Self {
            activity: ActivitySignal::new(),
            worker: None,
        }
    }

    pub(crate) fn start(
        config: MaintenanceConfig,
        database_path: String,
        decay_policy: DecayPolicy,
        working_set_size: usize,
    ) -> anyhow::Result<Self> {
        if !config.enabled && !config.prune_enabled && !config.index_enabled {
            return Ok(Self::disabled());
        }
        if is_unsupported_maintenance_database(&database_path) {
            return Err(anyhow::anyhow!(
                "autonomous maintenance requires a file-backed MINDLEAK_DB"
            ));
        }
        // Open before spawning so an invalid path fails startup synchronously.
        let engine = MindLeak::open(&database_path)?
            .with_decay_policy(decay_policy)
            .with_working_set_size(working_set_size)
            .with_consolidation_min_interval(config.min_interval.as_secs());
        let activity = ActivitySignal::new();
        let worker_activity = activity.clone();
        let (completed_tx, completed_rx) = mpsc::channel();
        let worker = std::thread::Builder::new()
            .name("mindleak-consolidation".to_string())
            .spawn(move || {
                run_worker(engine, worker_activity, config);
                let _ = completed_tx.send(());
            })?;
        Ok(Self {
            activity,
            worker: Some((worker, completed_rx)),
        })
    }

    pub(crate) fn activity(&self) -> ActivitySignal {
        self.activity.clone()
    }

    pub(crate) fn shutdown(self) {
        self.activity.shutdown();
        if let Some((worker, completed)) = self.worker {
            match completed.recv_timeout(SHUTDOWN_GRACE) {
                Ok(()) | Err(RecvTimeoutError::Disconnected) => {
                    let _ = worker.join();
                }
                Err(RecvTimeoutError::Timeout) => {
                    tracing::warn!(
                        "autonomous consolidation did not stop within shutdown grace; process exit will terminate it"
                    );
                }
            }
        }
    }
}

fn is_unsupported_maintenance_database(path: &str) -> bool {
    let normalized = path.trim().to_ascii_lowercase();
    normalized == ":memory:" || normalized.starts_with("file:")
}

fn run_worker(engine: MindLeak, activity: ActivitySignal, config: MaintenanceConfig) {
    // Cadence trackers are worker-local. The deterministic prune runs on a fixed
    // wall-clock interval that ignores request activity (it is a cheap, zero-token
    // SQL sweep), so heavy UI polling can never starve it. Consolidation stays
    // gated on genuine request idle plus a rate-limiting interval because it is
    // expensive and spends local-model tokens.
    let mut last_prune: Option<Instant> = None;
    let mut last_index: Option<Instant> = None;
    let mut last_consolidation: Option<Instant> = None;
    // Cap each sleep so the loop re-evaluates periodically even when the next
    // deadline is far off or a tier is disabled. Shutdown wakes the worker
    // immediately via the condvar, so this does not affect shutdown latency.
    const MAX_WAIT: Duration = Duration::from_secs(30);

    loop {
        let (state, condition) = &*activity.shared;
        let mut state = state.lock().unwrap_or_else(|error| error.into_inner());
        if state.shutdown {
            break;
        }
        let now = Instant::now();

        // Prune is due once its interval has elapsed since the last run (or it has
        // never run). Independent of active_requests and the idle window.
        let prune_wait = if config.prune_enabled {
            match last_prune {
                Some(last) => config
                    .prune_interval
                    .saturating_sub(now.saturating_duration_since(last)),
                None => Duration::ZERO,
            }
        } else {
            MAX_WAIT
        };

        // The index pass shares the prune's activity-independent cadence rather
        // than the consolidation idle gate. Recall answers from whatever the
        // index last covered, so letting request traffic defer it is what makes
        // the answers quietly stale instead of merely absent.
        let index_wait = if config.index_enabled {
            match last_index {
                Some(last) => config
                    .index_interval
                    .saturating_sub(now.saturating_duration_since(last)),
                None => Duration::ZERO,
            }
        } else {
            MAX_WAIT
        };

        // Consolidation waits for the process to be genuinely idle (no active
        // request for `idle`) and is rate-limited by `min_interval`.
        let consolidation_wait = if config.enabled && state.active_requests == 0 {
            let idle_remaining = config
                .idle
                .saturating_sub(now.saturating_duration_since(state.last_request));
            let interval_remaining = last_consolidation
                .map(|last| {
                    config
                        .min_interval
                        .saturating_sub(now.saturating_duration_since(last))
                })
                .unwrap_or(Duration::ZERO);
            idle_remaining.max(interval_remaining)
        } else {
            MAX_WAIT
        };

        let wait = prune_wait
            .min(index_wait)
            .min(consolidation_wait)
            .min(MAX_WAIT);
        if !wait.is_zero() {
            #[cfg(test)]
            if config.enabled && state.active_requests > 0 {
                state.worker_events.push(WorkerEvent::WaitingForIdle);
                condition.notify_all();
            }
            let result = condition
                .wait_timeout(state, wait)
                .unwrap_or_else(|error| error.into_inner());
            state = result.0;
            if state.shutdown {
                break;
            }
            continue;
        }

        let prune_due = config.prune_enabled && prune_wait.is_zero();
        let index_due = config.index_enabled && index_wait.is_zero();
        let consolidate_due =
            config.enabled && state.active_requests == 0 && consolidation_wait.is_zero();
        drop(state);

        if prune_due {
            run_prune(&engine);
            last_prune = Some(Instant::now());
            #[cfg(test)]
            activity.record_worker_event(WorkerEvent::Pruned);
        }
        if index_due && !activity.is_shutdown() {
            run_index(&engine, config.index_batch);
            last_index = Some(Instant::now());
        }
        if consolidate_due && !activity.is_shutdown() {
            run_consolidation(
                &engine,
                config.max_nodes,
                config.min_interval.as_secs(),
                &activity,
            );
            last_consolidation = Some(Instant::now());
            #[cfg(test)]
            activity.record_worker_event(WorkerEvent::Consolidated);
        }
    }
}

/// Reap decayed edges and the nodes they orphaned (ADR-0021). Deterministic and
/// zero-token, so it runs every idle pass regardless of model availability — the
/// self-cleaning that keeps the graph from growing unbounded between manual
/// `prune_graph` calls.
fn run_prune(engine: &MindLeak) {
    let started = Instant::now();
    match engine.prune() {
        Ok(outcome) => {
            engine.record_maintenance(
                "autonomous_prune",
                "ok",
                started.elapsed().as_millis() as i64,
                Some(json!({
                    "edges_removed": outcome.edges_removed,
                    "nodes_removed": outcome.nodes_removed,
                    "signal_candidates": outcome.signal_candidates.len(),
                })),
            );
            if outcome.edges_removed > 0 || outcome.nodes_removed > 0 {
                tracing::info!(
                    edges = outcome.edges_removed,
                    nodes = outcome.nodes_removed,
                    "autonomous prune reaped decayed graph"
                );
            }
        }
        Err(error) => {
            engine.record_maintenance(
                "autonomous_prune",
                "error",
                started.elapsed().as_millis() as i64,
                Some(json!({ "category": error_category(&error) })),
            );
            tracing::warn!(%error, "autonomous prune failed");
        }
    }
}

/// Embed nodes that have no current vector (ADR-0008), so `recall` answers from
/// the graph as it is rather than as it was at the last manual `index`.
///
/// Bounded per pass: a large backlog is worked off over several passes instead
/// of one long stall on a local model. An unreachable embedding server is
/// recorded and otherwise ignored -- recall already errors cleanly without one,
/// and failing the whole maintenance loop over an optional feature would take
/// the zero-token prune down with it.
fn run_index(engine: &MindLeak, batch: usize) {
    let started = Instant::now();
    match engine.index_nodes(batch) {
        Ok(indexed) => {
            engine.record_maintenance(
                "autonomous_index",
                "ok",
                started.elapsed().as_millis() as i64,
                Some(json!({ "indexed": indexed })),
            );
            if indexed > 0 {
                tracing::info!(nodes = indexed, "autonomous index embedded new nodes");
            }
        }
        Err(error) => {
            engine.record_maintenance(
                "autonomous_index",
                "error",
                started.elapsed().as_millis() as i64,
                Some(index_error_detail(&error)),
            );
            tracing::debug!(%error, "autonomous index skipped; no embedding server");
        }
    }
}

fn run_consolidation(
    engine: &MindLeak,
    max_nodes: usize,
    min_interval_secs: u64,
    activity: &ActivitySignal,
) {
    let started = Instant::now();
    match engine
        .consolidate_signal_with_control(max_nodes, min_interval_secs, || activity.is_shutdown())
    {
        Ok(outcome) => {
            engine.record_maintenance(
                "autonomous_consolidation",
                "ok",
                started.elapsed().as_millis() as i64,
                Some(json!({
                    "candidates_consolidated": outcome.candidates_consolidated,
                    "edges_removed": outcome.edges_removed,
                    "nodes_removed": outcome.nodes_removed,
                })),
            );
            tracing::info!(
                candidates = outcome.candidates_consolidated,
                "autonomous consolidation completed"
            );
        }
        Err(MindLeakError::NotFound(_)) => {
            engine.record_maintenance(
                "autonomous_consolidation",
                "skipped",
                started.elapsed().as_millis() as i64,
                Some(json!({ "reason": "no_candidates" })),
            );
        }
        Err(MindLeakError::Busy(_)) => {
            engine.record_maintenance(
                "autonomous_consolidation",
                "skipped",
                started.elapsed().as_millis() as i64,
                Some(json!({ "reason": "lease_busy_or_rate_limited" })),
            );
        }
        Err(MindLeakError::Cancelled(_)) => {
            engine.record_maintenance(
                "autonomous_consolidation",
                "skipped",
                started.elapsed().as_millis() as i64,
                Some(json!({ "reason": "shutdown" })),
            );
        }
        Err(error) => {
            engine.record_maintenance(
                "autonomous_consolidation",
                "error",
                started.elapsed().as_millis() as i64,
                Some(json!({ "category": error_category(&error) })),
            );
            tracing::warn!(%error, "autonomous consolidation failed");
        }
    }

    // Best-effort embedding index refresh so semantic recall (ADR-0008)
    // self-populates as new nodes accrue, instead of requiring a manual `index`.
    // Off the deterministic hot path; a failure (e.g. the embed model is not
    // reachable) is recorded and never crashes the worker or blocks consolidation.
    if activity.is_shutdown() {
        return;
    }
    let index_started = Instant::now();
    match engine.index_nodes(max_nodes) {
        Ok(0) => {}
        Ok(indexed) => {
            engine.record_maintenance(
                "autonomous_index",
                "ok",
                index_started.elapsed().as_millis() as i64,
                Some(json!({ "indexed": indexed })),
            );
            tracing::info!(indexed, "autonomous embedding index refreshed");
        }
        Err(error) => {
            engine.record_maintenance(
                "autonomous_index",
                "error",
                index_started.elapsed().as_millis() as i64,
                Some(index_error_detail(&error)),
            );
        }
    }
}

fn index_error_detail(error: &MindLeakError) -> serde_json::Value {
    json!({
        "category": error_category(error),
        "error": error.to_string(),
        "fallback": "deterministic_graph",
    })
}

fn error_category(error: &MindLeakError) -> &'static str {
    match error {
        MindLeakError::Sqlite(_) => "sqlite",
        MindLeakError::Json(_) => "json",
        MindLeakError::Io(_) => "io",
        MindLeakError::Http(_) => "http",
        MindLeakError::Model(failure) => failure.reason.as_str(),
        MindLeakError::NotFound(_) => "not_found",
        MindLeakError::InvalidArgument(_) => "invalid_argument",
        MindLeakError::Busy(_) => "busy",
        MindLeakError::Cancelled(_) => "cancelled",
        MindLeakError::Other(_) => "other",
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU64, Ordering};

    use mindleak_core::{Result as MindLeakResult, TextEmbedder};
    use mindleak_model::{failure, ModelFailureReason};

    use super::*;

    static TEMPORARY_DATABASE_SEQUENCE: AtomicU64 = AtomicU64::new(0);

    struct UnavailableIndexEmbedder;

    impl TextEmbedder for UnavailableIndexEmbedder {
        fn model(&self) -> &str {
            "nomic-embed-text"
        }

        fn embed(&self, _text: &str) -> MindLeakResult<Vec<f32>> {
            Err(failure(
                ModelFailureReason::Unreachable,
                false,
                "semantic recall is unavailable; install and start Ollama, then run `ollama pull nomic-embed-text`",
            )
            .into())
        }
    }

    #[test]
    fn shutdown_marks_state_and_wakes_waiters() {
        let activity = ActivitySignal::new();
        activity.shutdown();
        assert!(activity.shared.0.lock().unwrap().shutdown);
    }

    #[test]
    fn request_guard_tracks_activity_until_completion() {
        let activity = ActivitySignal::new();
        let guard = activity.begin_request();
        assert_eq!(activity.shared.0.lock().unwrap().active_requests, 1);
        drop(guard);
        assert_eq!(activity.shared.0.lock().unwrap().active_requests, 0);
    }

    #[test]
    fn disabled_runtime_has_no_worker_and_shuts_down() {
        MaintenanceRuntime::disabled().shutdown();
    }

    #[test]
    fn fully_disabled_start_does_not_open_the_database() {
        // With both maintenance tiers off, start short-circuits before opening
        // the DB, so even an unopenable path is accepted.
        let config = MaintenanceConfig {
            enabled: false,
            prune_enabled: false,
            index_enabled: false,
            index_interval: Duration::from_secs(3600),
            index_batch: 128,
            prune_interval: Duration::from_secs(3600),
            idle: Duration::from_secs(30),
            min_interval: Duration::from_secs(60),
            max_nodes: 20,
        };
        let runtime = MaintenanceRuntime::start(
            config,
            "invalid\0database".to_string(),
            DecayPolicy::default(),
            7,
        )
        .unwrap();
        runtime.shutdown();
    }

    #[test]
    fn enabled_start_rejects_isolated_in_memory_database() {
        let config = MaintenanceConfig {
            enabled: true,
            prune_enabled: false,
            index_enabled: false,
            index_interval: Duration::from_secs(3600),
            index_batch: 128,
            prune_interval: Duration::from_secs(3600),
            idle: Duration::from_secs(30),
            min_interval: Duration::from_secs(60),
            max_nodes: 20,
        };
        let error = match MaintenanceRuntime::start(
            config,
            ":memory:".to_string(),
            DecayPolicy::default(),
            7,
        ) {
            Ok(runtime) => {
                runtime.shutdown();
                panic!("in-memory autonomous maintenance should be rejected");
            }
            Err(error) => error,
        };
        assert!(error.to_string().contains("file-backed"));
    }

    #[test]
    fn detects_sqlite_in_memory_uri_forms() {
        for path in [
            ":memory:",
            "file::memory:?cache=shared",
            "file:review?mode=memory",
            "FILE:review?cache=shared&MODE=MEMORY",
            "file:review?%6dode=memory",
            "file:review?mode=memory#fragment",
            "file:workspace.db?mode=rwc",
        ] {
            assert!(is_unsupported_maintenance_database(path), "{path}");
        }
        assert!(!is_unsupported_maintenance_database(
            "workspace/.mindleak/graph.db"
        ));
    }

    #[test]
    fn no_candidate_pass_records_skipped_maintenance_telemetry() {
        let engine = MindLeak::open_in_memory().unwrap();

        let activity = ActivitySignal::new();
        run_consolidation(&engine, 20, 60, &activity);

        let snapshot = engine.telemetry_snapshot(1).unwrap();
        assert_eq!(snapshot.recent[0].kind, "maintenance");
        assert_eq!(snapshot.recent[0].name, "autonomous_consolidation");
        assert_eq!(snapshot.recent[0].outcome, "skipped");
    }

    #[test]
    fn prune_pass_reaps_and_records_telemetry_without_a_model() {
        // Deterministic prune runs with no model configured and records its own
        // telemetry — the self-cleaning that keeps the graph bounded.
        let engine = MindLeak::open_in_memory().unwrap();
        run_prune(&engine);
        let snapshot = engine.telemetry_snapshot(5).unwrap();
        assert!(snapshot
            .recent
            .iter()
            .any(|event| event.kind == "maintenance" && event.name == "autonomous_prune"));
        // Prune-only mode must not emit consolidation telemetry.
        assert!(!snapshot
            .recent
            .iter()
            .any(|event| event.name == "autonomous_consolidation"));
    }

    #[test]
    fn unavailable_index_records_actionable_deterministic_fallback_telemetry() {
        let engine = MindLeak::open_in_memory()
            .unwrap()
            .with_embedder(Box::new(UnavailableIndexEmbedder));
        engine
            .ingest_file("src/auth.rs", "fn authentication_handler() {}")
            .unwrap();

        run_index(&engine, 128);

        let snapshot = engine.telemetry_snapshot(1).unwrap();
        let event = &snapshot.recent[0];
        assert_eq!(event.kind, "maintenance");
        assert_eq!(event.name, "autonomous_index");
        assert_eq!(event.outcome, "error");
        let detail = event.detail.as_ref().unwrap();
        assert_eq!(detail["category"], "unreachable");
        assert_eq!(detail["fallback"], "deterministic_graph");
        assert!(detail["error"]
            .as_str()
            .unwrap()
            .contains("ollama pull nomic-embed-text"));
    }

    #[test]
    fn enabled_worker_runs_after_idle_and_joins_cleanly() {
        let path = temporary_database("idle");
        let runtime = MaintenanceRuntime::start(
            MaintenanceConfig {
                enabled: true,
                prune_enabled: false,
                index_enabled: false,
                index_interval: Duration::from_secs(3600),
                index_batch: 128,
                prune_interval: Duration::from_secs(3600),
                idle: Duration::from_millis(10),
                min_interval: Duration::from_secs(60),
                max_nodes: 20,
            },
            path.to_string_lossy().into_owned(),
            DecayPolicy::default(),
            7,
        )
        .unwrap();
        let inspector = MindLeak::open(path.to_str().unwrap()).unwrap();
        runtime
            .activity
            .wait_for_worker_event(WorkerEvent::Consolidated);
        assert!(inspector.telemetry_snapshot(1).unwrap().total_events > 0);

        runtime.shutdown();
        drop(inspector);
        cleanup_database(&path);
    }

    #[test]
    fn active_request_blocks_idle_pass_until_completion() {
        let path = temporary_database("active-request");
        let engine = MindLeak::open(path.to_str().unwrap()).unwrap();
        let inspector = MindLeak::open(path.to_str().unwrap()).unwrap();
        let activity = ActivitySignal::new();
        let request = activity.begin_request();
        let worker_activity = activity.clone();
        let worker = std::thread::spawn(move || {
            run_worker(
                engine,
                worker_activity,
                MaintenanceConfig {
                    enabled: true,
                    prune_enabled: false,
                    index_enabled: false,
                    index_interval: Duration::from_secs(3600),
                    index_batch: 128,
                    prune_interval: Duration::from_secs(3600),
                    idle: Duration::from_millis(10),
                    min_interval: Duration::from_secs(60),
                    max_nodes: 20,
                },
            );
        });
        activity.wait_for_worker_event(WorkerEvent::WaitingForIdle);
        assert_eq!(inspector.telemetry_snapshot(1).unwrap().total_events, 0);

        drop(request);
        activity.wait_for_worker_event(WorkerEvent::Consolidated);
        assert!(inspector.telemetry_snapshot(1).unwrap().total_events > 0);

        activity.shutdown();
        worker.join().unwrap();
        drop(inspector);
        cleanup_database(&path);
    }

    #[test]
    fn prune_runs_on_its_cadence_despite_continuous_request_activity() {
        // Regression (the "pruning never works" report): the deterministic prune
        // must fire on its own wall-clock cadence even while requests keep the
        // process non-idle. Before the fix, prune shared consolidation's idle
        // gate, so an extension polling every few seconds meant the idle window
        // was never reached and the autonomous prune never ran. Here the idle
        // window is an hour and requests arrive continuously, yet prune still
        // fires because its cadence is independent of request activity.
        let path = temporary_database("prune-cadence");
        let engine = MindLeak::open(path.to_str().unwrap()).unwrap();
        let inspector = MindLeak::open(path.to_str().unwrap()).unwrap();
        let activity = ActivitySignal::new();
        let request = activity.begin_request();
        let worker_activity = activity.clone();
        let worker = std::thread::spawn(move || {
            run_worker(
                engine,
                worker_activity,
                MaintenanceConfig {
                    enabled: false,
                    prune_enabled: true,
                    index_enabled: false,
                    index_interval: Duration::from_secs(3600),
                    index_batch: 128,
                    prune_interval: Duration::from_millis(10),
                    idle: Duration::from_secs(3600),
                    min_interval: Duration::from_secs(3600),
                    max_nodes: 20,
                },
            );
        });

        activity.wait_for_worker_event(WorkerEvent::Pruned);
        let pruned = inspector
            .telemetry_snapshot(5)
            .unwrap()
            .recent
            .iter()
            .any(|event| event.kind == "maintenance" && event.name == "autonomous_prune");

        drop(request);
        activity.shutdown();
        worker.join().unwrap();
        drop(inspector);
        cleanup_database(&path);
        assert!(
            pruned,
            "autonomous prune never ran despite its cadence elapsing under load"
        );
    }

    #[test]
    fn temporary_databases_are_unique_and_cleanup_sqlite_sidecars() {
        let first = temporary_database("isolation");
        let second = temporary_database("isolation");
        assert_ne!(first, second);

        fs::write(&first, "database").unwrap();
        fs::write(format!("{}-wal", first.display()), "wal").unwrap();
        fs::write(format!("{}-shm", first.display()), "shm").unwrap();

        cleanup_database(&first);

        assert!(!first.exists());
        assert!(!PathBuf::from(format!("{}-wal", first.display())).exists());
        assert!(!PathBuf::from(format!("{}-shm", first.display())).exists());
        cleanup_database(&second);
    }

    fn temporary_database(name: &str) -> PathBuf {
        let sequence = TEMPORARY_DATABASE_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "mindleak-maintenance-{name}-{}-{sequence}.db",
            std::process::id(),
        ));
        cleanup_database(&path);
        path
    }

    fn cleanup_database(path: &PathBuf) {
        let _ = fs::remove_file(path);
        let _ = fs::remove_file(format!("{}-wal", path.display()));
        let _ = fs::remove_file(format!("{}-shm", path.display()));
    }
}
