// Generated by AI (UnitTest MCP)
use super::{opt_i64, req_str, text_result};
use mindleak_core::{MindLeak, MindLeakError};
use serde_json::{json, Value};

const DETERMINISTIC_FALLBACK_DEPTH: u32 = 2;
const DETERMINISTIC_FALLBACK_MIN_WEIGHT: f64 = 0.2;

fn embedding_unavailable(error: &MindLeakError) -> bool {
    matches!(error, MindLeakError::Model(_) | MindLeakError::Http(_))
}

fn deterministic_recall_fallback(
    engine: &MindLeak,
    query: &str,
    error: &MindLeakError,
) -> Result<Value, String> {
    let graph = engine
        .multi_hop_query(
            query,
            DETERMINISTIC_FALLBACK_DEPTH,
            DETERMINISTIC_FALLBACK_MIN_WEIGHT,
        )
        .map_err(|fallback_error| fallback_error.to_string())?;
    let results = graph.nodes.clone();
    Ok(text_result(&json!({
        "results": results,
        "fallback": {
            "mode": "deterministic_graph",
            "semantic_recall": "unavailable",
            "reason": error.to_string(),
            "advice": "Semantic recall needs an OpenAI-compatible /v1/embeddings endpoint. To use the default, install and start Ollama, then run `ollama pull nomic-embed-text`. Otherwise set MINDLEAK_EMBED_URL, MINDLEAK_EMBED_MODEL, and MINDLEAK_EMBED_API_KEY. Deterministic graph/FTS results are returned instead.",
            "seed": graph.seed,
            "edges": graph.edges,
        }
    })))
}

pub(super) fn definitions() -> Vec<Value> {
    vec![
        json!({
            "name": "recall",
            "description": "Call for questions about why, prior decisions, regressions, or resumed work. Return meaning-nearest nodes from the optional embedding index. If the endpoint is unavailable, return an actionable Ollama/configuration remedy plus deterministic graph/FTS traversal seeded by the same task text.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "query": { "type": "string" },
                    "limit": { "type": "integer", "default": 10, "minimum": 1, "maximum": 100 }
                },
                "required": ["query"]
            }
        }),
        json!({
            "name": "index",
            "description": "Populate the semantic embedding index for nodes lacking a current vector (off the zero-token hot path). Returns how many nodes were indexed. Optional; requires a local embedding model.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "limit": { "type": "integer", "default": 200, "minimum": 1, "maximum": 5000 }
                }
            }
        }),
    ]
}

pub(super) fn dispatch(
    engine: &MindLeak,
    name: &str,
    args: &Value,
) -> Option<Result<Value, String>> {
    match name {
        "recall" => Some((|| {
            let query = req_str(args, "query")?;
            let limit = opt_i64(args, "limit", 10).clamp(1, 100) as usize;
            match engine.recall(&query, limit) {
                Ok(results) => Ok(text_result(&json!({ "results": results }))),
                Err(error) if embedding_unavailable(&error) => {
                    deterministic_recall_fallback(engine, &query, &error)
                }
                Err(error) => Err(error.to_string()),
            }
        })()),
        "index" => Some((|| {
            let limit = opt_i64(args, "limit", 200).clamp(1, 5000) as usize;
            let indexed = engine.index_nodes(limit).map_err(|e| e.to_string())?;
            Ok(text_result(&json!({ "indexed": indexed })))
        })()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use mindleak_core::{Result as MindLeakResult, TextEmbedder};
    use mindleak_model::{failure, ModelFailureReason};

    use crate::tools::call;

    use super::*;

    struct UnavailableEmbedder;

    impl TextEmbedder for UnavailableEmbedder {
        fn model(&self) -> &str {
            "nomic-embed-text"
        }

        fn embed(&self, _text: &str) -> MindLeakResult<Vec<f32>> {
            Err(failure(ModelFailureReason::Unreachable, false, "connection refused").into())
        }
    }

    struct KeywordEmbedder;

    impl TextEmbedder for KeywordEmbedder {
        fn model(&self) -> &str {
            "keyword"
        }

        fn embed(&self, text: &str) -> MindLeakResult<Vec<f32>> {
            if text.to_ascii_lowercase().contains("authentication") {
                Ok(vec![1.0, 0.0])
            } else {
                Ok(vec![0.0, 1.0])
            }
        }
    }

    struct InvalidEmbedder;

    impl TextEmbedder for InvalidEmbedder {
        fn model(&self) -> &str {
            "invalid"
        }

        fn embed(&self, _text: &str) -> MindLeakResult<Vec<f32>> {
            Err(MindLeakError::InvalidArgument(
                "invalid recall request".to_string(),
            ))
        }
    }

    fn payload(result: Value) -> Value {
        serde_json::from_str(result["content"][0]["text"].as_str().unwrap()).unwrap()
    }

    #[test]
    fn recall_returns_actionable_deterministic_fallback_when_embeddings_are_unavailable() {
        let engine = MindLeak::open_in_memory()
            .unwrap()
            .with_embedder(Box::new(UnavailableEmbedder));
        engine
            .ingest_file(
                "src/auth.rs",
                "fn authentication_fallback() { validate_session(); }",
            )
            .unwrap();

        let response = call(
            &engine,
            &json!({
                "name": "recall",
                "arguments": { "query": "authentication fallback", "limit": 5 }
            }),
        )
        .unwrap();
        let body = payload(response);

        assert_eq!(body["fallback"]["mode"], "deterministic_graph");
        assert_eq!(body["fallback"]["semantic_recall"], "unavailable");
        assert!(body["fallback"]["reason"]
            .as_str()
            .unwrap()
            .contains("unreachable"));
        let advice = body["fallback"]["advice"].as_str().unwrap();
        assert!(advice.contains("install and start Ollama"));
        assert!(advice.contains("ollama pull nomic-embed-text"));
        assert!(advice.contains("MINDLEAK_EMBED_URL"));
        assert!(body["results"]
            .as_array()
            .unwrap()
            .iter()
            .any(|node| node["id"] == "symbol:src/auth.rs:authentication_fallback"));
        assert!(body["fallback"]["seed"]
            .as_array()
            .unwrap()
            .iter()
            .any(|seed| seed == "symbol:src/auth.rs:authentication_fallback"));
    }

    #[test]
    fn recall_keeps_the_semantic_response_shape_when_embeddings_are_available() {
        let engine = MindLeak::open_in_memory()
            .unwrap()
            .with_embedder(Box::new(KeywordEmbedder));
        engine
            .ingest_file(
                "src/auth.rs",
                "fn authentication_handler() { validate_session(); }",
            )
            .unwrap();
        engine.index_nodes(50).unwrap();

        let response = call(
            &engine,
            &json!({
                "name": "recall",
                "arguments": { "query": "authentication", "limit": 5 }
            }),
        )
        .unwrap();
        let body = payload(response);

        assert_eq!(body.as_object().unwrap().len(), 1);
        assert!(body["results"]
            .as_array()
            .unwrap()
            .iter()
            .any(|hit| hit["id"] == "symbol:src/auth.rs:authentication_handler"));
    }

    #[test]
    fn recall_does_not_hide_non_model_failures_behind_the_fallback() {
        let engine = MindLeak::open_in_memory()
            .unwrap()
            .with_embedder(Box::new(InvalidEmbedder));

        let error = call(
            &engine,
            &json!({ "name": "recall", "arguments": { "query": "anything" } }),
        )
        .unwrap_err();

        assert_eq!(error, "invalid argument: invalid recall request");
    }
}
