// Generated by AI (UnitTest MCP)
use super::{opt_f64, opt_i64, opt_str, req_str, str_array, text_result};
use mindleak_core::MindLeak;
use serde_json::{json, Value};

pub(super) fn definitions() -> Vec<Value> {
    vec![
        json!({
            "name": "graph_multi_hop_query",
            "description": "Navigate the context graph up to N directional hops from a seed node id or search phrase, keeping only edges above a minimum time-decayed weight. Returns connected nodes, paths, and recent state.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "seed_entity": { "type": "string", "description": "Node id (e.g. 'artifact:src/auth.ts') or a free-text search phrase." },
                    "max_depth": { "type": "integer", "default": 2, "minimum": 1, "maximum": 6 },
                    "min_weight": { "type": "number", "default": 0.2, "minimum": 0.0, "maximum": 1.0 }
                },
                "required": ["seed_entity"]
            }
        }),
        json!({
            "name": "get_impact_radius",
            "description": "Determine what is structurally connected to a file or symbol you are about to edit: dependent symbols, previously failing executions, and related intents.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "target_artifact": { "type": "string", "description": "Node id or path of the file/symbol to assess." }
                },
                "required": ["target_artifact"]
            }
        }),
        json!({
            "name": "check_overlap",
            "description": "Read-only decay-aware pre-flight footprint for other agents on requested workspace paths or MindLeak symbol ids (ADR-0024). Advisory only; combine with Lodestar's check_overlap claim result.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "paths": { "type": "array", "items": { "type": "string" }, "default": [] },
                    "symbols": { "type": "array", "items": { "type": "string" }, "default": [] }
                }
            }
        }),
    ]
}

pub(super) fn dispatch(
    engine: &MindLeak,
    name: &str,
    args: &Value,
) -> Option<Result<Value, String>> {
    match name {
        "graph_multi_hop_query" => Some((|| {
            let seed = req_str(args, "seed_entity")?;
            let depth = opt_i64(args, "max_depth", 2).clamp(1, 6) as u32;
            let min_weight = opt_f64(args, "min_weight", 0.2);
            let sub = engine
                .multi_hop_query(&seed, depth, min_weight)
                .map_err(|e| e.to_string())?;
            Ok(text_result(&json!(sub)))
        })()),
        "get_impact_radius" => Some((|| {
            let target = req_str(args, "target_artifact")?;
            let sub = engine.impact_radius(&target).map_err(|e| e.to_string())?;
            Ok(text_result(&json!(sub)))
        })()),
        "check_overlap" => Some((|| {
            let overlaps = engine
                .check_overlap(
                    &str_array(args, "paths"),
                    &str_array(args, "symbols"),
                    opt_str(args, "exclude_agent").as_deref(),
                )
                .map_err(|e| e.to_string())?;
            Ok(text_result(&json!({ "footprints": overlaps })))
        })()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn overlap_tool_is_advertised_as_read_only_and_advisory() {
        let tool = definitions()
            .into_iter()
            .find(|tool| tool["name"] == "check_overlap")
            .unwrap();
        assert!(tool["description"].as_str().unwrap().contains("Read-only"));
        assert!(tool["description"].as_str().unwrap().contains("Advisory"));
        assert!(tool["inputSchema"]["properties"]["paths"].is_object());
        assert!(tool["inputSchema"]["properties"]["symbols"].is_object());
    }
}
