// Generated by AI (UnitTest MCP)
use crate::{
    Advice, AdviceDisposition, CodeBindingMode, GoalStatus, GoverningClause, Lodestar,
    LodestarError, Result,
};

impl Lodestar {
    /// Forward-looking, evidence-free, state-free constitutional advice (ADR-0029):
    /// given the nodes an agent is *about to* change (and an optional covering
    /// task), return the active clauses that govern that scope plus one
    /// proportional disposition — *before* any work is done.
    ///
    /// Unlike [`Lodestar::check_conformance`] it takes no evidence bundle, records
    /// no conformance verdict, and changes no task state. It is deterministic: the
    /// semantic judge is never invoked (there is no work to judge yet), so it can
    /// only surface what governs the change, warn about a would-be drift, block on
    /// a hard `forbid_change` lock, or defer to a human when no constitution is
    /// adopted. Advice never gates the compare-and-swap claim; it informs.
    pub fn advise(&self, task_id: Option<&str>, node_ids: &[String]) -> Result<Advice> {
        let task = match task_id {
            Some(id) => Some(
                self.store
                    .get_task(id)?
                    .ok_or_else(|| LodestarError::NotFound(id.to_string()))?,
            ),
            None => None,
        };

        // Fail-open: with no adopted constitution there is no policy to advise
        // against, so defer to a human rather than fake a clear verdict or
        // pre-emptively block the change (ADR-0026 §4, ADR-0029).
        if self.store.goals_by_status(GoalStatus::Active)?.is_empty() {
            return Ok(Advice {
                disposition: AdviceDisposition::NeedsHuman,
                governing: Vec::new(),
                findings: vec![
                    "constitution absent: no active policy to advise against".to_string()
                ],
            });
        }

        let task_goal_id = task.as_ref().map(|t| t.goal_id.as_str());
        let resolved = self.resolve_governing_clauses(node_ids, task_goal_id)?;

        // Surface every clause governing the declared scope, forbids first.
        let mut governing = Vec::new();
        for (node, goal) in &resolved.forbid {
            governing.push(GoverningClause {
                node_id: node.clone(),
                goal: goal.clone(),
                mode: CodeBindingMode::ForbidChange,
            });
        }
        for (node, goal) in resolved.in_scope.iter().chain(resolved.other.iter()) {
            governing.push(GoverningClause {
                node_id: node.clone(),
                goal: goal.clone(),
                mode: CodeBindingMode::Governed,
            });
        }

        let mut findings = Vec::new();
        let disposition = if !resolved.forbid.is_empty() {
            for (node, goal) in &resolved.forbid {
                findings.push(format!(
                    "{} forbids changes to {node}; a change needs a waiver, not a commit",
                    goal.id
                ));
            }
            AdviceDisposition::Block
        } else if !resolved.other.is_empty() {
            let goals = distinct_goal_ids(resolved.other.iter());
            findings.push(format!(
                "this change is governed by {} but no covering task claims it — it would drift; \
                 get a covering task or review before acting",
                goals.join(", ")
            ));
            AdviceDisposition::Review
        } else if !resolved.in_scope.is_empty() {
            let goals = distinct_goal_ids(resolved.in_scope.iter());
            findings.push(format!(
                "in scope of your task goal {}; honour the clause statements above as you work",
                goals.join(", ")
            ));
            AdviceDisposition::Advise
        } else {
            findings.push("no active clause governs this change; proceed".to_string());
            AdviceDisposition::Advise
        };

        Ok(Advice {
            disposition,
            governing,
            findings,
        })
    }
}

fn distinct_goal_ids<'a>(pairs: impl Iterator<Item = &'a (String, crate::Goal)>) -> Vec<String> {
    let mut ids: Vec<String> = pairs.map(|(_, goal)| goal.id.clone()).collect();
    ids.sort();
    ids.dedup();
    ids
}

#[cfg(test)]
mod tests {
    use crate::facade::test_support::engine;
    use crate::{AdviceDisposition, CodeBindingMode, GoalKind};

    #[test]
    fn absent_constitution_defers_to_a_human_never_blocks() {
        // Fail-open: an empty constitution yields needs_human, not a pre-emptive
        // block and not a false "all clear".
        let engine = engine();
        let advice = engine
            .advise(None, &["artifact:src/anything.rs".to_string()])
            .unwrap();
        assert_eq!(advice.disposition, AdviceDisposition::NeedsHuman);
        assert!(advice.governing.is_empty());
        assert!(advice.findings[0].contains("constitution absent"));
    }

    #[test]
    fn unbound_change_is_clear_when_a_constitution_exists() {
        let engine = engine();
        engine
            .define_goal(GoalKind::Constraint, "Some rule", "Hold the line.", None)
            .unwrap();
        // The rule governs no node, so an unrelated change is clear to proceed.
        let advice = engine
            .advise(None, &["artifact:src/unrelated.rs".to_string()])
            .unwrap();
        assert_eq!(advice.disposition, AdviceDisposition::Advise);
        assert!(advice.governing.is_empty());
    }

    #[test]
    fn a_forbid_change_lock_blocks_and_only_a_specific_active_clause_can() {
        let engine = engine();
        let goal = engine
            .define_goal(
                GoalKind::Invariant,
                "Frozen schema",
                "The schema file must not change.",
                None,
            )
            .unwrap();
        let node = "artifact:crates/core/src/schema.sql".to_string();
        engine
            .link_goal_to_code(
                &goal.id,
                std::slice::from_ref(&node),
                CodeBindingMode::ForbidChange,
            )
            .unwrap();

        let advice = engine.advise(None, std::slice::from_ref(&node)).unwrap();
        assert_eq!(advice.disposition, AdviceDisposition::Block);
        assert_eq!(advice.governing.len(), 1);
        assert_eq!(advice.governing[0].mode, CodeBindingMode::ForbidChange);
        assert!(advice.findings[0].contains("forbids changes"));

        // A different, unrelated node under no clause is not blocked.
        let clear = engine
            .advise(None, &["artifact:crates/core/src/other.rs".to_string()])
            .unwrap();
        assert_eq!(clear.disposition, AdviceDisposition::Advise);
    }

    #[test]
    fn governed_by_another_goal_without_a_covering_task_advises_review() {
        let engine = engine();
        let goal = engine
            .define_goal(
                GoalKind::Constraint,
                "Payments boundary",
                "Payment code stays isolated.",
                None,
            )
            .unwrap();
        let node = "artifact:crates/pay/src/lib.rs".to_string();
        engine
            .link_goal_to_code(
                &goal.id,
                std::slice::from_ref(&node),
                CodeBindingMode::Governed,
            )
            .unwrap();

        // No task claims this goal, so touching its code would drift -> review.
        let advice = engine.advise(None, &[node]).unwrap();
        assert_eq!(advice.disposition, AdviceDisposition::Review);
        assert!(advice.findings[0].contains("would drift"));
    }

    #[test]
    fn in_scope_of_the_task_goal_advises_and_surfaces_the_clause() {
        let engine = engine();
        let goal = engine
            .define_goal(
                GoalKind::Constraint,
                "Graph module boundary",
                "Graph access flows through GraphStore.",
                None,
            )
            .unwrap();
        let node = "artifact:crates/core/src/graph.rs".to_string();
        engine
            .link_goal_to_code(
                &goal.id,
                std::slice::from_ref(&node),
                CodeBindingMode::Governed,
            )
            .unwrap();
        let task = engine
            .create_task(&goal.id, "Extend GraphStore", "add a method")
            .unwrap();

        let advice = engine.advise(Some(&task.id), &[node]).unwrap();
        assert_eq!(advice.disposition, AdviceDisposition::Advise);
        assert_eq!(advice.governing.len(), 1);
        assert_eq!(advice.governing[0].goal.id, goal.id);
    }

    #[test]
    fn advise_records_no_conformance_row_and_no_task_state_change() {
        let engine = engine();
        let goal = engine
            .define_goal(GoalKind::Constraint, "Rule", "Keep it tidy.", None)
            .unwrap();
        let node = "artifact:crates/core/src/thing.rs".to_string();
        engine
            .link_goal_to_code(
                &goal.id,
                std::slice::from_ref(&node),
                CodeBindingMode::Governed,
            )
            .unwrap();
        let task = engine.create_task(&goal.id, "Work", "do it").unwrap();

        engine.advise(Some(&task.id), &[node]).unwrap();

        // Advising is a read: it must not persist a conformance record...
        assert!(engine.conformance_history(&task.id).unwrap().is_empty());
        // ...nor move the task out of its `open` lifecycle state.
        let after = engine.store().get_task(&task.id).unwrap().unwrap();
        assert_eq!(after.status, crate::TaskStatus::Open);
    }
}
