// Generated by AI (UnitTest MCP)
use crate::store::ConformanceAudit;
use crate::{
    now_unix, CodeBindingMode, ConformanceEvidence, ConformanceResult, Lodestar, LodestarError,
    Result, Task, TaskStatus, Verdict,
};

const MAX_EVIDENCE_EVENTS: usize = 200;
const MAX_EVIDENCE_PROVENANCE: usize = 1_000;
const MAX_EVIDENCE_SUMMARY_BYTES: usize = 4_096;

impl Lodestar {
    /// Complete a task only when claim-bounded evidence conforms (ADR-0009).
    pub fn complete_task(
        &self,
        id: &str,
        agent: &str,
        evidence: &ConformanceEvidence,
    ) -> Result<(bool, ConformanceResult)> {
        let now = now_unix();
        let agent = self.resolve_agent(agent)?;
        let task = self
            .store
            .get_task(id)?
            .ok_or_else(|| LodestarError::NotFound(id.to_string()))?;
        self.validate_claim_evidence(&task, agent, evidence, now)?;
        let conformance = self.evaluate_conformance(evidence, Some(&task))?;
        let target_status = match conformance.verdict {
            Verdict::Aligned => TaskStatus::Done,
            Verdict::Violation => TaskStatus::Blocked,
            Verdict::Drift | Verdict::NeedsHuman => TaskStatus::InReview,
        };
        let serialized = serde_json::to_string(evidence)?;
        let findings = conformance.findings.join("; ");
        if !self.store.record_conformance_and_transition(
            id,
            agent,
            ConformanceAudit {
                evidence_schema_version: evidence.schema_version,
                evidence: &serialized,
                verdict: conformance.verdict,
                findings: &findings,
            },
            target_status,
            now,
        )? {
            return Err(LodestarError::Invalid(format!(
                "task {id} claim changed before conformance could be recorded"
            )));
        }
        Ok((conformance.verdict == Verdict::Aligned, conformance))
    }

    /// Check evidence without changing task state; uses the completion evaluator.
    pub fn check_conformance(
        &self,
        evidence: &ConformanceEvidence,
        task_id: Option<&str>,
    ) -> Result<ConformanceResult> {
        let resolved_task_id = match (task_id, evidence.task_id.as_deref()) {
            (Some(left), Some(right)) if left != right => {
                return Err(LodestarError::Invalid(
                    "evidence task_id does not match requested task".to_string(),
                ));
            }
            (Some(id), _) | (_, Some(id)) => Some(id),
            (None, None) => None,
        };
        let task = match resolved_task_id {
            Some(id) => Some(
                self.store
                    .get_task(id)?
                    .ok_or_else(|| LodestarError::NotFound(id.to_string()))?,
            ),
            None => None,
        };
        if let Some(task) = task.as_ref() {
            let agent = self.resolve_agent(&evidence.agent_id)?;
            self.validate_claim_evidence(task, agent, evidence, now_unix())?;
        } else {
            self.validate_evidence_shape(evidence)?;
        }
        let conformance = self.evaluate_conformance(evidence, task.as_ref())?;
        let serialized = serde_json::to_string(evidence)?;
        let findings = conformance.findings.join("; ");
        self.store.record_conformance(
            resolved_task_id,
            ConformanceAudit {
                evidence_schema_version: evidence.schema_version,
                evidence: &serialized,
                verdict: conformance.verdict,
                findings: &findings,
            },
            now_unix(),
        )?;
        Ok(conformance)
    }

    fn evaluate_conformance(
        &self,
        evidence: &ConformanceEvidence,
        task: Option<&Task>,
    ) -> Result<ConformanceResult> {
        let mut findings = Vec::new();
        if evidence.changed_node_ids.is_empty() || evidence.provenance.is_empty() {
            findings.push("evidence contains no provenance-bearing mutation".to_string());
            return Ok(ConformanceResult {
                verdict: Verdict::NeedsHuman,
                findings,
            });
        }

        let mut touched_task_goal = false;
        let mut wrong_goals = Vec::new();
        for node in &evidence.changed_node_ids {
            for binding in self.store.active_bindings_for_node(node)? {
                if binding.mode == CodeBindingMode::ForbidChange {
                    findings.push(format!("{} forbids changes to {node}", binding.goal.id));
                    return Ok(ConformanceResult {
                        verdict: Verdict::Violation,
                        findings,
                    });
                }
                match task {
                    Some(task) if binding.goal.id == task.goal_id => touched_task_goal = true,
                    Some(_) => wrong_goals.push(binding.goal.id),
                    None => wrong_goals.push(binding.goal.id),
                }
            }
        }

        if !wrong_goals.is_empty() {
            wrong_goals.sort();
            wrong_goals.dedup();
            findings.push(format!(
                "governed code changed without a covering task: {}",
                wrong_goals.join(", ")
            ));
            return Ok(ConformanceResult {
                verdict: Verdict::Drift,
                findings,
            });
        }

        let Some(task) = task else {
            findings.push("no governed code touched".to_string());
            return Ok(ConformanceResult {
                verdict: Verdict::Aligned,
                findings,
            });
        };
        if !touched_task_goal {
            findings.push("evidence does not touch code bound to the task goal".to_string());
            return Ok(ConformanceResult {
                verdict: Verdict::NeedsHuman,
                findings,
            });
        }

        let goal = self
            .store
            .get_goal(&task.goal_id)?
            .ok_or_else(|| LodestarError::NotFound(task.goal_id.clone()))?;
        if goal.kind.is_normative() {
            match self.llm.judge(&goal.statement, &evidence.summary) {
                Ok((verdict, rationale)) if verdict == "aligned" => {
                    findings.push(format!("semantic check aligned: {rationale}"));
                }
                Ok((verdict, rationale)) if verdict == "violation" => {
                    findings.push(format!("semantic check found a violation: {rationale}"));
                    return Ok(ConformanceResult {
                        verdict: Verdict::Violation,
                        findings,
                    });
                }
                Ok((_, rationale)) => {
                    findings.push(format!("semantic check needs human review: {rationale}"));
                    return Ok(ConformanceResult {
                        verdict: Verdict::NeedsHuman,
                        findings,
                    });
                }
                Err(_) => {
                    findings.push("semantic check unavailable".to_string());
                    return Ok(ConformanceResult {
                        verdict: Verdict::NeedsHuman,
                        findings,
                    });
                }
            }
        }

        findings.push(format!("evidence covers task goal {}", task.goal_id));
        Ok(ConformanceResult {
            verdict: Verdict::Aligned,
            findings,
        })
    }

    fn validate_evidence_shape(&self, evidence: &ConformanceEvidence) -> Result<()> {
        if evidence.schema_version != 1 {
            return Err(LodestarError::Invalid(format!(
                "unsupported evidence schema version {}",
                evidence.schema_version
            )));
        }
        if evidence.started_at > evidence.ended_at {
            return Err(LodestarError::Invalid(
                "evidence start must not be after its end".to_string(),
            ));
        }
        if evidence.agent_id.trim().is_empty() {
            return Err(LodestarError::Invalid(
                "evidence agent must not be empty".to_string(),
            ));
        }
        if evidence.execution_ids.len() > MAX_EVIDENCE_EVENTS
            || evidence.commit_ids.len() > MAX_EVIDENCE_EVENTS
            || evidence.provenance.len() > MAX_EVIDENCE_PROVENANCE
            || evidence.summary.len() > MAX_EVIDENCE_SUMMARY_BYTES
        {
            return Err(LodestarError::Invalid(
                "evidence exceeds the bounded ADR-0009 contract".to_string(),
            ));
        }
        if !evidence
            .successful_execution_ids
            .iter()
            .all(|id| evidence.execution_ids.contains(id))
        {
            return Err(LodestarError::Invalid(
                "successful executions must be included in execution_ids".to_string(),
            ));
        }
        let agent_node_id = format!("agent:{}", evidence.agent_id);
        for event_id in evidence
            .execution_ids
            .iter()
            .chain(evidence.commit_ids.iter())
        {
            if !evidence.provenance.iter().any(|fact| {
                fact.source_id == agent_node_id
                    && fact.target_id == *event_id
                    && fact.relation == "observed"
            }) {
                return Err(LodestarError::Invalid(format!(
                    "event {event_id} lacks agent observation provenance"
                )));
            }
        }
        for changed_id in &evidence.changed_node_ids {
            if !evidence.provenance.iter().any(|fact| {
                fact.target_id == *changed_id
                    && matches!(fact.relation.as_str(), "modified" | "refactored")
                    && (evidence.execution_ids.contains(&fact.source_id)
                        || evidence.commit_ids.contains(&fact.source_id))
            }) {
                return Err(LodestarError::Invalid(format!(
                    "changed node {changed_id} lacks mutation provenance"
                )));
            }
        }
        for failed_id in &evidence.failed_node_ids {
            if !evidence.provenance.iter().any(|fact| {
                fact.target_id == *failed_id
                    && fact.relation == "failed_on"
                    && evidence.execution_ids.contains(&fact.source_id)
            }) {
                return Err(LodestarError::Invalid(format!(
                    "failed node {failed_id} lacks failure provenance"
                )));
            }
        }
        Ok(())
    }

    fn validate_claim_evidence(
        &self,
        task: &Task,
        agent: &str,
        evidence: &ConformanceEvidence,
        now: i64,
    ) -> Result<()> {
        self.validate_evidence_shape(evidence)?;
        if evidence.task_id.as_deref() != Some(task.id.as_str()) {
            return Err(LodestarError::Invalid(
                "evidence task_id does not identify the claimed task".to_string(),
            ));
        }
        if evidence.agent_id != agent || task.owner.as_deref() != Some(agent) {
            return Err(LodestarError::Invalid(
                "evidence agent does not own the task".to_string(),
            ));
        }
        let lease_expired = match task.lease_expires_at {
            Some(end) => end < now,
            None => true,
        };
        if task.status != TaskStatus::Claimed || lease_expired {
            return Err(LodestarError::Invalid(
                "task does not have a live claim".to_string(),
            ));
        }
        let claim_started_at = task.claim_started_at.ok_or_else(|| {
            LodestarError::Invalid("task claim has no evidence-window start".to_string())
        })?;
        if evidence.started_at < claim_started_at
            || evidence.ended_at > now
            || evidence.ended_at > task.lease_expires_at.unwrap_or(evidence.ended_at)
        {
            return Err(LodestarError::Invalid(
                "evidence interval falls outside the live claim".to_string(),
            ));
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::facade::test_support::engine;
    use crate::{EvidenceProvenance, GoalKind};

    #[test]
    fn conformance_flags_ungoverned_as_aligned_and_governed_as_drift() {
        let e = engine();
        let g = e
            .define_goal(
                GoalKind::Constraint,
                "Auth stays typed",
                "no stringly auth",
                None,
            )
            .unwrap();
        e.link_goal_to_code(
            &g.id,
            &["artifact:src/auth.rs".into()],
            CodeBindingMode::Governed,
        )
        .unwrap();

        let free_evidence = test_evidence(None, "agent-a", "artifact:src/unrelated.rs");
        let free = e.check_conformance(&free_evidence, None).unwrap();
        assert_eq!(free.verdict, Verdict::Aligned);

        let drift_evidence = test_evidence(None, "agent-a", "artifact:src/auth.rs");
        let drift = e.check_conformance(&drift_evidence, None).unwrap();
        assert_eq!(drift.verdict, Verdict::Drift);
    }

    #[test]
    fn covering_task_without_evidence_needs_human_review() {
        let e = engine();
        let g = e
            .define_goal(GoalKind::Objective, "Auth typed", "harden auth", None)
            .unwrap();
        e.link_goal_to_code(
            &g.id,
            &["artifact:src/auth.rs".into()],
            CodeBindingMode::Governed,
        )
        .unwrap();
        let t = e.create_task(&g.id, "harden auth", "").unwrap();
        e.claim_task(&t.id, "agent-a", 300).unwrap();
        let claimed = e.store.get_task(&t.id).unwrap().unwrap();
        let evidence = ConformanceEvidence {
            schema_version: 1,
            task_id: Some(t.id.clone()),
            agent_id: "agent-a".into(),
            started_at: claimed.claim_started_at.unwrap(),
            ended_at: now_unix(),
            changed_node_ids: Vec::new(),
            failed_node_ids: Vec::new(),
            execution_ids: Vec::new(),
            successful_execution_ids: Vec::new(),
            commit_ids: Vec::new(),
            summary: "no activity".into(),
            provenance: Vec::new(),
        };
        let res = e.check_conformance(&evidence, Some(&t.id)).unwrap();
        assert_eq!(res.verdict, Verdict::NeedsHuman);
    }

    fn test_evidence(
        task_id: Option<String>,
        agent: &str,
        changed_node_id: &str,
    ) -> ConformanceEvidence {
        ConformanceEvidence {
            schema_version: 1,
            task_id,
            agent_id: agent.into(),
            started_at: 1,
            ended_at: 2,
            changed_node_ids: vec![changed_node_id.into()],
            failed_node_ids: Vec::new(),
            execution_ids: vec!["execution:proof".into()],
            successful_execution_ids: vec!["execution:proof".into()],
            commit_ids: Vec::new(),
            summary: format!("changed {changed_node_id}"),
            provenance: vec![
                EvidenceProvenance {
                    source_id: format!("agent:{agent}"),
                    target_id: "execution:proof".into(),
                    relation: "observed".into(),
                },
                EvidenceProvenance {
                    source_id: "execution:proof".into(),
                    target_id: changed_node_id.into(),
                    relation: "modified".into(),
                },
            ],
        }
    }
}
