// Generated by AI (UnitTest MCP)
use crate::{
    common_core_pack, discovery::discover_project_facts, discovery::ProjectFact, now_unix,
    CodeBindingMode, ConstitutionPack, ConstitutionProposal, ConstitutionState, ConstitutionStatus,
    Goal, GoalKind, GoalStatus, Lodestar, LodestarError, PackClause, PackClauseDisposition,
    PackClauseProposal, PackClauseProvenance, PackProposalBatch, PackReviewOutcome, Result,
};

impl Lodestar {
    pub fn define_goal(
        &self,
        kind: GoalKind,
        title: &str,
        statement: &str,
        parent: Option<String>,
    ) -> Result<Goal> {
        self.store
            .define_goal(kind, title, statement, parent, now_unix())
    }

    pub fn supersede_goal(&self, old_id: &str, new_statement: &str, reason: &str) -> Result<Goal> {
        self.store
            .supersede_goal(old_id, new_statement, reason, now_unix())
    }

    /// The authoritative set an agent reads before acting.
    pub fn get_constitution(&self) -> Result<Vec<Goal>> {
        self.store.goals_by_status(GoalStatus::Active)
    }

    /// Report whether this project has an adopted constitution, a draft awaiting
    /// review, or none at all (SPEC-CONSTITUTION §11). Read-only and
    /// model-free: it never proposes, activates, or mutates anything. An active
    /// version wins over a draft, because only an activated version authorises
    /// verdicts — a project mid-bootstrap must not read as governed.
    pub fn constitution_status(&self) -> Result<ConstitutionStatus> {
        if let Some(version) = self.store.active_constitution_version()? {
            return Ok(ConstitutionStatus {
                state: ConstitutionState::Active,
                version: Some(version),
                clause_count: self.store.count_goals_by_status(GoalStatus::Active)?,
            });
        }
        if let Some(version) = self.store.draft_constitution_version()? {
            return Ok(ConstitutionStatus {
                state: ConstitutionState::Draft,
                version: Some(version),
                clause_count: self.store.count_goals_by_status(GoalStatus::Draft)?,
            });
        }
        Ok(ConstitutionStatus {
            state: ConstitutionState::Absent,
            version: None,
            clause_count: 0,
        })
    }

    /// Register one immutable policy-pack version. Re-registering the same
    /// digest is idempotent; the same id/version with different content is an
    /// error rather than a silent upstream rewrite.
    pub fn register_policy_pack(&self, pack: &ConstitutionPack) -> Result<ConstitutionPack> {
        self.store.register_policy_pack(pack, now_unix())
    }

    pub fn get_policy_pack(
        &self,
        pack_id: &str,
        version: &str,
    ) -> Result<Option<ConstitutionPack>> {
        self.store.get_policy_pack(pack_id, version)
    }

    /// Materialize durable review proposals for one pack. When no explicit
    /// draft/version is supplied, proposals target the current active
    /// constitution; an absent constitution leaves them draft-only.
    pub fn propose_policy_pack(
        &self,
        pack_id: &str,
        version: &str,
        constitution_version: Option<&str>,
    ) -> Result<PackProposalBatch> {
        let active;
        let context = match constitution_version {
            Some(version) => Some(version),
            None => {
                active = self.store.active_constitution_version()?;
                active.as_ref().map(|version| version.id.as_str())
            }
        };
        self.store
            .propose_policy_pack(pack_id, version, context, now_unix())
    }

    /// Register and propose the five Common Core principles through exactly the
    /// same immutable-pack path used by extension packs.
    pub fn propose_common_core(&self) -> Result<PackProposalBatch> {
        let pack = common_core_pack();
        self.register_policy_pack(&pack)?;
        self.propose_policy_pack(&pack.id, &pack.version, None)
    }

    /// Draft a constitution for an ungoverned project (SPEC-CONSTITUTION §7.3):
    /// discover cited facts from the supplied repository paths, record them as
    /// the draft's provenance, and propose the Common Core against that draft.
    ///
    /// Deterministic and model-free, and it **never activates**: the returned
    /// version is a `draft`, every Common Core clause is left undecided for a
    /// human, and every discovered fact is evidence rather than a clause. An
    /// already-active constitution is refused because changing adopted policy is
    /// an amendment, not a fresh proposal.
    pub fn propose_constitution(
        &self,
        paths: &[String],
        created_by: Option<&str>,
    ) -> Result<ConstitutionProposal> {
        if let Some(active) = self.store.active_constitution_version()? {
            return Err(LodestarError::Invalid(format!(
                "{} is already active; changing adopted policy is an amendment, not a fresh proposal",
                active.id
            )));
        }
        if let Some(draft) = self.store.draft_constitution_version()? {
            return Err(LodestarError::Invalid(format!(
                "{} is already drafted and awaiting review; resolve or activate it rather than drafting over it",
                draft.id
            )));
        }

        let now = now_unix();
        let number = self.store.next_constitution_version_number()?;
        let id = format!("constitution:v{number}");
        let version = self.store.create_constitution_version(
            &id,
            number,
            GoalStatus::Draft,
            created_by,
            now,
        )?;

        let facts = discover_project_facts(paths);
        self.store.record_project_facts(&id, &facts, now)?;

        let pack = common_core_pack();
        self.register_policy_pack(&pack)?;
        let common_core = self.propose_policy_pack(&pack.id, &pack.version, Some(&id))?;

        Ok(ConstitutionProposal {
            version,
            facts,
            common_core,
        })
    }

    /// The cited facts a drafted or active constitution was grounded in.
    pub fn constitution_facts(&self, constitution_version: &str) -> Result<Vec<ProjectFact>> {
        self.store.project_facts(constitution_version)
    }

    pub fn policy_pack_proposals(
        &self,
        pack_id: &str,
        version: &str,
        constitution_version: Option<&str>,
        include_decided: bool,
    ) -> Result<Vec<PackClauseProposal>> {
        let active;
        let context = match constitution_version {
            Some(version) => Some(version),
            None => {
                active = self.store.active_constitution_version()?;
                active.as_ref().map(|version| version.id.as_str())
            }
        };
        self.store
            .policy_pack_proposals(pack_id, version, context, include_decided)
    }

    pub fn review_pack_clause(
        &self,
        proposal_id: &str,
        disposition: PackClauseDisposition,
        tailored_clause: Option<&PackClause>,
        actor: &str,
        reason: Option<&str>,
    ) -> Result<PackReviewOutcome> {
        self.store.review_pack_clause(
            proposal_id,
            disposition,
            tailored_clause,
            actor,
            reason,
            now_unix(),
        )
    }

    pub fn pack_clause_provenance(&self, goal_id: &str) -> Result<Option<PackClauseProvenance>> {
        self.store.pack_clause_provenance(goal_id)
    }

    pub fn link_goal_to_code(
        &self,
        goal_id: &str,
        node_ids: &[String],
        mode: CodeBindingMode,
    ) -> Result<usize> {
        if !self.store.goal_exists(goal_id)? {
            return Err(LodestarError::NotFound(goal_id.to_string()));
        }
        let goal = self
            .store
            .get_goal(goal_id)?
            .ok_or_else(|| LodestarError::NotFound(goal_id.to_string()))?;
        if mode == CodeBindingMode::ForbidChange && !goal.kind.is_normative() {
            return Err(LodestarError::Invalid(
                "forbid_change is valid only for constraints and invariants".to_string(),
            ));
        }
        self.store.link_goal_to_code(goal_id, node_ids, mode)
    }

    /// Remove goal↔code bindings (ADR-0009 seam upkeep). The inverse of
    /// `link_goal_to_code`: prune a stale or mistaken binding — e.g. a shared doc
    /// or a source file that a goal no longer governs — so conformance stops
    /// flagging honest changes to it as drift against a goal it does not realise.
    /// A node not bound to the goal is a no-op. Returns how many bindings were
    /// removed.
    pub fn unlink_goal_from_code(&self, goal_id: &str, node_ids: &[String]) -> Result<usize> {
        if !self.store.goal_exists(goal_id)? {
            return Err(LodestarError::NotFound(goal_id.to_string()));
        }
        self.store.unlink_goal_from_code(goal_id, node_ids)
    }

    /// Audit which active goals govern a code node, and how (governed /
    /// forbid_change) — the read that makes binding hygiene inspectable before
    /// pruning with `unlink_goal_from_code`.
    pub fn governing_goals(&self, node_id: &str) -> Result<Vec<crate::CodeBinding>> {
        self.store.active_bindings_for_node(node_id)
    }

    /// Render the active constitution as committed-friendly markdown; optionally
    /// write it to `path`.
    pub fn export_constitution(&self, path: Option<&str>) -> Result<String> {
        let goals = self.get_constitution()?;
        let markdown = render_constitution(&goals);
        if let Some(p) = path {
            if let Some(parent) = std::path::Path::new(p).parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(p, &markdown)?;
        }
        Ok(markdown)
    }
}

/// A goal is realised by *code*, not by the shared prose many goals touch.
/// Documentation artifacts — markdown, and the root operational/meta files — are
/// therefore treated as never goal-governed **at conformance read time**: a
/// documentation node never drives a drift verdict, even when a binding to it
/// exists. This is derived, never enforced by mutating stored bindings — nothing
/// is deleted, so it can never clobber a legitimately-recorded binding.
pub(crate) fn is_documentation_node(node_id: &str) -> bool {
    let path = node_id.strip_prefix("artifact:").unwrap_or(node_id);
    let file = path.rsplit('/').next().unwrap_or(path);
    path.to_ascii_lowercase().ends_with(".md") || matches!(file, "LICENSE" | "CODEOWNERS")
}

/// Render the active constitution as committed-friendly markdown, grouped by
/// kind (invariants first — the hardest constraints lead).
fn render_constitution(goals: &[Goal]) -> String {
    let mut out = String::from("# Constitution\n\n");
    out.push_str("> Generated by Lodestar from the active Intent Plane. Do not edit by hand.\n\n");
    for (kind, heading) in [
        (GoalKind::Invariant, "## Invariants"),
        (GoalKind::Constraint, "## Constraints"),
        (GoalKind::Objective, "## Objectives"),
        (GoalKind::Principle, "## Principles"),
    ] {
        let group: Vec<&Goal> = goals.iter().filter(|g| g.kind == kind).collect();
        if group.is_empty() {
            continue;
        }
        out.push_str(heading);
        out.push_str("\n\n");
        for g in group {
            out.push_str(&format!("- **{}** (`{}`, v{})\n", g.title, g.id, g.version));
            out.push_str(&format!("  {}\n", g.statement));
        }
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::facade::test_support::engine;

    #[test]
    fn status_reports_absent_before_any_constitution_exists() {
        // Absent is a distinct answer from "governed and permitted": an agent
        // must be able to tell that no policy exists at all.
        let e = engine();
        let status = e.constitution_status().unwrap();
        assert_eq!(status.state, ConstitutionState::Absent);
        assert!(status.version.is_none());
        assert_eq!(status.clause_count, 0);
    }

    #[test]
    fn status_reports_a_draft_without_treating_it_as_governing() {
        let e = engine();
        e.store
            .create_constitution_version("constitution:draft", 1, GoalStatus::Draft, None, 1)
            .unwrap();
        let status = e.constitution_status().unwrap();
        assert_eq!(status.state, ConstitutionState::Draft);
        assert_eq!(status.version.unwrap().id, "constitution:draft");
    }

    #[test]
    fn an_ungoverned_project_reaches_a_cited_draft_without_activating() {
        // SPEC-CONSTITUTION §7.3 + task 3 acceptance: a fixture repository with
        // no constitution reaches a cited draft, every Common Core clause is
        // left undecided, and nothing activates itself.
        let e = engine();
        let paths = [
            "README.md".to_string(),
            "AGENTS.md".to_string(),
            ".github/workflows/ci.yml".to_string(),
            "CODEOWNERS".to_string(),
        ];
        let proposal = e.propose_constitution(&paths, Some("maintainer")).unwrap();

        assert_eq!(proposal.version.status, GoalStatus::Draft);
        assert_eq!(proposal.version.id, "constitution:v1");
        assert_eq!(proposal.facts.len(), 4);
        assert!(proposal.facts.iter().all(|f| !f.source_path.is_empty()));
        assert_eq!(proposal.common_core.proposals.len(), 5);
        assert!(proposal
            .common_core
            .proposals
            .iter()
            .all(|p| p.disposition.is_none()));

        // The draft governs nothing: status stays draft, not active.
        let status = e.constitution_status().unwrap();
        assert_eq!(status.state, ConstitutionState::Draft);
        // Facts are durable provenance, not a transient response.
        assert_eq!(e.constitution_facts(&proposal.version.id).unwrap().len(), 4);
    }

    #[test]
    fn proposing_over_an_active_constitution_is_refused_as_an_amendment() {
        let e = engine();
        e.store
            .create_constitution_version("constitution:v1", 1, GoalStatus::Active, None, 1)
            .unwrap();
        let error = e.propose_constitution(&[], None).unwrap_err().to_string();
        assert!(error.contains("amendment"), "{error}");
    }

    #[test]
    fn proposing_over_an_existing_draft_is_refused_rather_than_stacking_drafts() {
        let e = engine();
        e.propose_constitution(&["README.md".to_string()], None)
            .unwrap();
        let error = e
            .propose_constitution(&["README.md".to_string()], None)
            .unwrap_err()
            .to_string();
        assert!(error.contains("awaiting review"), "{error}");
    }

    #[test]
    fn an_active_version_wins_over_a_later_draft() {
        // A project mid-amendment is still governed by its activated version,
        // so the draft must not downgrade the reported state.
        let e = engine();
        e.store
            .create_constitution_version("constitution:v1", 1, GoalStatus::Active, None, 1)
            .unwrap();
        e.store
            .create_constitution_version("constitution:v2", 2, GoalStatus::Draft, None, 2)
            .unwrap();
        e.define_goal(
            GoalKind::Invariant,
            "Decay is the point",
            "Edges fade",
            None,
        )
        .unwrap();

        let status = e.constitution_status().unwrap();
        assert_eq!(status.state, ConstitutionState::Active);
        assert_eq!(status.version.unwrap().id, "constitution:v1");
        assert_eq!(status.clause_count, 1);
    }

    #[test]
    fn constitution_returns_only_active_goals() {
        let e = engine();
        let g = e
            .define_goal(
                GoalKind::Invariant,
                "Zero-token write path",
                "No LLM on ingest",
                None,
            )
            .unwrap();
        e.supersede_goal(&g.id, "No LLM tokens on the write path", "clarity")
            .unwrap();
        let active = e.get_constitution().unwrap();
        assert_eq!(active.len(), 1);
        assert_eq!(active[0].version, 2);
    }

    #[test]
    fn goals_govern_code_not_documentation() {
        for doc in [
            "artifact:CHANGELOG.md",
            "artifact:README.md",
            "artifact:docs/ARCHITECTURE.md",
            "artifact:LICENSE",
            "artifact:CODEOWNERS",
        ] {
            assert!(is_documentation_node(doc), "{doc} should be documentation");
        }
        for code in [
            "artifact:crates/lodestar-core/src/model.rs",
            "symbol:src/app.ts:handler",
            "artifact:src/app.rs",
        ] {
            assert!(!is_documentation_node(code), "{code} should be code");
        }
    }

    #[test]
    fn export_constitution_renders_grouped_markdown() {
        let e = engine();
        e.define_goal(
            GoalKind::Invariant,
            "Decay is the point",
            "edges fade",
            None,
        )
        .unwrap();
        let md = e.export_constitution(None).unwrap();
        assert!(md.contains("## Invariants"));
        assert!(md.contains("Decay is the point"));
    }
}
