// Generated by AI (UnitTest MCP)
use serde_json::Value;

use crate::{ConformanceRecord, Lodestar, Result, Verdict};

impl Lodestar {
    /// Render a task's durable conformance record chain as committed-friendly,
    /// portable proof-of-work (ADR-0031): each check's stable id, verdict, acting
    /// agent, claim window, and evidence summary. Optionally write it to `path` so
    /// the proof leaves the local ledger for review, CI, and audit. Deterministic
    /// and model-free — it only reads the durable audit trail (mirrors
    /// [`export_constitution`](Self::export_constitution)).
    pub fn export_evidence(&self, task_id: &str, path: Option<&str>) -> Result<String> {
        let records = self.conformance_history(task_id)?;
        let markdown = render_evidence(task_id, &records);
        if let Some(destination) = path {
            if let Some(parent) = std::path::Path::new(destination).parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(destination, &markdown)?;
        }
        Ok(markdown)
    }
}

/// The canonical lowercase label for a verdict, taken from its `Serialize` impl so
/// there is no hand-maintained match to drift from the enum.
fn verdict_label(verdict: &Verdict) -> String {
    serde_json::to_value(verdict)
        .ok()
        .and_then(|value| value.as_str().map(str::to_string))
        .unwrap_or_else(|| "unknown".to_string())
}

/// Render the conformance chain as committed-friendly markdown. Each row resolves
/// back to the durable record by its stable `id`; the evidence summary carries the
/// provenance counts (executions, commits, changed nodes) behind the verdict.
fn render_evidence(task_id: &str, records: &[ConformanceRecord]) -> String {
    let mut out = format!("# Conformance evidence for `{task_id}`\n\n");
    out.push_str(
        "> Generated by Lodestar (ADR-0031). Portable proof-of-work: each row resolves to a \
         durable, provenance-bearing evidence record. Do not edit by hand.\n\n",
    );
    if records.is_empty() {
        out.push_str("_No conformance records: this task never reached a checked completion._\n");
        return out;
    }
    out.push_str("| Check | Verdict | Agent | Window (unix) | Checked | Summary |\n");
    out.push_str("|--:|---|---|---|--:|---|\n");
    for record in records {
        let bundle: Value = serde_json::from_str(&record.evidence).unwrap_or(Value::Null);
        let agent = bundle
            .get("agent_id")
            .and_then(Value::as_str)
            .unwrap_or("-");
        let started = bundle
            .get("started_at")
            .and_then(Value::as_i64)
            .unwrap_or(0);
        let ended = bundle.get("ended_at").and_then(Value::as_i64).unwrap_or(0);
        let summary = bundle.get("summary").and_then(Value::as_str).unwrap_or("");
        out.push_str(&format!(
            "| {} | {} | {} | {}-{} | {} | {} |\n",
            record.id,
            verdict_label(&record.verdict),
            agent,
            started,
            ended,
            record.checked_at,
            summary,
        ));
    }
    out.push('\n');
    for record in records {
        if !record.findings.trim().is_empty() {
            out.push_str(&format!(
                "- **#{} {}** — {}\n",
                record.id,
                verdict_label(&record.verdict),
                record.findings,
            ));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use crate::facade::test_support::engine;

    #[test]
    fn export_of_a_task_without_records_is_explicit_not_empty() {
        // A task that never reached a checked completion must produce a clear,
        // human-readable artifact — not an empty file that looks like "no proof
        // because nothing was checked" is indistinguishable from a write failure.
        let engine = engine();
        let markdown = engine.export_evidence("task:none", None).unwrap();
        assert!(markdown.contains("task:none"));
        assert!(markdown.contains("never reached a checked completion"));
    }
}
