// Generated by AI (UnitTest MCP)
//! Executive tool definitions and dispatch.

use super::conformance::parse_evidence;
use super::{bool_arg, i64_arg, ok, opt_str, optional_string_arg, req_str, text};
use lodestar_core::Lodestar;
use serde_json::{json, Value};

pub(super) fn definitions() -> Vec<Value> {
    vec![
        json!({
            "name": "create_task",
            "description": "Create work serving a goal. With blocked_by, the task remains unclaimable until the predecessor completes aligned, enabling progressive same-file handoffs without pretending to lock symbols or text.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "goal_id": { "type": "string" },
                    "title": { "type": "string" },
                    "acceptance": { "type": "string", "description": "What 'done' means." },
                    "blocked_by": { "type": "string", "description": "Optional predecessor task. The new task opens automatically only after that task completes aligned." }
                },
                "required": ["goal_id", "title"]
            }
        }),
        json!({
            "name": "decompose_goal",
            "description": "Break a goal into claimable tasks (uses a local model when reachable, else a single-task fallback).",
            "inputSchema": {
                "type": "object",
                "properties": { "goal_id": { "type": "string" } },
                "required": ["goal_id"]
            }
        }),
        json!({
            "name": "next_task",
            "description": "Suggest the next unblocked, claimable task (open or lease-expired), oldest first.",
            "inputSchema": { "type": "object", "properties": {} }
        }),
        json!({
            "name": "claim_task",
            "description": "Atomically claim a task with a lease (TTL seconds). Returns won=true only if this agent won the race — the coordination primitive that stops parallel agents colliding.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "task_id": { "type": "string" },
                    "agent": { "type": "string", "description": "Optional when LODESTAR_AGENT is configured." },
                    "lease_secs": { "type": "integer", "default": 300 }
                },
                "required": ["task_id"]
            }
        }),
        json!({
            "name": "renew_lease",
            "description": "Heartbeat: extend the lease on a task this agent still owns.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "task_id": { "type": "string" },
                    "agent": { "type": "string", "description": "Optional when LODESTAR_AGENT is configured." },
                    "lease_secs": { "type": "integer", "default": 300 }
                },
                "required": ["task_id"]
            }
        }),
        json!({
            "name": "complete_task",
            "description": "Complete a task only when claim-bounded ADR-0009 evidence conforms. Aligned completes; drift/uncertainty stay in review; violation blocks.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "task_id": { "type": "string" },
                    "agent": { "type": "string", "description": "Optional when LODESTAR_AGENT is configured." },
                    "evidence": { "type": "object", "description": "Versioned ConformanceEvidence returned by MindLeak evidence_for." }
                },
                "required": ["task_id", "evidence"]
            }
        }),
        json!({
            "name": "release_task",
            "description": "Release a claim back to open (owner-guarded).",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "task_id": { "type": "string" },
                    "agent": { "type": "string", "description": "Optional when LODESTAR_AGENT is configured." }
                },
                "required": ["task_id"]
            }
        }),
        json!({
            "name": "block_task",
            "description": "Mark a nonterminal task blocked and clear any live claim. An optional blocked_by predecessor must be same-goal, acyclic, and part of a one-to-one handoff chain; release/claim cannot bypass it.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "task_id": { "type": "string" },
                    "blocked_by": { "type": "string" }
                },
                "required": ["task_id"]
            }
        }),
        json!({
            "name": "reopen_task",
            "description": "Return a stranded task (in_review after a drift/needs-human completion, or manually blocked with no predecessor gate) to open so an agent can claim it again. Refuses to bypass a handoff dependency, to disturb an active claim (use release_task), or to revive terminal work.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "task_id": { "type": "string" }
                },
                "required": ["task_id"]
            }
        }),
        json!({
            "name": "abandon_task",
            "description": "Permanently retire a nonterminal task to abandoned (terminal) — the deliberate 'this work should not be done' verb, distinct from reopen_task (recover to claimable) and reset_database (wipe everything). Refuses to disturb an active claim (release_task first) or re-retire terminal work.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "task_id": { "type": "string" }
                },
                "required": ["task_id"]
            }
        }),
        json!({
            "name": "board",
            "description": "The coordination snapshot of tasks with owner, status, and lease. Returns every task by default; pass include_terminal=false for only the live/actionable set (open, claimed, in_review, blocked), leaving done/abandoned tasks durable but out of view.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "include_terminal": { "type": "boolean", "default": true, "description": "Include terminal done/abandoned tasks (default true)." }
                }
            }
        }),
    ]
}

pub(super) fn dispatch(
    engine: &Lodestar,
    name: &str,
    args: &Value,
) -> Option<Result<Value, String>> {
    match name {
        "create_task" => Some((|| {
            let task = engine
                .create_task_after(
                    req_str(args, "goal_id")?,
                    req_str(args, "title")?,
                    opt_str(args, "acceptance").unwrap_or_default().as_str(),
                    optional_string_arg(args, "blocked_by")?,
                )
                .map_err(|e| e.to_string())?;
            ok(&task)
        })()),
        "decompose_goal" => Some((|| {
            ok(&engine
                .decompose_goal(req_str(args, "goal_id")?)
                .map_err(|e| e.to_string())?)
        })()),
        "next_task" => Some((|| match engine.next_task().map_err(|e| e.to_string())? {
            Some(t) => ok(&t),
            None => text("no claimable task".to_string()),
        })()),
        "claim_task" => Some((|| {
            let won = engine
                .claim_task(
                    req_str(args, "task_id")?,
                    opt_str(args, "agent").unwrap_or_default().as_str(),
                    i64_arg(args, "lease_secs", 300),
                )
                .map_err(|e| e.to_string())?;
            ok(&json!({ "won": won }))
        })()),
        "renew_lease" => Some((|| {
            let renewed = engine
                .renew_lease(
                    req_str(args, "task_id")?,
                    opt_str(args, "agent").unwrap_or_default().as_str(),
                    i64_arg(args, "lease_secs", 300),
                )
                .map_err(|e| e.to_string())?;
            ok(&json!({ "renewed": renewed }))
        })()),
        "complete_task" => Some((|| {
            let evidence = parse_evidence(args)?;
            let (completed, conformance) = engine
                .complete_task(
                    req_str(args, "task_id")?,
                    opt_str(args, "agent").unwrap_or_default().as_str(),
                    &evidence,
                )
                .map_err(|e| e.to_string())?;
            ok(&json!({ "completed": completed, "conformance": conformance }))
        })()),
        "release_task" => Some((|| {
            let released = engine
                .release_task(
                    req_str(args, "task_id")?,
                    opt_str(args, "agent").unwrap_or_default().as_str(),
                )
                .map_err(|e| e.to_string())?;
            ok(&json!({ "released": released }))
        })()),
        "block_task" => Some((|| {
            let blocked = engine
                .block_task(
                    req_str(args, "task_id")?,
                    optional_string_arg(args, "blocked_by")?,
                )
                .map_err(|e| e.to_string())?;
            ok(&json!({ "blocked": blocked }))
        })()),
        "reopen_task" => Some((|| {
            let reopened = engine
                .reopen_task(req_str(args, "task_id")?)
                .map_err(|e| e.to_string())?;
            ok(&json!({ "reopened": reopened }))
        })()),
        "abandon_task" => Some((|| {
            let abandoned = engine
                .abandon_task(req_str(args, "task_id")?)
                .map_err(|e| e.to_string())?;
            ok(&json!({ "abandoned": abandoned }))
        })()),
        "board" => Some((|| {
            ok(&engine
                .board(bool_arg(args, "include_terminal", true))
                .map_err(|e| e.to_string())?)
        })()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::super::call;
    use super::*;
    use lodestar_core::llm::LlmClient;
    use lodestar_core::GoalKind;

    #[test]
    fn create_task_dispatch_accepts_a_predecessor() {
        let engine = Lodestar::open_in_memory().unwrap();
        let goal = engine
            .define_goal(GoalKind::Objective, "Handoff", "serialize edits", None)
            .unwrap();
        let first = engine.create_task(&goal.id, "First", "done").unwrap();

        let result = call(
            &engine,
            &json!({
                "name": "create_task",
                "arguments": {
                    "goal_id": goal.id,
                    "title": "Second",
                    "acceptance": "done",
                    "blocked_by": first.id
                }
            }),
        )
        .unwrap();
        let task: Value =
            serde_json::from_str(result["content"][0]["text"].as_str().unwrap()).unwrap();

        assert_eq!(task["status"], "blocked");
        assert!(task["blocked_by"].as_str().unwrap().starts_with("task:"));
    }

    #[test]
    fn decompose_goal_dispatch_falls_back_to_a_single_task_offline() {
        // The decompose_goal tool calls the optional planning model. With no
        // model reachable it must degrade to a single seed task rather than
        // error — and the test must stay deterministic regardless of whatever
        // model a developer happens to be running locally.
        let engine = Lodestar::open_in_memory()
            .unwrap()
            .with_llm(LlmClient::unreachable());
        let goal = engine
            .define_goal(
                GoalKind::Objective,
                "Add search",
                "Implement FTS search",
                None,
            )
            .unwrap();

        let result = call(
            &engine,
            &json!({
                "name": "decompose_goal",
                "arguments": { "goal_id": goal.id }
            }),
        )
        .unwrap();
        let tasks: Value =
            serde_json::from_str(result["content"][0]["text"].as_str().unwrap()).unwrap();
        let tasks = tasks.as_array().unwrap();
        assert_eq!(tasks.len(), 1);
        assert!(tasks[0]["title"].as_str().unwrap().contains("Add search"));
    }

    #[test]
    fn reopen_task_dispatch_returns_a_manual_hold_to_open() {
        let engine = Lodestar::open_in_memory().unwrap();
        let goal = engine
            .define_goal(GoalKind::Objective, "Recover", "unstick work", None)
            .unwrap();
        let task = engine.create_task(&goal.id, "Held", "done").unwrap();
        // A manual hold with no predecessor was previously unrecoverable via the
        // tool surface; reopen_task must return it to a claimable state.
        engine.block_task(&task.id, None).unwrap();

        let result = call(
            &engine,
            &json!({ "name": "reopen_task", "arguments": { "task_id": task.id } }),
        )
        .unwrap();
        let payload: Value =
            serde_json::from_str(result["content"][0]["text"].as_str().unwrap()).unwrap();
        assert_eq!(payload["reopened"], true);

        let board = engine.board(true).unwrap();
        let reopened = board.iter().find(|t| t.id == task.id).unwrap();
        assert_eq!(reopened.status.as_str(), "open");
    }

    #[test]
    fn board_tool_filters_terminal_tasks_when_requested() {
        let engine = Lodestar::open_in_memory().unwrap();
        let goal = engine
            .define_goal(GoalKind::Objective, "Ship", "do it", None)
            .unwrap();
        let live = engine.create_task(&goal.id, "Live", "").unwrap();
        let retired = engine.create_task(&goal.id, "Retired", "").unwrap();
        engine.abandon_task(&retired.id).unwrap();

        // Default: every task, including the abandoned one.
        let all: Value = serde_json::from_str(
            call(&engine, &json!({ "name": "board", "arguments": {} })).unwrap()["content"][0]
                ["text"]
                .as_str()
                .unwrap(),
        )
        .unwrap();
        assert!(all
            .as_array()
            .unwrap()
            .iter()
            .any(|task| task["id"] == retired.id));

        // Opt into the lean view: terminal tasks drop out, live work remains.
        let active: Value = serde_json::from_str(
            call(
                &engine,
                &json!({ "name": "board", "arguments": { "include_terminal": false } }),
            )
            .unwrap()["content"][0]["text"]
                .as_str()
                .unwrap(),
        )
        .unwrap();
        let ids: Vec<&str> = active
            .as_array()
            .unwrap()
            .iter()
            .map(|task| task["id"].as_str().unwrap())
            .collect();
        assert!(ids.contains(&live.id.as_str()));
        assert!(!ids.contains(&retired.id.as_str()));
    }

    #[test]
    fn create_task_rejects_malformed_predecessor_and_preserves_legacy_calls() {
        let engine = Lodestar::open_in_memory().unwrap();
        let goal = engine
            .define_goal(GoalKind::Objective, "Handoff", "serialize edits", None)
            .unwrap();
        let malformed = json!({
            "name": "create_task",
            "arguments": {
                "goal_id": goal.id,
                "title": "Unsafe",
                "blocked_by": 42
            }
        });
        assert!(call(&engine, &malformed)
            .unwrap_err()
            .contains("must be a string"));

        let legacy = call(
            &engine,
            &json!({
                "name": "create_task",
                "arguments": { "goal_id": goal.id, "title": "Legacy" }
            }),
        )
        .unwrap();
        let task: Value =
            serde_json::from_str(legacy["content"][0]["text"].as_str().unwrap()).unwrap();
        assert_eq!(task["status"], "open");
        assert!(task["blocked_by"].is_null());
    }
}
