// Generated by AI (UnitTest MCP)
use crate::db;
use crate::decay::{SignalEvidence, PRUNE_THRESHOLD};
use crate::graph::test_support::*;
use crate::graph::{ArtifactStub, Direction, GraphStore, SignalCandidate};
use crate::model::{Edge, Node, NodeType, RelationType};

#[test]
fn decay_policy_retroactively_overrides_the_stored_half_life() {
    let graph = store();
    add_node(&graph, "artifact:a", NodeType::Artifact, "a", NOW);
    add_node(&graph, "artifact:b", NodeType::Artifact, "b", NOW);
    graph
        .upsert_edge(&raw_edge(
            "artifact:a",
            "artifact:b",
            RelationType::Modified,
            1.0,
            24.0,
            NOW,
        ))
        .unwrap();

    let before = graph
        .traverse(
            &["artifact:a".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW + 24 * HOUR,
        )
        .unwrap();
    assert!((before.edges[0].effective - 0.5).abs() < 1e-9);

    let graph = graph.with_decay_policy(policy(&[(RelationType::Modified, 48.0)], 0.05));
    let after = graph
        .traverse(
            &["artifact:a".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW + 24 * HOUR,
        )
        .unwrap();
    assert_eq!(after.edges[0].half_life_hours, 48.0);
    assert!((after.edges[0].effective - 2f64.sqrt() / 2.0).abs() < 1e-9);
}

#[test]
fn configured_threshold_controls_all_active_edge_surfaces_and_prune() {
    let graph = store().with_decay_policy(policy(&[], 0.6));
    add_node(&graph, "agent:a", NodeType::Agent, "a", NOW);
    add_node(&graph, "artifact:a", NodeType::Artifact, "a", NOW);
    add_node(&graph, "artifact:b", NodeType::Artifact, "b", NOW);
    for (source, target, relation) in [
        ("artifact:a", "artifact:b", RelationType::Modified),
        ("agent:a", "artifact:a", RelationType::Observed),
    ] {
        graph
            .upsert_edge(&raw_edge(source, target, relation, 1.0, 1.0, NOW))
            .unwrap();
    }
    let later = NOW + HOUR;

    assert_eq!(graph.counts(later).unwrap(), (3, 0));
    assert!(graph.snapshot(10, later).unwrap().edges.is_empty());
    assert!(graph.export_graph(later).unwrap().edges.is_empty());
    assert!(graph
        .impact_radius(&["artifact:b".to_string()], later)
        .unwrap()
        .edges
        .is_empty());
    assert_eq!(graph.list_agents(later).unwrap()[0].observations, 0);

    let outcome = graph.prune_with_signal(later).unwrap();
    assert_eq!(outcome.edges_removed, 2);
}

#[test]
fn caller_minimum_cannot_resurrect_inactive_edges() {
    let graph = store().with_decay_policy(policy(&[], 0.6));
    add_node(&graph, "artifact:a", NodeType::Artifact, "a", NOW);
    add_node(&graph, "artifact:b", NodeType::Artifact, "b", NOW);
    graph
        .upsert_edge(&raw_edge(
            "artifact:a",
            "artifact:b",
            RelationType::Imports,
            0.5,
            168.0,
            NOW,
        ))
        .unwrap();

    let traversed = graph
        .traverse(
            &["artifact:a".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW,
        )
        .unwrap();

    assert!(traversed.edges.is_empty());
}

#[test]
fn proven_signal_edge_outlives_a_one_off_at_the_same_age() {
    // ADR-0005: an edge reinforced repeatedly across a wide span earns a
    // longer half-life, so at equal age it keeps more weight than a one-off.
    // Same-session spam (narrow span) would NOT earn this.
    let s = store();
    add_node(&s, "artifact:a", NodeType::Artifact, "a", NOW);
    add_node(&s, "artifact:one_off", NodeType::Artifact, "o", NOW);
    add_node(&s, "artifact:proven", NodeType::Artifact, "p", NOW);

    // one-off: a single reinforcement at NOW.
    s.upsert_edge(&raw_edge(
        "artifact:a",
        "artifact:one_off",
        RelationType::Modified,
        1.0,
        24.0,
        NOW,
    ))
    .unwrap();
    // proven: 3 reinforcements spread across 100h, ending at NOW.
    for t in [NOW - 100 * HOUR, NOW - 50 * HOUR, NOW] {
        s.upsert_edge(&raw_edge(
            "artifact:a",
            "artifact:proven",
            RelationType::Modified,
            1.0,
            24.0,
            t,
        ))
        .unwrap();
    }

    // Four days after their (shared) last update.
    let now = NOW + 4 * 24 * HOUR;
    let sub = s
        .traverse(&["artifact:a".into()], Direction::Outgoing, 1, 0.0, now)
        .unwrap();
    let one_off = sub
        .edges
        .iter()
        .find(|e| e.target_id == "artifact:one_off")
        .unwrap();
    let proven = sub
        .edges
        .iter()
        .find(|e| e.target_id == "artifact:proven")
        .unwrap();
    assert!(proven.effective > one_off.effective);
}

#[test]
fn resolved_failure_outlives_same_session_modified_spam() {
    let s = store();
    let stable_created = NOW - 10 * 24 * HOUR;
    s.upsert_node(&Node::new(
        "artifact:stable",
        NodeType::Artifact,
        "stable",
        stable_created,
    ))
    .unwrap();
    add_node(&s, "artifact:consumer", NodeType::Artifact, "consumer", NOW);
    add_node(&s, "artifact:spam", NodeType::Artifact, "spam", NOW);

    let failure = Node::new("execution:failure", NodeType::Execution, "cargo test", NOW)
        .with_content("exit=1\n");
    let success = Node::new(
        "execution:success",
        NodeType::Execution,
        "cargo test",
        NOW + 2 * HOUR,
    )
    .with_content("exit=0\n");
    let spam =
        Node::new("execution:spam", NodeType::Execution, "green", NOW).with_content("exit=0\n");
    let commit = Node::new("intent:commit", NodeType::Intent, "fix stable", NOW + HOUR);
    let decision = Node::new(
        "intent:decision",
        NodeType::Intent,
        "DECISION: preserve stable",
        NOW + HOUR,
    );
    for node in [failure, success, spam, commit, decision] {
        s.upsert_node(&node).unwrap();
    }

    let failed_on = raw_edge(
        "execution:failure",
        "artifact:stable",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    );
    s.upsert_edge(&failed_on).unwrap();
    s.upsert_edge(&raw_edge(
        "intent:commit",
        "artifact:stable",
        RelationType::Refactored,
        1.0,
        168.0,
        NOW + HOUR,
    ))
    .unwrap();
    s.upsert_edge(&raw_edge(
        "artifact:consumer",
        "artifact:stable",
        RelationType::Imports,
        1.0,
        168.0,
        NOW,
    ))
    .unwrap();
    s.upsert_edge(&raw_edge(
        "intent:decision",
        "artifact:stable",
        RelationType::RelatesTo,
        1.0,
        48.0,
        NOW + HOUR,
    ))
    .unwrap();
    for _ in 0..400 {
        s.upsert_edge(&raw_edge(
            "execution:spam",
            "artifact:spam",
            RelationType::Modified,
            1.0,
            24.0,
            NOW,
        ))
        .unwrap();
    }

    let evidence = s.signal_evidence(&failed_on, NOW + 6 * 24 * HOUR).unwrap();
    assert!(evidence.consequence);
    assert!(evidence.surprise);
    assert!(evidence.source_diversity >= 3);
    assert!(evidence.deliberate_attention);

    let failure_graph = s
        .traverse(
            &["artifact:stable".into()],
            Direction::Incoming,
            1,
            PRUNE_THRESHOLD,
            NOW + 6 * 24 * HOUR,
        )
        .unwrap();
    assert!(failure_graph
        .edges
        .iter()
        .any(|edge| edge.relation == RelationType::FailedOn));
    let spam_graph = s
        .traverse(
            &["artifact:spam".into()],
            Direction::Incoming,
            1,
            PRUNE_THRESHOLD,
            NOW + 6 * 24 * HOUR,
        )
        .unwrap();
    assert!(spam_graph.edges.is_empty());
}

#[test]
fn near_expiry_proven_signal_is_routed_to_consolidation() {
    let s = store();
    let target = Node::new(
        "artifact:stable",
        NodeType::Artifact,
        "stable",
        NOW - 10 * 24 * HOUR,
    );
    let failure = Node::new("execution:failure", NodeType::Execution, "cargo test", NOW)
        .with_content("exit=1\n");
    let success = Node::new(
        "execution:success",
        NodeType::Execution,
        "cargo test",
        NOW + 2 * HOUR,
    )
    .with_content("exit=0\n");
    let commit = Node::new("intent:commit", NodeType::Intent, "fix", NOW + HOUR);
    for node in [target, failure, success, commit] {
        s.upsert_node(&node).unwrap();
    }
    let failed_on = raw_edge(
        "execution:failure",
        "artifact:stable",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    );
    s.upsert_edge(&failed_on).unwrap();
    s.upsert_edge(&raw_edge(
        "intent:commit",
        "artifact:stable",
        RelationType::Refactored,
        1.0,
        168.0,
        NOW + HOUR,
    ))
    .unwrap();

    let candidates = s.expiring_signal_candidates(NOW + 20 * 24 * HOUR).unwrap();
    assert!(candidates
        .iter()
        .any(|candidate| candidate.relation == RelationType::FailedOn));

    let early = NOW + 24 * HOUR;
    let s = s.with_decay_policy(policy(&[], 0.5));
    assert!(s
        .expiring_signal_candidates(early)
        .unwrap()
        .iter()
        .any(|candidate| candidate.relation == RelationType::FailedOn));
    let s = s.with_decay_policy(policy(&[], 0.001));
    assert!(s.expiring_signal_candidates(early).unwrap().is_empty());

    let s = s.with_decay_policy(policy(&[(RelationType::FailedOn, 8_760.0)], 0.05));
    assert!(s
        .expiring_signal_candidates(NOW + 20 * 24 * HOUR)
        .unwrap()
        .is_empty());
}

#[test]
fn promotion_candidates_group_corroborating_signal_by_subject() {
    // ADR-0022: expiring proven-signal edges that share a target collapse into one
    // promotion candidate whose evidence is the distinct corroborating source nodes
    // plus the target — the shape the Intent plane's gated promoter consumes.
    let s = store();
    s.upsert_node(&Node::new(
        "artifact:stable",
        NodeType::Artifact,
        "stable",
        NOW - 10 * 24 * HOUR,
    ))
    .unwrap();
    // Three distinct failing executions on the same target...
    for i in 1..=3i64 {
        let id = format!("execution:failure{i}");
        s.upsert_node(
            &Node::new(&id, NodeType::Execution, "cargo test", NOW + i * HOUR)
                .with_content("exit=1\n"),
        )
        .unwrap();
        s.upsert_edge(&raw_edge(
            &id,
            "artifact:stable",
            RelationType::FailedOn,
            1.0,
            24.0,
            NOW + i * HOUR,
        ))
        .unwrap();
    }
    // ...later resolved (a success plus a refactor commit) so each failure edge is a
    // consequence and earns signal_multiplier > 1.
    s.upsert_node(
        &Node::new(
            "execution:success",
            NodeType::Execution,
            "cargo test",
            NOW + 5 * HOUR,
        )
        .with_content("exit=0\n"),
    )
    .unwrap();
    s.upsert_node(&Node::new(
        "intent:commit",
        NodeType::Intent,
        "fix stable",
        NOW + 5 * HOUR,
    ))
    .unwrap();
    s.upsert_edge(&raw_edge(
        "intent:commit",
        "artifact:stable",
        RelationType::Refactored,
        1.0,
        168.0,
        NOW + 5 * HOUR,
    ))
    .unwrap();

    let horizon = NOW + 20 * 24 * HOUR;
    // Sanity: the three failures are near-expiry proven signal.
    let failing_sources: std::collections::BTreeSet<_> = s
        .expiring_signal_candidates(horizon)
        .unwrap()
        .into_iter()
        .filter(|c| c.relation == RelationType::FailedOn && c.target_id == "artifact:stable")
        .map(|c| c.source_id)
        .collect();
    assert!(
        failing_sources.len() >= 3,
        "expected 3 corroborating failures, got {failing_sources:?}"
    );

    // The promotion pass collapses them into one subject-level candidate.
    let candidates = s.promotion_candidates(horizon).unwrap();
    let grouped = candidates
        .iter()
        .find(|c| {
            c.subject == "artifact:stable"
                && c.evidence_node_ids
                    .iter()
                    .filter(|id| id.starts_with("execution:failure"))
                    .count()
                    >= 3
        })
        .expect("a grouped failed_on promotion candidate");
    assert!(grouped
        .evidence_node_ids
        .contains(&"artifact:stable".to_string()));
    assert!(grouped.last_seen >= grouped.first_seen);
}

#[test]
fn expired_proven_signal_waits_for_consolidation_acknowledgement() {
    let s = store();
    s.upsert_node(&Node::new(
        "artifact:stable",
        NodeType::Artifact,
        "stable",
        NOW - 10 * 24 * HOUR,
    ))
    .unwrap();
    for node in [
        Node::new("execution:failure", NodeType::Execution, "cargo test", NOW)
            .with_content("exit=1\n"),
        Node::new(
            "execution:success",
            NodeType::Execution,
            "cargo test",
            NOW + 2 * HOUR,
        )
        .with_content("exit=0\n"),
        Node::new("intent:commit", NodeType::Intent, "fix stable", NOW + HOUR),
    ] {
        s.upsert_node(&node).unwrap();
    }
    s.upsert_edge(&raw_edge(
        "execution:failure",
        "artifact:stable",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    ))
    .unwrap();
    s.upsert_edge(&raw_edge(
        "intent:commit",
        "artifact:stable",
        RelationType::Refactored,
        1.0,
        168.0,
        NOW + HOUR,
    ))
    .unwrap();

    let outcome = s.prune_with_signal(NOW + 60 * 24 * HOUR).unwrap();
    assert!(outcome
        .signal_candidates
        .iter()
        .any(|candidate| candidate.relation == RelationType::FailedOn));
    assert!(s.get_node("execution:failure").unwrap().is_some());

    let owner = acquire_lease(&s, NOW + 60 * 24 * HOUR);
    s.commit_signal_consolidation(
        &owner,
        NOW + 60 * 24 * HOUR,
        &outcome.signal_candidates,
        &[],
        &[],
    )
    .unwrap();
    assert!(s.get_node("execution:failure").unwrap().is_none());
}

#[test]
fn signal_consolidation_commits_facts_and_acknowledgement_atomically() {
    let s = store();
    add_node(&s, "execution:failure", NodeType::Execution, "failure", NOW);
    add_node(&s, "artifact:target", NodeType::Artifact, "target", NOW);
    s.upsert_edge(&raw_edge(
        "execution:failure",
        "artifact:target",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    ))
    .unwrap();
    let candidate = SignalCandidate {
        source_id: "execution:failure".to_string(),
        target_id: "artifact:target".to_string(),
        relation: RelationType::FailedOn,
        effective: 0.01,
        signal_multiplier: 2.0,
        evidence: SignalEvidence {
            reinforcement_count: 1,
            ..SignalEvidence::default()
        },
        updated_at: NOW,
    };
    let intent = Node::new("intent:gist", NodeType::Intent, "gist", NOW);
    let link = Edge::new(
        "intent:gist",
        "artifact:target",
        RelationType::RelatesTo,
        NOW,
    );

    let owner = acquire_lease(&s, NOW);
    let (outcome, edges_removed, nodes_removed) = s
        .commit_signal_consolidation(&owner, NOW, &[candidate], &[intent], &[link])
        .unwrap();

    assert_eq!(outcome.nodes_created, 1);
    assert_eq!(outcome.edges_created, 1);
    assert_eq!(edges_removed, 1);
    assert_eq!(nodes_removed, 1);
    assert!(s.get_node("intent:gist").unwrap().is_some());
    assert!(s.get_node("execution:failure").unwrap().is_none());
}

#[test]
fn signal_consolidation_rolls_back_facts_when_persistence_fails() {
    let s = store();
    add_node(&s, "execution:failure", NodeType::Execution, "failure", NOW);
    add_node(&s, "artifact:target", NodeType::Artifact, "target", NOW);
    s.upsert_edge(&raw_edge(
        "execution:failure",
        "artifact:target",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    ))
    .unwrap();
    let candidate = SignalCandidate {
        source_id: "execution:failure".to_string(),
        target_id: "artifact:target".to_string(),
        relation: RelationType::FailedOn,
        effective: 0.01,
        signal_multiplier: 2.0,
        evidence: SignalEvidence {
            reinforcement_count: 1,
            ..SignalEvidence::default()
        },
        updated_at: NOW,
    };
    let intent = Node::new("intent:gist", NodeType::Intent, "gist", NOW);
    let invalid_link = Edge::new(
        "intent:gist",
        "artifact:missing",
        RelationType::RelatesTo,
        NOW,
    );

    let owner = acquire_lease(&s, NOW);
    assert!(s
        .commit_signal_consolidation(&owner, NOW, &[candidate], &[intent], &[invalid_link])
        .is_err());

    assert!(s.get_node("intent:gist").unwrap().is_none());
    assert!(s.get_node("execution:failure").unwrap().is_some());
    assert_eq!(
        s.traverse(
            &["execution:failure".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW,
        )
        .unwrap()
        .edges
        .len(),
        1
    );
}

#[test]
fn signal_consolidation_rolls_back_when_candidate_was_reinforced() {
    let s = store();
    add_node(&s, "execution:failure", NodeType::Execution, "failure", NOW);
    add_node(&s, "artifact:target", NodeType::Artifact, "target", NOW);
    s.upsert_edge(&raw_edge(
        "execution:failure",
        "artifact:target",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    ))
    .unwrap();
    let candidate = SignalCandidate {
        source_id: "execution:failure".to_string(),
        target_id: "artifact:target".to_string(),
        relation: RelationType::FailedOn,
        effective: 0.01,
        signal_multiplier: 2.0,
        evidence: SignalEvidence {
            reinforcement_count: 1,
            ..SignalEvidence::default()
        },
        updated_at: NOW,
    };
    s.upsert_edge(&raw_edge(
        "execution:failure",
        "artifact:target",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    ))
    .unwrap();
    let intent = Node::new("intent:gist", NodeType::Intent, "gist", NOW + HOUR);
    let link = Edge::new(
        "intent:gist",
        "artifact:target",
        RelationType::RelatesTo,
        NOW + HOUR,
    );

    let owner = acquire_lease(&s, NOW);
    let error = s
        .commit_signal_consolidation(&owner, NOW, &[candidate], &[intent], &[link])
        .unwrap_err();

    assert!(error.to_string().contains("changed during consolidation"));
    assert!(s.get_node("intent:gist").unwrap().is_none());
    let remaining = s
        .traverse(
            &["execution:failure".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW,
        )
        .unwrap();
    assert_eq!(remaining.edges[0].updated_at, NOW);
    assert_eq!(remaining.edges[0].signal_evidence.reinforcement_count, 2);
}

#[test]
fn signal_consolidation_allows_output_to_replace_the_candidate_edge_key() {
    let s = store();
    add_node(&s, "intent:gist", NodeType::Intent, "gist", NOW);
    add_node(&s, "artifact:target", NodeType::Artifact, "target", NOW);
    s.upsert_edge(&raw_edge(
        "intent:gist",
        "artifact:target",
        RelationType::Refactored,
        1.0,
        168.0,
        NOW,
    ))
    .unwrap();
    let candidate = SignalCandidate {
        source_id: "intent:gist".to_string(),
        target_id: "artifact:target".to_string(),
        relation: RelationType::Refactored,
        effective: 0.01,
        signal_multiplier: 2.0,
        evidence: SignalEvidence {
            reinforcement_count: 1,
            ..SignalEvidence::default()
        },
        updated_at: NOW,
    };
    let output = Edge::new(
        "intent:gist",
        "artifact:target",
        RelationType::Refactored,
        NOW + HOUR,
    );
    let owner = acquire_lease(&s, NOW);

    let (_, removed, _) = s
        .commit_signal_consolidation(&owner, NOW, &[candidate], &[], &[output])
        .unwrap();

    assert_eq!(removed, 1);
    let remaining = s
        .traverse(
            &["intent:gist".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW + HOUR,
        )
        .unwrap();
    assert_eq!(remaining.edges.len(), 1);
    assert_eq!(remaining.edges[0].updated_at, NOW + HOUR);
}

#[test]
fn authored_decision_is_not_an_episodic_consolidation_candidate() {
    let s = store();
    add_node(&s, "artifact:stable", NodeType::Artifact, "stable", NOW);
    add_node(
        &s,
        "intent:decision",
        NodeType::Intent,
        "DECISION: stable",
        NOW,
    );
    s.upsert_edge(&raw_edge(
        "intent:decision",
        "artifact:stable",
        RelationType::RelatesTo,
        1.0,
        48.0,
        NOW,
    ))
    .unwrap();

    let candidates = s.expiring_signal_candidates(NOW + 60 * 24 * HOUR).unwrap();
    assert!(candidates.is_empty());
    s.prune_with_signal(NOW + 60 * 24 * HOUR).unwrap();
    assert!(s.get_node("intent:decision").unwrap().is_some());
}

#[test]
fn unrelated_green_execution_does_not_award_consequence() {
    let s = store();
    s.upsert_node(&Node::new(
        "artifact:stable",
        NodeType::Artifact,
        "stable",
        NOW - 10 * 24 * HOUR,
    ))
    .unwrap();
    for node in [
        Node::new("execution:failure", NodeType::Execution, "cargo test", NOW)
            .with_content("exit=1\n"),
        Node::new(
            "execution:unrelated",
            NodeType::Execution,
            "cargo build",
            NOW + 2 * HOUR,
        )
        .with_content("exit=0\n"),
        Node::new("intent:commit", NodeType::Intent, "fix stable", NOW + HOUR),
    ] {
        s.upsert_node(&node).unwrap();
    }
    let failed_on = raw_edge(
        "execution:failure",
        "artifact:stable",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    );
    s.upsert_edge(&failed_on).unwrap();
    s.upsert_edge(&raw_edge(
        "intent:commit",
        "artifact:stable",
        RelationType::Refactored,
        1.0,
        168.0,
        NOW + HOUR,
    ))
    .unwrap();

    let evidence = s.signal_evidence(&failed_on, NOW + 3 * HOUR).unwrap();
    assert!(!evidence.consequence);
}

#[test]
fn reopened_legacy_edge_uses_the_new_read_time_policy() {
    let path = std::env::temp_dir().join(format!(
        "mindleak-policy-reopen-{}-{}.db",
        std::process::id(),
        NOW
    ));
    let _ = std::fs::remove_file(&path);
    {
        let graph = GraphStore::new(db::open(path.to_str().unwrap()).unwrap());
        add_node(&graph, "artifact:a", NodeType::Artifact, "a", NOW);
        add_node(&graph, "artifact:b", NodeType::Artifact, "b", NOW);
        graph
            .upsert_edge(&raw_edge(
                "artifact:a",
                "artifact:b",
                RelationType::Modified,
                1.0,
                37.0,
                NOW,
            ))
            .unwrap();
    }

    let graph = GraphStore::new(db::open(path.to_str().unwrap()).unwrap());
    let legacy = graph
        .traverse(
            &["artifact:a".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW,
        )
        .unwrap();
    assert_eq!(legacy.edges[0].half_life_hours, 37.0);
    drop(graph);

    let graph = GraphStore::new(db::open(path.to_str().unwrap()).unwrap())
        .with_decay_policy(policy(&[(RelationType::Modified, 48.0)], 0.05));
    let traversed = graph
        .traverse(
            &["artifact:a".to_string()],
            Direction::Outgoing,
            1,
            0.0,
            NOW,
        )
        .unwrap();

    assert_eq!(traversed.edges[0].half_life_hours, 48.0);
    drop(graph);
    std::fs::remove_file(path).unwrap();
}

#[test]
fn prune_removes_decayed_edges_and_orphan_executions() {
    let s = store();
    add_node(&s, "a", NodeType::Artifact, "a", NOW);
    add_node(&s, "c", NodeType::Artifact, "c", NOW);
    add_node(&s, "b", NodeType::Artifact, "b", NOW);
    add_node(
        &s,
        "execution:orphan",
        NodeType::Execution,
        "orphan run",
        NOW,
    );
    s.upsert_edge(&raw_edge("a", "c", RelationType::Calls, 1.0, 168.0, NOW))
        .unwrap();
    s.upsert_edge(&raw_edge(
        "a",
        "b",
        RelationType::Modified,
        1.0,
        1.0,
        NOW - 10 * HOUR,
    ))
    .unwrap();

    let outcome = s.prune_with_signal(NOW).unwrap();
    assert_eq!(outcome.edges_removed, 1); // only the decayed a->b
    assert_eq!(outcome.nodes_removed, 1); // the orphan execution node
    assert!(s.get_node("execution:orphan").unwrap().is_none());
    assert!(s.get_node("a").unwrap().is_some());
}

#[test]
fn prune_removes_removed_symbol_after_historical_edges_decay() {
    let s = store();
    let owner = Node::new("artifact:a", NodeType::Artifact, "a", NOW);
    let symbol = Node::new("symbol:a:old", NodeType::Symbol, "old", NOW);
    let contains = Edge::new("artifact:a", "symbol:a:old", RelationType::Contains, NOW);
    s.replace_structure("artifact:a", &[owner.clone(), symbol], &[contains], &[])
        .unwrap();
    add_node(&s, "agent:a", NodeType::Agent, "a", NOW);
    s.upsert_edge(&raw_edge(
        "agent:a",
        "symbol:a:old",
        RelationType::Observed,
        1.0,
        1.0,
        NOW - 10 * HOUR,
    ))
    .unwrap();

    s.replace_structure("artifact:a", &[owner], &[], &[])
        .unwrap();
    assert!(s.get_node("symbol:a:old").unwrap().is_some());

    let outcome = s.prune_with_signal(NOW).unwrap();
    assert_eq!(outcome.edges_removed, 1);
    assert_eq!(outcome.nodes_removed, 1);
    assert!(s.get_node("symbol:a:old").unwrap().is_none());
    assert!(s.search_nodes("old", 5).unwrap().is_empty());
}

// ADR-0021 ordering invariant: within one prune transaction, sub-threshold edges
// are deleted FIRST, then orphans are detected against the post-deletion edge set,
// so a node orphaned by the pass is reaped in that SAME pass — no second prune is
// ever required. A regression here (detecting orphans before deleting edges) would
// leave the execution node stranded until a later prune, the exact stale-looking
// "nodes_removed:0" symptom ADR-0021 pins against.
#[test]
fn prune_reaps_orphan_in_the_same_pass_that_deletes_its_last_edge() {
    let s = store();
    add_node(&s, "artifact:a", NodeType::Artifact, "a", NOW);
    add_node(&s, "execution:run", NodeType::Execution, "a run", NOW);
    // The execution's only edge is already decayed at prune time.
    s.upsert_edge(&raw_edge(
        "execution:run",
        "artifact:a",
        RelationType::Modified,
        1.0,
        1.0,
        NOW - 10 * HOUR,
    ))
    .unwrap();

    let outcome = s.prune_with_signal(NOW).unwrap();
    assert_eq!(outcome.edges_removed, 1); // the decayed edge
    assert_eq!(outcome.nodes_removed, 1); // the now-orphan execution, same pass
    assert!(s.get_node("execution:run").unwrap().is_none());
    assert!(s.get_node("artifact:a").unwrap().is_some());

    // A second prune has nothing left to do: single-pass reaping is complete.
    let second = s.prune_with_signal(NOW).unwrap();
    assert_eq!(second.edges_removed, 0);
    assert_eq!(second.nodes_removed, 0);
}

// ADR-0021 per-type retention contract: prune reaps transient/unresolved nodes
// (execution, symbol, package, and unresolved artifact STUBS) once edgeless, but
// RETAINS durable structure — a real ingested artifact, an intent, and an agent —
// even after every edge that referenced them has decayed away. Reaping a real
// artifact or an intent would churn stable ids / erase decision history, which the
// ADR forbids.
#[test]
fn prune_reaps_stub_but_retains_real_artifact_intent_and_agent() {
    let s = store();
    // A real consumer artifact importing an unresolved "ghost" (registered as a stub).
    let consumer = Node::new(
        "artifact:consumer.rs",
        NodeType::Artifact,
        "consumer.rs",
        NOW,
    );
    let ghost = Node::new("artifact:ghost.rs", NodeType::Artifact, "ghost.rs", NOW);
    let import = Edge::new(
        "artifact:consumer.rs",
        "artifact:ghost.rs",
        RelationType::Imports,
        NOW,
    );
    s.replace_structure(
        "artifact:consumer.rs",
        &[consumer, ghost],
        &[import],
        &[ArtifactStub {
            node_id: "artifact:ghost.rs".to_string(),
            candidate_ids: vec!["artifact:ghost.rs".to_string()],
        }],
    )
    .unwrap();

    // A durable intent and an agent, each reachable only via edges that will decay.
    add_node(&s, "intent:d", NodeType::Intent, "a decision", NOW);
    add_node(&s, "agent:a", NodeType::Agent, "a", NOW);
    add_node(&s, "execution:run", NodeType::Execution, "a run", NOW);
    s.upsert_edge(&raw_edge(
        "agent:a",
        "intent:d",
        RelationType::Observed,
        1.0,
        1.0,
        NOW,
    ))
    .unwrap();
    s.upsert_edge(&raw_edge(
        "intent:d",
        "execution:run",
        RelationType::RelatesTo,
        1.0,
        1.0,
        NOW,
    ))
    .unwrap();

    // Far enough out that every edge — including the 168h import — decays below the
    // prune threshold, leaving each node edgeless.
    let later = NOW + 60 * 24 * HOUR;
    let outcome = s.prune_with_signal(later).unwrap();

    // Reaped: the unresolved stub and the orphaned execution.
    assert!(s.get_node("artifact:ghost.rs").unwrap().is_none());
    assert!(s.get_node("execution:run").unwrap().is_none());
    assert_eq!(outcome.nodes_removed, 2);

    // Retained by design: the real artifact, the intent, and the agent.
    assert!(s.get_node("artifact:consumer.rs").unwrap().is_some());
    assert!(s.get_node("intent:d").unwrap().is_some());
    assert!(s.get_node("agent:a").unwrap().is_some());
}

#[test]
fn sustained_active_observation_becomes_rehearsal_signal() {
    let s = store();
    add_node(&s, "agent:a", NodeType::Agent, "a", NOW);
    add_node(&s, "artifact:x", NodeType::Artifact, "x", NOW);
    add_node(&s, "execution:failure", NodeType::Execution, "failure", NOW);
    let failure = raw_edge(
        "execution:failure",
        "artifact:x",
        RelationType::FailedOn,
        1.0,
        24.0,
        NOW,
    );
    s.upsert_edge(&failure).unwrap();
    for timestamp in [NOW, NOW + 24 * HOUR, NOW + 48 * HOUR] {
        s.upsert_edge(&raw_edge(
            "agent:a",
            "artifact:x",
            RelationType::Observed,
            1.0,
            48.0,
            timestamp,
        ))
        .unwrap();
    }

    let evidence = s.signal_evidence(&failure, NOW + 48 * HOUR).unwrap();
    let working = s.working_set("a", 7, NOW + 48 * HOUR).unwrap();

    assert!(evidence.deliberate_attention);
    assert_eq!(working[0].observation_count, 3);
    assert_eq!(working[0].observation_span_hours, 48.0);

    add_node(&s, "artifact:a", NodeType::Artifact, "a", NOW);
    s.upsert_edge(&raw_edge(
        "agent:a",
        "artifact:a",
        RelationType::Observed,
        1.0,
        48.0,
        NOW + 48 * HOUR,
    ))
    .unwrap();
    let s = s.with_working_set_size(1);

    assert_eq!(
        s.working_set("a", 7, NOW + 48 * HOUR).unwrap()[0].node.id,
        "artifact:a"
    );
    assert!(
        !s.signal_evidence(&failure, NOW + 48 * HOUR)
            .unwrap()
            .deliberate_attention
    );

    add_node(&s, "agent:b", NodeType::Agent, "b", NOW);
    for timestamp in [NOW, NOW + 24 * HOUR, NOW + 48 * HOUR] {
        s.upsert_edge(&raw_edge(
            "agent:b",
            "artifact:x",
            RelationType::Observed,
            1.0,
            48.0,
            timestamp,
        ))
        .unwrap();
    }
    assert!(
        s.signal_evidence(&failure, NOW + 48 * HOUR)
            .unwrap()
            .deliberate_attention
    );
}
