//! Markdown rendering helpers for human-facing executive tool responses.

use lodestar_core::{GoverningClause, HumanQuestion};

/// The human inbox as readable markdown.
///
/// Rendered rather than dumped as JSON because the reader is a person deciding
/// what to answer, and a wall of objects is not a decision aid. The structured
/// form still travels in `structuredContent` for programmatic callers.
pub(super) fn render_human_questions(questions: &[HumanQuestion]) -> String {
    if questions.is_empty() {
        return "## Waiting on you\n\nNothing. No agent is parked on a question from you."
            .to_string();
    }
    let mut out = format!("## Waiting on you ({})\n", questions.len());
    for question in questions {
        out.push_str(&format!(
            "\n### {}\n\n{}\n\n- task: `{}`\n- asked by: `{}`\n- waiting: {}\n- reply: `answer` with this task_id\n",
            question.task_title,
            question.question,
            question.task_id,
            question.asked_by,
            humanize_seconds(question.waiting_seconds),
        ));
    }
    out
}

/// A duration a person can read at a glance. Coarse on purpose: the point is
/// "this has been sitting for three days", not a stopwatch.
pub(super) fn humanize_seconds(seconds: i64) -> String {
    match seconds {
        s if s < 60 => format!("{s}s"),
        s if s < 3_600 => format!("{}m", s / 60),
        s if s < 86_400 => format!("{}h {}m", s / 3_600, (s % 3_600) / 60),
        s => format!("{}d {}h", s / 86_400, (s % 86_400) / 3_600),
    }
}

/// Render the clauses governing a task's scope as a bounded Markdown section for
/// pickup responses (`task_query` view=next / `task_claim` step=claim). Empty
/// when nothing governs.
pub(super) fn render_governing(governing: &[GoverningClause]) -> String {
    if governing.is_empty() {
        return String::new();
    }
    let mut section = String::from("\n\n**Governed by:**");
    for clause in governing {
        section.push_str(&format!(
            "\n- `{}` ({}, {}) — {}",
            clause.goal.id,
            clause.goal.kind.as_str(),
            clause.mode.as_str(),
            clause.goal.title
        ));
    }
    section
}

#[cfg(test)]
mod tests {
    // Generated by AI (UnitTest MCP)
    use super::*;
    use lodestar_core::model::{ArtifactBindingMode, ClauseOrigin, GoalKind, GoalStatus};
    use lodestar_core::Goal;

    fn question(task_id: &str, task_title: &str, waiting_seconds: i64) -> HumanQuestion {
        HumanQuestion {
            question_id: 1,
            task_id: task_id.to_string(),
            task_title: task_title.to_string(),
            asked_by: "agent-a".to_string(),
            question: "Should I use approach X?".to_string(),
            asked_at: 1_000,
            waiting_seconds,
        }
    }

    fn clause(id: &str, kind: GoalKind, title: &str, mode: ArtifactBindingMode) -> GoverningClause {
        GoverningClause {
            node_id: "artifact:crates/lib.rs".to_string(),
            goal: Goal {
                id: id.to_string(),
                slug: "a-slug".to_string(),
                kind,
                title: title.to_string(),
                statement: "Something must hold.".to_string(),
                status: GoalStatus::Active,
                version: 1,
                parent_id: None,
                superseded_by: None,
                reason: None,
                created_at: 1_000,
                constitution_version: Some("constitution:v1".to_string()),
                rationale: None,
                scope: None,
                evidence_contract: None,
                consequence: None,
                waivable: false,
                waiver_authority: None,
                origin: ClauseOrigin::Local,
                source_system: None,
                external_id: None,
                source_ref: None,
                source_digest: None,
            },
            mode,
        }
    }

    #[test]
    fn humanize_seconds_covers_every_bracket_boundary() {
        assert_eq!(humanize_seconds(0), "0s");
        assert_eq!(humanize_seconds(59), "59s");
        assert_eq!(humanize_seconds(60), "1m");
        assert_eq!(humanize_seconds(3_599), "59m");
        assert_eq!(humanize_seconds(3_600), "1h 0m");
        assert_eq!(humanize_seconds(86_399), "23h 59m");
        assert_eq!(humanize_seconds(86_400), "1d 0h");
        assert_eq!(humanize_seconds(90_000), "1d 1h");
    }

    #[test]
    fn render_human_questions_reports_nothing_waiting_when_the_inbox_is_empty() {
        assert_eq!(
            render_human_questions(&[]),
            "## Waiting on you\n\nNothing. No agent is parked on a question from you."
        );
    }

    #[test]
    fn render_human_questions_formats_one_question_with_a_humanized_wait() {
        let questions = vec![question("task:abc123", "Fix the thing", 125)];
        assert_eq!(
            render_human_questions(&questions),
            "## Waiting on you (1)\n\
             \n\
             ### Fix the thing\n\
             \n\
             Should I use approach X?\n\
             \n\
             - task: `task:abc123`\n\
             - asked by: `agent-a`\n\
             - waiting: 2m\n\
             - reply: `answer` with this task_id\n"
        );
    }

    #[test]
    fn render_human_questions_lists_every_question_in_order() {
        let questions = vec![
            question("task:first", "First question", 30),
            question("task:second", "Second question", 7_260),
        ];
        let rendered = render_human_questions(&questions);
        assert_eq!(
            rendered,
            "## Waiting on you (2)\n\
             \n\
             ### First question\n\
             \n\
             Should I use approach X?\n\
             \n\
             - task: `task:first`\n\
             - asked by: `agent-a`\n\
             - waiting: 30s\n\
             - reply: `answer` with this task_id\n\
             \n\
             ### Second question\n\
             \n\
             Should I use approach X?\n\
             \n\
             - task: `task:second`\n\
             - asked by: `agent-a`\n\
             - waiting: 2h 1m\n\
             - reply: `answer` with this task_id\n"
        );
    }

    #[test]
    fn render_governing_is_empty_when_nothing_governs() {
        assert_eq!(render_governing(&[]), "");
    }

    #[test]
    fn render_governing_renders_one_clause() {
        let governing = vec![clause(
            "goal:no-secrets-in-logs@constitution:v1",
            GoalKind::Constraint,
            "No secrets in logs",
            ArtifactBindingMode::Governed,
        )];
        assert_eq!(
            render_governing(&governing),
            "\n\n**Governed by:**\n- `goal:no-secrets-in-logs@constitution:v1` \
             (constraint, governed) — No secrets in logs"
        );
    }

    #[test]
    fn render_governing_lists_every_clause_in_order() {
        let governing = vec![
            clause(
                "goal:a@constitution:v1",
                GoalKind::Objective,
                "Goal A",
                ArtifactBindingMode::Governed,
            ),
            clause(
                "goal:b@constitution:v1",
                GoalKind::Invariant,
                "Goal B",
                ArtifactBindingMode::ForbidChange,
            ),
        ];
        assert_eq!(
            render_governing(&governing),
            "\n\n**Governed by:**\n- `goal:a@constitution:v1` (objective, governed) — Goal A\n\
             - `goal:b@constitution:v1` (invariant, forbid_change) — Goal B"
        );
    }
}
