// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import { test } from "node:test";
import { PassThrough } from "node:stream";
import { McpConnection } from "../src/protocol.js";

interface Harness {
  connection: McpConnection;
  sentLines: string[];
  reply: (obj: unknown) => void;
  serverToClient: PassThrough;
}

/** clientToServer is what the connection writes ("stdin"); serverToClient is what it reads ("stdout"). */
function harness(requestTimeoutMs = 200): Harness {
  const clientToServer = new PassThrough();
  const serverToClient = new PassThrough();
  const connection = new McpConnection(clientToServer, serverToClient, { requestTimeoutMs });

  const sentLines: string[] = [];
  let buffer = "";
  clientToServer.on("data", (chunk: Buffer) => {
    buffer += chunk.toString();
    let idx: number;
    while ((idx = buffer.indexOf("\n")) >= 0) {
      sentLines.push(buffer.slice(0, idx));
      buffer = buffer.slice(idx + 1);
    }
  });

  const reply = (obj: unknown) => {
    serverToClient.write(JSON.stringify(obj) + "\n");
  };

  return { connection, sentLines, reply, serverToClient };
}

test("resolves a request when a matching response line arrives", async () => {
  const { connection, reply } = harness();
  const promise = connection.request("ping", { a: 1 });
  reply({ jsonrpc: "2.0", id: 1, result: { ok: true } });
  assert.deepStrictEqual(await promise, { ok: true });
});

test("rejects a request when the response carries an error", async () => {
  const { connection, reply } = harness();
  const promise = connection.request("boom", {});
  reply({ jsonrpc: "2.0", id: 1, error: { code: -1, message: "nope" } });
  await assert.rejects(promise, /nope/);
});

test("rejects every pending request when the connection closes", async () => {
  const { connection, serverToClient } = harness();
  const first = connection.request("a", {});
  const second = connection.request("b", {});
  serverToClient.emit("close");
  await assert.rejects(first, /closed/);
  await assert.rejects(second, /closed/);
});

test("ignores an unparseable line instead of dropping the pending request", async () => {
  const { connection, reply, serverToClient } = harness();
  const promise = connection.request("ping", {});
  serverToClient.write("not json at all\n");
  reply({ jsonrpc: "2.0", id: 1, result: "fine" });
  assert.strictEqual(await promise, "fine");
});

test("times out a request that never receives a response", async () => {
  const { connection } = harness(50);
  await assert.rejects(connection.request("ping", {}), /timed out/);
});

test("notify sends a JSON-RPC message with no id and does not wait for a reply", () => {
  const { connection, sentLines } = harness();
  connection.notify("notifications/initialized", { a: 1 });
  assert.strictEqual(sentLines.length, 1);
  const parsed = JSON.parse(sentLines[0]) as Record<string, unknown>;
  assert.strictEqual(parsed.method, "notifications/initialized");
  assert.deepStrictEqual(parsed.params, { a: 1 });
  assert.strictEqual("id" in parsed, false);
});

test("a request already in flight when the request is issued still resolves by id, not by arrival order", async () => {
  const { connection, reply } = harness();
  const first = connection.request("a", {});
  const second = connection.request("b", {});
  // Reply out of order: id 2 (second) before id 1 (first).
  reply({ jsonrpc: "2.0", id: 2, result: "second-result" });
  reply({ jsonrpc: "2.0", id: 1, result: "first-result" });
  assert.strictEqual(await first, "first-result");
  assert.strictEqual(await second, "second-result");
});

test("request rejects immediately once the connection is already closed", async () => {
  const { connection, serverToClient } = harness();
  serverToClient.emit("close");
  await assert.rejects(connection.request("ping", {}), /closed/);
});
