import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import { postCheckoutHook } from "./install-hooks.mjs";
import {
  EXPECTED_HOOKS,
  healthMessage,
  isPreCommitHook,
  missingHooks,
  readHookFrom,
  setupCommand,
} from "./hook-health.mjs";

// A pre-commit generated hook names itself; that is the marker we key on.
const PRE_COMMIT_SHIM =
  "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexec pre-commit hook-impl --hook-type=post-commit\n";

const OURS = postCheckoutHook();

/** A hooks directory in the healthy state, so each test names one deviation. */
const HEALTHY = {
  "pre-commit": PRE_COMMIT_SHIM,
  "pre-push": PRE_COMMIT_SHIM,
  "post-commit": PRE_COMMIT_SHIM,
  "post-checkout": OURS,
};

/** A throwaway hooks directory, so no test reads the repository's real hooks. */
const withHooksDir = (files, run) => {
  const dir = mkdtempSync(join(tmpdir(), "hook-health-"));
  try {
    for (const [name, body] of Object.entries(files)) {
      writeFileSync(join(dir, name), body, "utf8");
    }
    run(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
};

const readerFor = (files) => (hook) => files[hook] ?? null;

test("a file that names pre-commit is an installed hook; anything else is not", () => {
  assert.equal(isPreCommitHook(PRE_COMMIT_SHIM), true);
  assert.equal(isPreCommitHook(null), false, "absent");
  assert.equal(
    isPreCommitHook("#!/bin/sh\necho hand-written\n"),
    false,
    "a hand-written hook does not run pre-commit's stages",
  );
});

test("a complete installation reports nothing missing", () => {
  assert.deepEqual(missingHooks(readerFor(HEALTHY)), []);
});

test("a missing post-commit is named, and only it", () => {
  // The exact drift this guard exists to catch: pre-commit and pre-push were
  // installed before post-commit joined default_install_hook_types, so commits
  // land with no provenance and nothing says so.
  const reader = readerFor({ ...HEALTHY, "post-commit": null });
  assert.deepEqual(missingHooks(reader), [
    { hook: "post-commit", owner: "pre-commit", present: false },
  ]);
});

test("a hook file that exists but is not pre-commit's counts as missing", () => {
  const reader = readerFor({
    ...HEALTHY,
    "pre-push": "#!/bin/sh\necho stale\n",
  });
  assert.deepEqual(missingHooks(reader), [
    { hook: "pre-push", owner: "pre-commit", present: true },
  ]);
});

// The state every clone made before post-checkout moved off pre-commit is in.
// It is strictly worse than an absent hook: something runs, so nothing looks
// broken, while pre-commit carries on snapshotting and restoring the whole
// working tree around every checkout — which is the behaviour being removed.
test("pre-commit's post-checkout shim counts as missing, not as installed", () => {
  const reader = readerFor({ ...HEALTHY, "post-checkout": PRE_COMMIT_SHIM });
  assert.deepEqual(missingHooks(reader), [
    { hook: "post-checkout", owner: "install-hooks", present: true },
  ]);
});

test("our own post-checkout hook is recognised as installed", () => {
  const reader = readerFor({ ...HEALTHY, "post-checkout": OURS });
  assert.deepEqual(missingHooks(reader), []);
});

test("the message names every missing hook and the one repair command", () => {
  const message = healthMessage([
    { hook: "pre-commit", owner: "pre-commit", present: false },
    { hook: "post-commit", owner: "pre-commit", present: false },
  ]);
  assert.match(message, /- pre-commit/);
  assert.match(message, /- post-commit/);
  assert.ok(
    message.includes(setupCommand("pre-commit")),
    "an actionable setup command, not just a complaint",
  );
});

test("a missing post-checkout names its own silent consequence and its own installer", () => {
  const message = healthMessage([
    { hook: "post-checkout", owner: "install-hooks", present: false },
  ]);
  assert.match(message, /- post-checkout/);
  assert.match(message, /reads as unclaimed until its first commit/);
  assert.ok(
    message.includes(setupCommand("install-hooks")),
    "post-checkout is not reinstalled by `pre-commit install`, so naming that " +
      "command would send the reader to a fix that cannot work",
  );
});

// A hook present but owned by the wrong installer must not read like an absent
// one: the remedy is the same command, but the reader who sees "absent" for a
// file that plainly exists stops trusting the report.
test("the message distinguishes a wrong-installer hook from an absent one", () => {
  const message = healthMessage([
    { hook: "post-checkout", owner: "install-hooks", present: true },
  ]);
  assert.match(message, /present, but not installed by install-hooks/);
  assert.doesNotMatch(message, /\(absent\)/);
});

test("reading a complete hooks directory off disk finds nothing missing", () => {
  withHooksDir(HEALTHY, (dir) => {
    assert.deepEqual(missingHooks(readHookFrom(dir)), []);
  });
});

test("reading a hooks directory that lacks post-commit names it", () => {
  const { "post-commit": _omitted, ...withoutPostCommit } = HEALTHY;
  withHooksDir(withoutPostCommit, (dir) => {
    assert.deepEqual(missingHooks(readHookFrom(dir)), [
      { hook: "post-commit", owner: "pre-commit", present: false },
    ]);
  });
});

test("reading a hooks directory that lacks post-checkout names it", () => {
  // Without it a freshly created worktree reads as unclaimed until a first
  // commit that may never come (ADR-0038).
  const { "post-checkout": _omitted, ...withoutPostCheckout } = HEALTHY;
  withHooksDir(withoutPostCheckout, (dir) => {
    assert.deepEqual(missingHooks(readHookFrom(dir)), [
      { hook: "post-checkout", owner: "install-hooks", present: false },
    ]);
  });
});

test("the expected set names each hook's installer", () => {
  assert.deepEqual(EXPECTED_HOOKS, [
    { hook: "pre-commit", owner: "pre-commit" },
    { hook: "pre-push", owner: "pre-commit" },
    { hook: "post-commit", owner: "pre-commit" },
    { hook: "post-checkout", owner: "install-hooks" },
  ]);
});
