// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import { test } from "node:test";

import {
  ARTEFACT_KINDS,
  claimStateRefusal,
  classifyArtefact,
  classifyWorktree,
  formatBytes,
  hasLanded,
  liveClaimBranches,
  planArtefactSweep,
  PROTECTED_BRANCHES,
  reclaimScriptFreshness,
  readLiveClaimState,
  revalidateBeforeReclaim,
} from "./worktree-reclaim.mjs";

const idle = {
  path: "C:/Repos/MindLeak-done",
  branch: "fix/something-that-shipped",
  bare: false,
  dirty: false,
  landed: true,
  owner: null,
  building: false,
};

test("runs only when the reclaim script matches origin/main after fetching", () => {
  assert.deepEqual(
    reclaimScriptFreshness({ fetched: true, matchesOrigin: true }),
    { current: true, reason: null },
  );
});

test("refuses a stale reclaim script before inspecting shared worktrees", () => {
  assert.deepEqual(
    reclaimScriptFreshness({ fetched: true, matchesOrigin: false }),
    {
      current: false,
      reason: "this script differs from origin/main",
    },
  );
});

test("refuses to reclaim when origin cannot be fetched", () => {
  assert.deepEqual(
    reclaimScriptFreshness({ fetched: false, matchesOrigin: true }),
    {
      current: false,
      reason: "could not fetch origin before checking this script's version",
    },
  );
});

test("reclaims a merged, clean, idle worktree", () => {
  const verdict = classifyWorktree(idle, { session: "session:v1:me" });
  assert.equal(verdict.reclaim, true);
  assert.equal(verdict.branch, "fix/something-that-shipped");
});

test("never takes a branch held by a live task claim", () => {
  const verdict = classifyWorktree(idle, {
    session: "session:v1:me",
    liveClaimBranches: new Set([idle.branch]),
  });
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /live Lodestar claim/);
});

test("fails closed when authoritative claim state is unavailable", () => {
  const verdict = classifyWorktree(idle, {
    session: "session:v1:me",
    claimStateAvailable: false,
  });
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /claim state is unavailable/);
});

test("only unexpired claimed tasks protect their declared branches", () => {
  const now = 1_700_000_000;
  const branches = liveClaimBranches(
    [
      {
        status: "claimed",
        branch: "fix/live",
        lease_expires_at: now + 60,
      },
      {
        status: "claimed",
        branch: "fix/expired",
        lease_expires_at: now - 1,
      },
      { status: "open", branch: "fix/open", lease_expires_at: null },
      { status: "claimed", branch: null, lease_expires_at: now + 60 },
    ],
    now,
  );

  assert.deepEqual([...branches], ["fix/live"]);
});

test("reads live claim branches through the shared Lodestar client", () => {
  const now = 1_700_000_000;
  let requested;
  const state = readLiveClaimState("C:/Repos/MindLeak", {
    now,
    resolveServerFn: () => "lodestar-stub.mjs",
    callToolsFn: (_server, _root, calls) => {
      requested = calls;
      return [
        [
          {
            status: "claimed",
            branch: "fix/live",
            lease_expires_at: now + 60,
          },
        ],
      ];
    },
  });

  assert.equal(state.available, true);
  assert.deepEqual([...state.branches], ["fix/live"]);
  assert.deepEqual(requested, [
    {
      name: "task_query",
      arguments: { view: "board", include_terminal: false },
    },
  ]);
});

test("reports unavailable claim state when the Lodestar board cannot be read", () => {
  const absent = readLiveClaimState("C:/Repos/MindLeak", {
    resolveServerFn: () => null,
  });
  assert.equal(absent.available, false);
  assert.match(absent.reason, /no lodestar-mcp binary/);

  const unreadable = readLiveClaimState("C:/Repos/MindLeak", {
    resolveServerFn: () => "lodestar-stub.mjs",
    callToolsFn: () => {
      throw new Error("ledger unavailable");
    },
  });
  assert.equal(unreadable.available, false);
  assert.match(unreadable.reason, /ledger unavailable/);
});

test("refuses explicitly when Lodestar answers without a readable board", () => {
  const state = readLiveClaimState("C:/Repos/MindLeak", {
    resolveServerFn: () => "lodestar-stub.mjs",
    callToolsFn: () => [{ error: "unknown task board event" }],
  });

  assert.equal(state.available, false);
  assert.equal(state.boardUnreadable, true);
  assert.match(claimStateRefusal(state), /refusing to reclaim named worktrees/);
  assert.match(
    claimStateRefusal(state),
    /almost certainly older than the ledger/,
  );
  assert.doesNotMatch(
    claimStateRefusal(state),
    /held by a live Lodestar claim/,
  );
});

test("apply-time revalidation closes the report-to-delete claim race", () => {
  assert.equal(
    classifyWorktree(idle, { liveClaimBranches: new Set() }).reclaim,
    true,
  );

  const verdict = revalidateBeforeReclaim(idle, {
    readClaimState: () => ({
      available: true,
      branches: new Set([idle.branch]),
    }),
  });
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /live Lodestar claim/);
});

test("apply-time revalidation fails closed when the board disappears", () => {
  const verdict = revalidateBeforeReclaim(idle, {
    readClaimState: () => ({
      available: false,
      branches: new Set(),
      reason: "ledger unavailable",
    }),
  });
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /claim state is unavailable/);
});

// Everything below is a refusal. A cleanup tool tested only on what it deletes
// has not been tested on what matters: no report can be un-deleted.

test("never takes the primary checkout", () => {
  const verdict = classifyWorktree({ ...idle, bare: true }, {});
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /primary checkout/);
});

/**
 * Found on the first live run against 94 real worktrees. This tool's own
 * worktree was merged, clean and idle, so every other rule said yes — it would
 * have deleted `target/` out from under the running process and then tried to
 * remove the checkout it was executing in. A cleanup tool must not be its own
 * first casualty.
 */
test("never takes the worktree it is running in", () => {
  const verdict = classifyWorktree({ ...idle, current: true }, {});
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /running here/);
});

test("never takes a protected branch, however merged it looks", () => {
  for (const branch of PROTECTED_BRANCHES) {
    const verdict = classifyWorktree({ ...idle, branch }, {});
    assert.equal(verdict.reclaim, false, `${branch} must be refused`);
    assert.match(verdict.reason, /protected/);
  }
});

test("never takes a tree with uncommitted or untracked changes", () => {
  // Untracked counts. A file nobody has staged yet exists nowhere else, which
  // makes it the most valuable thing in the tree rather than the least.
  const verdict = classifyWorktree({ ...idle, dirty: true }, {});
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /uncommitted or untracked/);
});

test("never takes work that has not landed on origin/main", () => {
  const verdict = classifyWorktree({ ...idle, landed: false }, {});
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /have not landed/);
});

test("takes a branch whose pull request was closed unmerged", () => {
  // Such a branch never lands, so the rule above would keep its worktree
  // forever. Measured 2026-08-14: feat/enrolment-carries-the-public-key, closed
  // as a duplicate, was permanently unreclaimable. Closing a duplicate is the
  // correct move, and the cleanup tool was charging disk for it.
  const verdict = classifyWorktree(
    { ...idle, landed: false },
    { abandonedBranches: new Set([idle.branch]) },
  );
  assert.equal(verdict.reclaim, true);
  assert.match(verdict.reason, /closed unmerged/);
});

test("distinguishes abandoned from merged in the reason it reports", () => {
  // "reclaimed" reads very differently when the work was thrown away, and the
  // operator sees only this line.
  assert.match(classifyWorktree(idle, {}).reason, /merged and idle/);
});

test("keeps unlanded work that has no pull request at all", () => {
  // The distinction the fix turns on: no pull request means nobody has decided
  // against this yet, so it is in-progress work and stays. Only an explicit
  // closed-unmerged verdict releases it.
  const verdict = classifyWorktree(
    { ...idle, landed: false },
    { abandonedBranches: new Set(["some/other-branch"]) },
  );
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /have not landed/);
});

test("abandonment never overrides a refusal that outranks it", () => {
  // An abandoned branch must widen exactly one rule, not become a skeleton key
  // for the guards ahead of it — each of these protects something the closed
  // pull request says nothing about.
  const abandonedBranches = new Set([idle.branch]);
  const cases = [
    [{ dirty: true }, {}, /uncommitted or untracked/],
    [{ building: true }, {}, /build is running/],
    [{ branch: null }, {}, /detached/],
    [{ branch: "main" }, {}, /protected/],
    [{ bare: true }, {}, /primary checkout/],
    [{ current: true }, {}, /running here/],
    [{}, { liveClaimBranches: new Set([idle.branch]) }, /live Lodestar claim/],
    [{}, { claimStateAvailable: false }, /claim state is unavailable/],
    [
      { owner: "session:v1:someone-else" },
      { session: "session:v1:me" },
      /owned by session/,
    ],
  ];

  for (const [facts, options, expected] of cases) {
    const verdict = classifyWorktree(
      { ...idle, landed: false, ...facts },
      { ...options, abandonedBranches },
    );
    assert.equal(verdict.reclaim, false, `${expected} should still refuse`);
    assert.match(verdict.reason, expected);
  }
});

test("never takes a worktree another session owns", () => {
  const verdict = classifyWorktree(
    { ...idle, owner: "session:v1:someone-else" },
    { session: "session:v1:me" },
  );
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /owned by session/);
});

test("takes a worktree this session owns", () => {
  const verdict = classifyWorktree(
    { ...idle, owner: "session:v1:me" },
    { session: "session:v1:me" },
  );
  assert.equal(verdict.reclaim, true);
});

test("never takes a tree with a build running in it", () => {
  const verdict = classifyWorktree({ ...idle, building: true }, {});
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /build is running/);
});

test("never takes a detached HEAD, because nothing names what it holds", () => {
  const verdict = classifyWorktree({ ...idle, branch: null }, {});
  assert.equal(verdict.reclaim, false);
  assert.match(verdict.reason, /detached/);
});

/**
 * The regression this rule exists for. A squash or rebase merge lands every
 * line under a NEW commit id, so `git merge-base --is-ancestor` answers "no"
 * for work that is fully merged. An agent here used ancestry, concluded 245
 * merged lines were lost, and queued a PR to restore code already on main.
 *
 * `git cherry` marks an upstream-equivalent patch `-` and a genuinely absent
 * one `+`, which is the question actually being asked.
 */
test("treats a squash-merged branch as landed, not as lost work", () => {
  assert.equal(
    hasLanded("- 1a2b3c squashed away\n- 4d5e6f also landed\n"),
    true,
  );
});

test("treats a branch with any unlanded commit as not landed", () => {
  assert.equal(hasLanded("- 1a2b3c landed\n+ 9f8e7d never landed\n"), false);
});

test("treats a branch with no commits as landed", () => {
  assert.equal(hasLanded("\n  \n"), true);
});

test("reports sizes in a unit a human can decide on", () => {
  assert.equal(formatBytes(0), "0.00 GiB");
  assert.equal(formatBytes(1024 ** 3), "1.00 GiB");
});

// --- sweeping build output from trees that are STAYING -------------------
//
// A different question from reclaiming a whole worktree: these trees are alive
// and keeping their caches is the default. Almost all of the 149.18 GiB
// measured on 2026-07-30 sat in trees nobody was going to remove.

const HOUR = 60 * 60 * 1000;
const NOW = 1_700_000_000_000;

/** A sweepable cache: merged, clean, unowned, idle for a week. */
const cache = (over = {}) => ({
  kind: "cargo-debug",
  path: "C:/Repos/MindLeak-x/target/debug",
  branch: "feat/x",
  bare: false,
  primary: false,
  dirty: false,
  landed: true,
  owner: null,
  building: false,
  modifiedAt: NOW - 7 * 24 * HOUR,
  bytes: 1024,
  files: 10,
  ...over,
});

test("sweeps a regenerable cache in a merged, clean, idle tree", () => {
  assert.equal(classifyArtefact(cache(), { now: NOW }).sweep, true);
});

test("never sweeps the bare host's target/release, which serves the running servers", () => {
  // Deleting this stops every agent mid-call, and the symptom (tools vanishing)
  // points nowhere near the cause.
  const verdict = classifyArtefact(
    cache({ bare: true, branch: null, kind: "cargo-release" }),
    { now: NOW },
  );
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /serves the running tools/);
});

test("still sweeps the bare host's target/debug, the largest measured candidate", () => {
  const verdict = classifyArtefact(
    cache({ bare: true, branch: null, kind: "cargo-debug" }),
    { now: NOW },
  );
  assert.equal(verdict.sweep, true);
});

// Measured 2026-08-13: this fleet serves from a NON-bare checkout on `main`.
// It is clean, landed, unowned and idle, so every other predicate passed and
// the sweep deleted the binaries `resolveServer` resolves to -- after which
// worktree-reclaim refused every worktree with "no lodestar-mcp binary found"
// and canonical-push could not publish. A guard keyed on `bare` alone never
// fired here.
test("never sweeps the serving checkout's target/release when it is not bare", () => {
  const verdict = classifyArtefact(
    cache({ primary: true, branch: "main", kind: "cargo-release" }),
    { now: NOW },
  );
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /serves the running tools/);
});

test("still sweeps the serving checkout's target/debug", () => {
  const verdict = classifyArtefact(
    cache({ primary: true, branch: "main", kind: "cargo-debug" }),
    { now: NOW },
  );
  assert.equal(verdict.sweep, true);
});

// The other half of the same rule: the commit hooks shell out to prettier and
// eslint from editors/vscode/node_modules, so sweeping it off the host breaks
// every subsequent commit there with MODULE_NOT_FOUND from a hook that
// modifies nothing.
test("never sweeps the serving checkout's extension node_modules", () => {
  const verdict = classifyArtefact(
    cache({
      primary: true,
      branch: "main",
      kind: "extension-node-modules",
    }),
    { now: NOW },
  );
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /serves the running tools/);
});

test("still sweeps a linked worktree's extension node_modules", () => {
  const verdict = classifyArtefact(cache({ kind: "extension-node-modules" }), {
    now: NOW,
  });
  assert.equal(verdict.sweep, true);
});

// The disk win this tool exists for lives in the linked worktrees, so sparing
// the host must not spare them too.
test("still sweeps a linked worktree's landed target/release", () => {
  const verdict = classifyArtefact(cache({ kind: "cargo-release" }), {
    now: NOW,
  });
  assert.equal(verdict.sweep, true);
});

test("never sweeps while a build is running", () => {
  const verdict = classifyArtefact(cache({ building: true }), { now: NOW });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /build is running/);
});

test("never sweeps a tree with uncommitted or untracked changes", () => {
  const verdict = classifyArtefact(cache({ dirty: true }), { now: NOW });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /uncommitted or untracked/);
});

test("never sweeps a detached HEAD, because nothing names what it holds", () => {
  const verdict = classifyArtefact(cache({ branch: null }), { now: NOW });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /detached HEAD/);
});

test("never sweeps work that has not landed on origin/main", () => {
  const verdict = classifyArtefact(cache({ landed: false }), { now: NOW });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /have not landed/);
});

test("never sweeps a branch an open pull request still points at", () => {
  // Landed and still open means a follow-up commit is expected; rebuilding from
  // cold to answer a review comment is a cost this tool would have imposed.
  const verdict = classifyArtefact(cache(), {
    now: NOW,
    openPrBranches: new Set(["feat/x"]),
  });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /open pull request/);
});

test("never sweeps a cache another session owns", () => {
  const verdict = classifyArtefact(cache({ owner: "session:v1:other" }), {
    now: NOW,
    session: "session:v1:me",
  });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /owned by session/);
});

test("sweeps a cache this session owns", () => {
  const verdict = classifyArtefact(cache({ owner: "session:v1:me" }), {
    now: NOW,
    session: "session:v1:me",
  });
  assert.equal(verdict.sweep, true);
});

test("never sweeps inside the recent-activity grace period", () => {
  const verdict = classifyArtefact(cache({ modifiedAt: NOW - HOUR }), {
    now: NOW,
    graceMs: 4 * HOUR,
  });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /grace period/);
});

test("never sweeps a cache newer than the age threshold", () => {
  const verdict = classifyArtefact(cache({ modifiedAt: NOW - 2 * HOUR }), {
    now: NOW,
    minimumAgeMs: 24 * HOUR,
  });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /newer than the age threshold/);
});

test("treats an unreadable age as active rather than guessing it is old", () => {
  const verdict = classifyArtefact(cache({ modifiedAt: null }), { now: NOW });
  assert.equal(verdict.sweep, false);
  assert.match(verdict.reason, /age could not be read/);
});

test("the plan reports every refusal with the rule that caused it", () => {
  const { plan, skipped } = planArtefactSweep(
    [
      cache(),
      cache({ path: "b", dirty: true }),
      cache({ path: "c", landed: false }),
    ],
    { now: NOW },
  );
  assert.equal(plan.length, 1);
  assert.equal(skipped.length, 2);
  // A refused directory must never read as one the tool failed to notice.
  assert.ok(
    skipped.every((s) => typeof s.reason === "string" && s.reason.length > 0),
  );
});

test("the plan totals the bytes and files it will actually reclaim", () => {
  const { bytes, files } = planArtefactSweep(
    [
      cache({ bytes: 100, files: 2 }),
      cache({ path: "b", bytes: 50, files: 3 }),
      cache({ path: "c", dirty: true, bytes: 999, files: 99 }),
    ],
    { now: NOW },
  );
  assert.equal(bytes, 150);
  assert.equal(files, 5);
});

test("a disk budget takes the oldest caches and leaves recent builds warm", () => {
  const old = cache({
    path: "old",
    modifiedAt: NOW - 30 * 24 * HOUR,
    bytes: 60,
  });
  const recent = cache({
    path: "recent",
    modifiedAt: NOW - 8 * 24 * HOUR,
    bytes: 60,
  });
  const { plan } = planArtefactSweep([recent, old], {
    now: NOW,
    budgetBytes: 60,
  });
  assert.deepEqual(
    plan.map((p) => p.path),
    ["old"],
  );
});

test("a disk already under budget plans nothing, and says so", () => {
  const { plan, skipped } = planArtefactSweep([cache({ bytes: 10 })], {
    now: NOW,
    budgetBytes: 1000,
  });
  assert.equal(plan.length, 0);
  assert.match(skipped[0].reason, /already under budget/);
});

test("no artefact kind is the bare target directory", () => {
  // target/ also holds completion offers and scratch that nothing regenerates.
  // This is the structural half of that exclusion: if a kind is ever added back
  // as bare `target`, this fails rather than quietly sweeping them.
  for (const { rel } of ARTEFACT_KINDS) {
    assert.notEqual(rel, "target");
  }
  const swept = ARTEFACT_KINDS.map((k) => k.rel);
  assert.ok(!swept.includes("target/tmp"));
  assert.ok(!swept.includes("target/completion-offers"));
});
