// Generated by AI (UnitTest MCP)
//
// The board asks the ledger for everything, then asks again per finished item.
//
// Measured against the live ledger on 2026-07-31: one refresh rendered 75 rows
// of which 5 were actionable, and cost 70 MCP calls -- 69 of them fetching
// promotion detail for `materialized` designs, work that is done and that
// nobody is being asked to decide. The refresh is wired to a file watcher over
// docs/adr, so every ADR touch paid it again.
//
// `design_query` already names the right question. Its own description defines
// view=board as "actionable items: proposed ADRs awaiting a human decision plus
// accepted designs awaiting or retrying promotion" -- which is the board this
// view is named after. These tests pin the view and the fan-out, because the
// fan-out is invisible from the UI and would come back unnoticed.
import { beforeEach, describe, expect, it, vi } from "vitest";

const vscodeMock = vi.hoisted(() => ({
  showErrorMessage: vi.fn(),
  showInformationMessage: vi.fn(),
  showWarningMessage: vi.fn(),
  showInputBox: vi.fn(),
}));

vi.mock("vscode", () => ({ window: vscodeMock, workspace: { workspaceFolders: [] } }));

import { DesignBoardController } from "./designBoardController";

const design = (id: string, promotionStatus: string) => ({
  id,
  title: id,
  status: "accepted",
  promotion_status: promotionStatus,
  created_at: 1,
});

/** A ledger shaped like the live one: a few actionable, most long finished. */
const ledger = [
  design("design:0001", "pending"),
  design("design:0002", "pending"),
  ...Array.from({ length: 69 }, (_, index) => design(`design:done-${index}`, "materialized")),
];

function controller() {
  const calls: { name: string; args: Record<string, unknown> }[] = [];
  const callTool = vi.fn(async (name: string, args: Record<string, unknown>) => {
    calls.push({ name, args });
    if (name !== "design_query") return null;
    if (args.view === "ledger" && args.include_deferred) {
      return [
        {
          ...design("design:deferred", "not_required"),
          status: "proposed",
          deferred: { at: 2, by: "reviewer", reason: "not now" },
        },
      ];
    }
    if (args.view === "ledger") return ledger;
    // What the server actually returns for the actionable view.
    if (args.view === "board") return ledger.filter((d) => d.promotion_status === "pending");
    if (args.view === "promotion") return { design_id: args.id, objectives: [] };
    return null;
  });
  let includeDeferred = false;
  const provider = {
    update: vi.fn(),
    expand: vi.fn(),
    get includeDeferred() {
      return includeDeferred;
    },
    setIncludeDeferred: vi.fn((include: boolean) => {
      includeDeferred = include;
    }),
  };
  const instance = new DesignBoardController(
    { isReady: () => true, callTool } as never,
    provider as never,
    "session:v1:test",
    vi.fn(),
    vi.fn(),
    vi.fn(async () => undefined)
  );
  return { instance, calls, provider, callTool };
}

describe("DesignBoardController refresh", () => {
  beforeEach(() => vi.clearAllMocks());

  it("asks for the actionable designs, not the whole durable record", async () => {
    const { instance, calls } = controller();

    await instance.refresh();

    const views = calls.filter((c) => c.name === "design_query").map((c) => c.args.view);
    expect(views).toContain("board");
    expect(views).not.toContain("ledger");
  });

  /// The fan-out is the expensive half and the invisible one: one extra call
  /// per finished design, on a refresh a file watcher triggers.
  it("does not fetch promotion detail for work nobody is being asked to decide", async () => {
    const { instance, calls } = controller();

    await instance.refresh();

    const promotionCalls = calls.filter(
      (c) => c.name === "design_query" && c.args.view === "promotion"
    );
    expect(promotionCalls.length).toBe(0);
    expect(calls.length).toBeLessThanOrEqual(2);
  });

  it("still hands the rows it fetched to the view", async () => {
    const { instance, provider } = controller();

    await instance.refresh();

    expect(provider.update).toHaveBeenCalledTimes(1);
    const [designs] = provider.update.mock.calls[0];
    expect(designs).toHaveLength(2);
  });

  it("loads only deferred proposals when the reader asks to see them", async () => {
    const { instance, calls, provider } = controller();

    await instance.toggleDeferred();

    expect(provider.setIncludeDeferred).toHaveBeenCalledWith(true);
    expect(calls).toContainEqual({
      name: "design_query",
      args: { view: "ledger", status: "proposed", include_deferred: true },
    });
    const [designs] = provider.update.mock.calls.at(-1)!;
    expect(designs.map((entry: { id: string }) => entry.id)).toEqual([
      "design:0001",
      "design:0002",
      "design:deferred",
    ]);
  });

  it("expands the existing projection without another server read", () => {
    const { instance, provider, calls } = controller();

    instance.expand();

    expect(provider.expand).toHaveBeenCalledOnce();
    expect(calls).toEqual([]);
  });
});

describe("DesignBoardController deferral", () => {
  beforeEach(() => vi.clearAllMocks());

  const row = {
    design: {
      id: "design:0077",
      title: "A crowded board is not a decision",
      status: "proposed",
      promotion_status: "not_required",
      proposed_by: "planner",
      created_at: 1,
    },
  };

  it("defers without rewriting the ADR decision status", async () => {
    vscodeMock.showInputBox
      .mockResolvedValueOnce("Reviewer")
      .mockResolvedValueOnce("not this quarter");
    const { instance, calls } = controller();

    await instance.defer(row as never);

    expect(calls).toContainEqual({
      name: "design_decide",
      args: {
        id: "design:0077",
        decision: "defer",
        human: "Reviewer",
        reason: "not this quarter",
      },
    });
  });

  it("resumes through deferral's own inverse", async () => {
    vscodeMock.showInputBox
      .mockResolvedValueOnce("Reviewer")
      .mockResolvedValueOnce("back in scope");
    const { instance, calls } = controller();

    await instance.resume(row as never);

    expect(calls).toContainEqual({
      name: "design_decide",
      args: {
        id: "design:0077",
        decision: "resume",
        human: "Reviewer",
        reason: "back in scope",
      },
    });
  });
});

// A decision and the ADR file must move together. accept()/reject() used to
// call design_decide first and only then write the file, so when the file could
// not be resolved -- the ADR is on main but absent from the open checkout --
// the ledger had already accepted while the file still said Proposed. That
// drift is permanent and is the fingerprint ADR-0072 already carries. The fix
// resolves and stages the file write before the decision, so a decision that
// cannot be written is never recorded. These tests fail against the old order.
describe("DesignBoardController does not record a decision it cannot write to the ADR", () => {
  beforeEach(() => vi.clearAllMocks());

  const unresolvable = {
    design: {
      id: "design:0075",
      title: "ADR-0075",
      status: "proposed",
      promotion_status: "not_required",
      created_at: 1,
      adr_path: "docs/adr/0075-example.md",
    },
  };

  it("records no acceptance when the ADR file is not in the open workspace", async () => {
    // No workspace folders, so the file cannot be resolved.
    vscodeMock.showInputBox.mockResolvedValue("Reviewer");
    const { instance, calls } = controller();

    await instance.accept(unresolvable as never);

    expect(calls.filter((c) => c.name === "design_decide")).toHaveLength(0);
    // The failure names what to do, not only what is missing.
    expect(vscodeMock.showErrorMessage).toHaveBeenCalledWith(
      expect.stringContaining("open the checkout that contains it before deciding")
    );
  });

  it("records no rejection when the ADR file is not in the open workspace", async () => {
    vscodeMock.showInputBox.mockResolvedValue("Reviewer");
    const { instance, calls } = controller();

    await instance.reject(unresolvable as never);

    expect(calls.filter((c) => c.name === "design_decide")).toHaveLength(0);
    expect(vscodeMock.showErrorMessage).toHaveBeenCalledWith(
      expect.stringContaining("open the checkout that contains it before deciding")
    );
  });
});
