// Generated by AI (UnitTest MCP)
//
// Regression: `onFocus` boosted whatever repo-relative artifact id a focused
// file resolved to, without checking whether that file's repository is the
// one the extension is tracking. In a multi-root workspace, two unrelated
// repositories can each contain a file at the same relative path (e.g.
// `src/index.ts`), so focusing the file in the *other* root silently boosted
// the tracked repository's identically-named artifact -- attention recorded
// against the wrong node. `onSave`/`onDelete` already guarded on
// `repositoryWorktrees.contains(...)`; `onFocus` now does too.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("vscode", () => ({
  TreeItem: class TreeItem {
    label: string;
    constructor(label: string) {
      this.label = label;
    }
  },
  TreeItemCollapsibleState: { None: 0, Collapsed: 1, Expanded: 2 },
  ThemeIcon: class ThemeIcon {
    constructor(public id: string) {}
  },
  workspace: {
    asRelativePath: (uri: { fsPath: string }) => uri.fsPath.replace(/^\/workspace\//, ""),
  },
}));

import { onFocus } from "./extension";

function textDocument(fsPath: string, scheme = "file") {
  return { uri: { scheme, fsPath } } as any;
}

function fakeClient(ready = true) {
  return {
    isReady: () => ready,
    callTool: vi.fn().mockResolvedValue({}),
  } as any;
}

describe("onFocus", () => {
  let contains: ReturnType<typeof vi.fn>;
  let worktrees: { contains: ReturnType<typeof vi.fn> };

  beforeEach(() => {
    contains = vi.fn();
    worktrees = { contains };
  });

  it("does not boost a focused file outside the tracked repository worktree", async () => {
    // Same repo-relative path as the tracked repo would use, but this file
    // lives in an unrelated multi-root folder.
    contains.mockResolvedValue(false);
    const client = fakeClient();

    await onFocus(textDocument("/workspace/src/index.ts"), client, worktrees as any);

    expect(contains).toHaveBeenCalledWith("/workspace/src/index.ts");
    expect(client.callTool).not.toHaveBeenCalled();
  });

  it("boosts a focused file inside the tracked repository worktree", async () => {
    contains.mockResolvedValue(true);
    const client = fakeClient();

    await onFocus(textDocument("/workspace/src/index.ts"), client, worktrees as any);

    expect(client.callTool).toHaveBeenCalledWith("boost_entity", {
      id: expect.stringContaining("artifact:"),
    });
  });

  it("never checks worktree membership for a non-file scheme", async () => {
    const client = fakeClient();

    await onFocus(textDocument("/workspace/src/index.ts", "untitled"), client, worktrees as any);

    expect(contains).not.toHaveBeenCalled();
    expect(client.callTool).not.toHaveBeenCalled();
  });

  it("never checks worktree membership when the client is not ready", async () => {
    const client = fakeClient(false);

    await onFocus(textDocument("/workspace/src/index.ts"), client, worktrees as any);

    expect(contains).not.toHaveBeenCalled();
    expect(client.callTool).not.toHaveBeenCalled();
  });

  it("does not boost when no repository worktrees are being tracked", async () => {
    // Mirrors `onSave`/`onDelete`: an absent tracker (not yet resolved, or the
    // extension activated outside any repository) must fail closed, not open.
    const client = fakeClient();

    await onFocus(textDocument("/workspace/src/index.ts"), client, undefined);

    expect(client.callTool).not.toHaveBeenCalled();
  });
});
