// Generated by AI (UnitTest MCP)
import { beforeEach, describe, expect, it, vi } from "vitest";

const gitMock = vi.hoisted(() => {
  const repositoryHandlers: Record<string, () => void> = {};
  const apiHandlers: Record<string, (repository: any) => void> = {};
  const event = (handlers: Record<string, any>, name: string) => (handler: any) => {
    handlers[name] = handler;
    return { dispose: vi.fn() };
  };
  const state = {
    HEAD: { commit: "old-sha" },
    onDidChange: event(repositoryHandlers, "change"),
  };
  const repository = {
    rootUri: { toString: () => "file:///workspace" },
    state,
    onDidCommit: event(repositoryHandlers, "commit"),
    getCommit: vi.fn(async () => ({
      hash: "new-sha",
      message: "fix: captured commit",
      parents: ["old-sha"],
      commitDate: new Date("2026-07-22T00:00:00Z"),
    })),
    diffBetween: vi.fn(async () => [{ uri: { fsPath: "/workspace/src/app.ts" } }]),
  };
  const api = {
    repositories: [repository],
    onDidOpenRepository: event(apiHandlers, "open"),
    onDidCloseRepository: event(apiHandlers, "close"),
  };
  return { api, apiHandlers, repository, repositoryHandlers, state };
});

vi.mock("vscode", () => ({
  extensions: {
    getExtension: () => ({
      activate: async () => ({ enabled: true, getAPI: () => gitMock.api }),
    }),
  },
  workspace: {
    asRelativePath: (uri: { fsPath: string }) => uri.fsPath.replace("/workspace/", ""),
    getWorkspaceFolder: () => ({}),
    onDidChangeConfiguration: () => ({ dispose: vi.fn() }),
  },
}));

import { GitSensor } from "./gitSensor";

describe("GitSensor", () => {
  beforeEach(() => {
    gitMock.state.HEAD.commit = "old-sha";
    gitMock.repository.getCommit.mockClear();
    gitMock.repository.diffBetween.mockClear();
  });

  it("turns a repository commit event into commit evidence", async () => {
    const callTool = vi.fn().mockResolvedValue({});
    const sensor = new GitSensor({ isReady: () => true, callTool }, () => true, vi.fn(), vi.fn());
    await sensor.start();

    gitMock.state.HEAD.commit = "new-sha";
    gitMock.repositoryHandlers.commit();

    await vi.waitFor(() => expect(callTool).toHaveBeenCalledOnce());
    expect(callTool).toHaveBeenCalledWith("ingest_commit", {
      sha: "new-sha",
      message: "fix: captured commit",
      changed_files: ["src/app.ts"],
      timestamp: 1784678400,
    });
    sensor.dispose();
  });

  it("retries an unseen commit after the MCP client becomes ready", async () => {
    let ready = false;
    const callTool = vi.fn().mockResolvedValue({});
    const sensor = new GitSensor({ isReady: () => ready, callTool }, () => true, vi.fn(), vi.fn());
    await sensor.start();

    gitMock.state.HEAD.commit = "new-sha";
    gitMock.repositoryHandlers.commit();
    expect(callTool).not.toHaveBeenCalled();

    ready = true;
    gitMock.repositoryHandlers.change();
    await vi.waitFor(() => expect(callTool).toHaveBeenCalledOnce());
    sensor.dispose();
  });
});
