// Generated by AI (UnitTest MCP)
import { describe, expect, it, vi } from "vitest";

const vscodeMock = vi.hoisted(() => {
  const handlers: Record<string, (event?: any) => void> = {};
  const event = (name: string) => (handler: (event?: any) => void) => {
    handlers[name] = handler;
    return { dispose: vi.fn() };
  };
  return {
    handlers,
    window: {
      terminals: [{ shellIntegration: {} }],
      onDidStartTerminalShellExecution: event("start"),
      onDidEndTerminalShellExecution: event("end"),
      onDidChangeTerminalShellIntegration: event("integration"),
      onDidOpenTerminal: event("open"),
      onDidCloseTerminal: event("close"),
    },
  };
});

vi.mock("vscode", () => ({
  window: vscodeMock.window,
  workspace: {
    onDidChangeConfiguration: () => ({ dispose: vi.fn() }),
  },
}));

import { TerminalSensor } from "./terminalSensor";

describe("TerminalSensor", () => {
  it("turns shell start/end events into bounded, redacted execution evidence", async () => {
    const callTool = vi.fn().mockResolvedValue({});
    const health = vi.fn();
    let pathChanged: ((path: string) => void) | undefined;
    const sensor = new TerminalSensor(
      { isReady: () => true, callTool },
      "/workspace",
      {
        onDidChange: (handler) => {
          pathChanged = handler;
          return { dispose: vi.fn() };
        },
      },
      () => ({
        enabled: true,
        captureOutput: true,
        maxOutputChars: 256,
        maxChangedFiles: 200,
        excludedPathPrefixes: [],
      }),
      vi.fn(),
      health
    );
    const execution = {
      commandLine: { value: "npm test", confidence: 2, isTrusted: true },
      cwd: { scheme: "file", fsPath: "/workspace" },
      async *read() {
        yield "failed token=secret-value";
      },
    };

    vscodeMock.handlers.start({ execution });
    pathChanged?.("src/changed.ts");
    vscodeMock.handlers.end({ execution, exitCode: 1 });

    await vi.waitFor(() => expect(callTool).toHaveBeenCalledOnce());
    expect(callTool).toHaveBeenCalledWith(
      "ingest_execution",
      expect.objectContaining({
        command: "npm test",
        exit_code: 1,
        output: "failed token=[REDACTED]",
        changed_files: ["src/changed.ts"],
      })
    );
    sensor.dispose();
  });
});
