// Generated by AI (UnitTest MCP)
import * as path from "path";

import { describe, expect, it } from "vitest";

import {
  boardRows,
  conformanceDiagnostic,
  evidenceRequestForTask,
  filterChangedPaths,
  formatLogLine,
  formatTaskEvidence,
  healthSummary,
  logLines,
  parseToolResult,
  redactTerminalOutput,
  resolveBinaryPath,
  resolveServerPath,
  shouldCaptureCommand,
  telemetryDashboard,
  TelemetrySnapshot,
  toArtifactId,
} from "./util";

const SNAPSHOT: TelemetrySnapshot = {
  total_events: 10,
  total_errors: 2,
  by_name: [
    { name: "recall", calls: 6, errors: 2, total_ms: 300, min_ms: 20, max_ms: 90, avg_ms: 50 },
    { name: "graph_stats", calls: 4, errors: 0, total_ms: 40, min_ms: 5, max_ms: 20, avg_ms: 10 },
  ],
  recent: [
    { ts: 1_700_000_005, kind: "tool_call", name: "recall", outcome: "error", duration_ms: 90 },
    { ts: 1_700_000_000, kind: "tool_call", name: "graph_stats", outcome: "ok", duration_ms: 5 },
  ],
};

describe("healthSummary", () => {
  it("reports both planes and both passive sensors in a stable order", () => {
    expect(
      healthSummary("memory connected", "intent unavailable", "terminal active", "Git off")
    ).toBe("memory connected · intent unavailable · terminal active · Git off");
  });
});

describe("toArtifactId", () => {
  it("normalises backslashes to forward slashes", () => {
    expect(toArtifactId("src\\auth.ts")).toBe("artifact:src/auth.ts");
  });

  it("leaves posix paths unchanged", () => {
    expect(toArtifactId("src/auth.ts")).toBe("artifact:src/auth.ts");
  });
});

describe("parseToolResult", () => {
  it("parses JSON from the first text content block", () => {
    const result = { content: [{ type: "text", text: '{"nodes":2}' }] };
    expect(parseToolResult(result)).toEqual({ nodes: 2 });
  });

  it("returns the raw text when it is not JSON", () => {
    const result = { content: [{ type: "text", text: "not json" }] };
    expect(parseToolResult(result)).toBe("not json");
  });

  it("returns the whole result when there is no text block", () => {
    const result = { content: [] };
    expect(parseToolResult(result)).toBe(result);
  });
});

describe("resolveServerPath", () => {
  it("honours an explicit non-default configured path", () => {
    expect(resolveServerPath("/custom/mindleak-mcp", "/ws", { exists: () => true })).toBe(
      "/custom/mindleak-mcp"
    );
  });

  it("prefers a packaged server over a workspace build", () => {
    const resolved = resolveServerPath("mindleak-mcp", "/ws", {
      extensionPath: "/extension",
      platform: "linux",
      exists: (candidate) =>
        candidate === path.join("/extension", "bin", "mindleak-mcp") ||
        candidate === path.join("/ws", "target", "release", "mindleak-mcp"),
    });

    expect(resolved).toBe(path.join("/extension", "bin", "mindleak-mcp"));
  });

  it("uses a workspace build when the packaged server is absent", () => {
    const resolved = resolveServerPath("mindleak-mcp", "/ws", {
      extensionPath: "/extension",
      platform: "linux",
      exists: (candidate) => candidate === path.join("/ws", "target", "release", "mindleak-mcp"),
    });

    expect(resolved).toBe(path.join("/ws", "target", "release", "mindleak-mcp"));
  });

  it("prefers a release build when it exists (win32)", () => {
    const resolved = resolveServerPath("mindleak-mcp", "C:/ws", {
      platform: "win32",
      exists: (p) => p.includes("release"),
    });
    expect(resolved).toContain("release");
    expect(resolved).toContain("mindleak-mcp.exe");
  });

  it("falls back to debug when release is absent", () => {
    const resolved = resolveServerPath("mindleak-mcp", "/ws", {
      platform: "linux",
      exists: (p) => p.includes("debug"),
    });
    expect(resolved).toContain("debug");
    expect(resolved.endsWith("mindleak-mcp")).toBe(true);
  });

  it("falls back to the bare command when no build is found", () => {
    expect(resolveServerPath("mindleak-mcp", "/ws", { exists: () => false })).toBe("mindleak-mcp");
  });
});

describe("resolveBinaryPath", () => {
  it("resolves a workspace lodestar build (linux)", () => {
    const resolved = resolveBinaryPath("lodestar-mcp", "/ws", "lodestar-mcp", {
      platform: "linux",
      exists: (p) => p.includes("release"),
    });
    expect(resolved).toContain("release");
    expect(resolved.endsWith("lodestar-mcp")).toBe(true);
  });

  it("honours an explicit non-default path", () => {
    expect(
      resolveBinaryPath("/opt/lodestar-mcp", "/ws", "lodestar-mcp", { exists: () => true })
    ).toBe("/opt/lodestar-mcp");
  });
});

describe("boardRows", () => {
  it("orders by lifecycle and formats the owner", () => {
    const rows = boardRows([
      { id: "t1", goal_id: "g", title: "done thing", status: "done" },
      { id: "t2", goal_id: "g", title: "mine", status: "claimed", owner: "alice" },
    ]);
    expect(rows[0].label).toBe("mine");
    expect(rows[0].description).toBe("claimed \u00b7 alice");
    expect(rows[1].status).toBe("done");
  });
});

describe("conformanceDiagnostic", () => {
  it("returns null when aligned", () => {
    expect(conformanceDiagnostic({ verdict: "aligned", findings: [] })).toBeNull();
  });

  it("maps violation to error and drift to warning", () => {
    expect(conformanceDiagnostic({ verdict: "violation", findings: ["x"] })?.severity).toBe(
      "error"
    );
    expect(conformanceDiagnostic({ verdict: "drift", findings: [] })?.severity).toBe("warning");
  });
});

describe("formatTaskEvidence", () => {
  const record = (over = {}) => ({
    id: 1,
    task_id: "task:x",
    evidence: JSON.stringify({
      summary: "changed auth",
      changed_node_ids: ["artifact:src/auth.rs"],
      failed_node_ids: ["artifact:src/auth.test.rs"],
      execution_ids: ["execution:1"],
      commit_ids: ["intent:abc123"],
    }),
    verdict: "aligned",
    findings: "evidence covers task goal",
    checked_at: 1_700_000_000,
    ...over,
  });

  it("returns null when there is no recorded evidence", () => {
    expect(formatTaskEvidence([])).toBeNull();
    expect(formatTaskEvidence(undefined as never)).toBeNull();
  });

  it("renders the most recent record with parsed evidence fields", () => {
    const markdown = formatTaskEvidence([record()], "Harden auth") ?? "";
    expect(markdown).toContain("# Conformance evidence: Harden auth");
    expect(markdown).toContain("**Verdict:** aligned");
    expect(markdown).toContain("**Summary:** changed auth");
    expect(markdown).toContain("**Changed nodes:** artifact:src/auth.rs");
    expect(markdown).toContain("**Failed nodes:** artifact:src/auth.test.rs");
    expect(markdown).toContain("**Executions:** execution:1");
    expect(markdown).toContain("**Commits:** intent:abc123");
    expect(markdown).toContain("**Findings:** evidence covers task goal");
  });

  it("uses the latest record and lists prior checks in order", () => {
    const markdown =
      formatTaskEvidence([
        record({ id: 1, verdict: "drift", findings: "wrong goal", checked_at: 1_700_000_000 }),
        record({ id: 2, verdict: "aligned", checked_at: 1_700_000_500 }),
      ]) ?? "";
    expect(markdown).toContain("**Verdict:** aligned");
    expect(markdown).toContain("## Prior checks");
    expect(markdown).toContain("**drift** — wrong goal");
  });

  it("survives malformed evidence json without throwing", () => {
    const markdown = formatTaskEvidence([record({ evidence: "{not json" })]) ?? "";
    expect(markdown).toContain("**Verdict:** aligned");
    expect(markdown).not.toContain("**Changed nodes:**");
  });
});

describe("evidenceRequestForTask", () => {
  it("uses the owner and stable claim window", () => {
    expect(
      evidenceRequestForTask(
        {
          id: "task:auth",
          goal_id: "goal:auth",
          title: "Harden auth",
          status: "claimed",
          owner: "agent-a",
          claim_started_at: 100,
        },
        "fallback",
        150
      )
    ).toEqual({
      task_id: "task:auth",
      agent_id: "agent-a",
      started_at: 100,
      ended_at: 150,
    });
  });

  it("rejects an unclaimed task or missing claim window", () => {
    expect(() =>
      evidenceRequestForTask(
        { id: "task:x", goal_id: "goal:x", title: "x", status: "open" },
        "agent-a",
        150
      )
    ).toThrow("not claimed");
    expect(() =>
      evidenceRequestForTask(
        { id: "task:x", goal_id: "goal:x", title: "x", status: "claimed" },
        "agent-a",
        150
      )
    ).toThrow("no claim start");
  });
});

describe("terminal capture privacy", () => {
  it("suppresses likely secret-bearing and low-confidence commands", () => {
    expect(shouldCaptureCommand("npm test", 2)).toBe(true);
    expect(shouldCaptureCommand("az login", 2)).toBe(false);
    expect(shouldCaptureCommand("read -s PASSWORD", 2)).toBe(false);
    expect(shouldCaptureCommand("npm test", 0)).toBe(false);
  });

  it("strips terminal control sequences, redacts secrets, and bounds output", () => {
    const output = redactTerminalOutput(
      "\u001b[31mfailed\u001b[0m token=abc123 Authorization: Bearer secret-value",
      48
    );
    expect(output).not.toContain("\u001b");
    expect(output).not.toContain("abc123");
    expect(output).not.toContain("secret-value");
    expect(output.length).toBeLessThanOrEqual(48);
  });
});

describe("workspace change filtering", () => {
  it("filters configured workspace-relative path prefixes", () => {
    expect(
      filterChangedPaths(["src/z.ts", "src/a.ts", "generated/out.ts"], ["generated"], 1)
    ).toEqual(["src/a.ts"]);
  });
});

describe("telemetryDashboard", () => {
  it("derives success/error rates, weighted latency, and sorted tool rows", () => {
    const dashboard = telemetryDashboard(SNAPSHOT, { nodes: 42, active_edges: 17 });
    expect(dashboard.nodes).toBe(42);
    expect(dashboard.activeEdges).toBe(17);
    expect(dashboard.totalEvents).toBe(10);
    expect(dashboard.totalErrors).toBe(2);
    expect(dashboard.successRatePct).toBe(80);
    expect(dashboard.errorRatePct).toBe(20);
    // weighted: (300 + 40) / (6 + 4) = 34
    expect(dashboard.avgLatencyMs).toBe(34);
    expect(dashboard.tools.map((t) => t.name)).toEqual(["recall", "graph_stats"]);
    expect(dashboard.tools[0]).toMatchObject({
      calls: 6,
      errors: 2,
      errorRatePct: 33.3,
      avgMs: 50,
    });
  });

  it("reports a clean 100% success readout when nothing has run yet", () => {
    const dashboard = telemetryDashboard(undefined, undefined);
    expect(dashboard).toMatchObject({
      nodes: 0,
      activeEdges: 0,
      totalEvents: 0,
      totalErrors: 0,
      successRatePct: 100,
      errorRatePct: 0,
      avgLatencyMs: 0,
      tools: [],
    });
  });
});

describe("formatLogLine", () => {
  it("renders a deterministic UTC line with outcome, kind:name, and duration", () => {
    expect(
      formatLogLine({
        ts: 1_700_000_000,
        kind: "tool_call",
        name: "recall",
        outcome: "ok",
        duration_ms: 12,
      })
    ).toBe("22:13:20 ok tool_call:recall 12ms");
  });

  it("omits duration when it is absent", () => {
    expect(
      formatLogLine({ ts: 1_700_000_000, kind: "maintenance", name: "prune", outcome: "ok" })
    ).toBe("22:13:20 ok maintenance:prune");
  });
});

describe("logLines", () => {
  it("returns newest-first formatted lines when live", () => {
    expect(logLines(SNAPSHOT, true)).toEqual([
      "22:13:25 error tool_call:recall 90ms",
      "22:13:20 ok tool_call:graph_stats 5ms",
    ]);
  });

  it("returns nothing when live logging is off", () => {
    expect(logLines(SNAPSHOT, false)).toEqual([]);
  });

  it("caps the number of lines", () => {
    expect(logLines(SNAPSHOT, true, 1)).toEqual(["22:13:25 error tool_call:recall 90ms"]);
  });
});
