// Generated by AI (UnitTest MCP)
//! Tenant-scoped Fleet read models for the Bridge (ADR-0095).
//!
//! Fleet rows are derived from active enrollment receipts and the graph
//! projection's freshness state. This module is read-only: neither browser
//! views nor their API may change enrolment, claims, or ledger records.

use std::collections::HashMap;
use std::time::SystemTime;

use tokio_postgres::{Client, NoTls};

use crate::signing_keys::{self, EnvelopeBinding, KeyResolution, SigningKeyError};

const ENROLLMENT_MIGRATION: &str = include_str!("../migrations/0003_enrollment.sql");
const PROJECTION_MIGRATION: &str = include_str!("../migrations/0002_projection.sql");
const LEDGER_MIGRATION: &str = include_str!("../migrations/0001_ledger.sql");
const CLAIM_MIGRATION: &str = include_str!("../migrations/0005_claim_delegation.sql");
const SIGNING_KEYS_MIGRATION: &str = include_str!("../migrations/0004_signing_keys.sql");

/// One repository represented in a tenant's Fleet view.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FleetRepository {
    pub repository_id: String,
    pub active_node_count: i64,
    pub last_activated_at: SystemTime,
    pub ledger_stream_position: i64,
    pub projection_stream_position: Option<i64>,
    pub projection_updated_at: Option<SystemTime>,
    pub freshness: RepositoryFreshness,
}

/// Whether a repository's graph projection has caught up with its ledger,
/// as read by the Bridge (ADR-0095 decision 6: "a rebuilding or lagging
/// projection is presented as such" rather than silently reported as
/// current). Distinct from [`crate::projection::ProjectionFreshness`], which
/// is the raw `(stream_position, projected_at)` pair the projector itself
/// reads; this type is the Bridge's classification of that pair against the
/// ledger head.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RepositoryFreshness {
    /// The repository has an active enrollment but has never produced a
    /// projection.
    NeverProjected,
    /// The projection exists but has not caught up with the ledger's current
    /// stream position.
    Lagging,
    /// The projection's stream position matches the ledger head.
    Fresh,
}

/// Classify a projection's currency against the ledger head (ADR-0095
/// decision 6), shared by every read that reports freshness so the Fleet
/// list and a single repository's detail can never disagree about what
/// "lagging" means. `pub(crate)` so the Readiness rollup classifies the
/// exact same way rather than inventing a second judgment.
pub(crate) fn classify_freshness(
    ledger_stream_position: i64,
    projection_stream_position: Option<i64>,
) -> RepositoryFreshness {
    match projection_stream_position {
        None => RepositoryFreshness::NeverProjected,
        Some(projected) if projected < ledger_stream_position => RepositoryFreshness::Lagging,
        Some(_) => RepositoryFreshness::Fresh,
    }
}

/// One repository's coordination, ledger, and projection state (ADR-0095
/// decision 4's repository detail resource).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepositoryDetail {
    pub repository_id: String,
    pub active_node_count: i64,
    pub last_activated_at: SystemTime,
    pub ledger_stream_position: i64,
    pub projection_stream_position: Option<i64>,
    pub projection_updated_at: Option<SystemTime>,
    pub freshness: RepositoryFreshness,
}

/// One accepted ledger record surfaced on a repository's timeline (ADR-0095
/// decision 4's timeline resource). Rejections are not persisted anywhere the
/// Bridge can read (ADR-0086), so a timeline names only what was accepted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TimelineEvent {
    pub stream_position: i64,
    pub occurred_at: SystemTime,
    pub payload_type: String,
    pub producer_id: String,
    pub signing_key_id: Option<String>,
    /// The signing key's status judged as of now, not as of when this record
    /// was accepted (ADR-0084 decision 12: an existing receipt "retain[s]
    /// the key status known at acceptance and gain[s] a visible
    /// later-compromise annotation"). The record above never changes; only
    /// this derived field can move, e.g. from `Resolved` to `Revoked`, as the
    /// key's own lifecycle changes. `None` when the record carries no
    /// signing key at all (e.g. `unverified_attribution` provenance).
    pub key_status: Option<KeyResolution>,
}

/// One live delegated claim in a repository's Bridge Work view.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActiveWorkItem {
    pub task_id: String,
    pub owner_id: String,
    pub branch: String,
    pub lease_expires_at: SystemTime,
    pub paths: Vec<String>,
    pub symbols: Vec<String>,
}

/// One live delegated claim anywhere in a tenant's fleet (ADR-0105 decision
/// 5's Agents/Work control room). Unlike `ActiveWorkItem`, which is already
/// scoped to a repository the caller named, this carries its own
/// `repository_id` because the query spans every repository the tenant has
/// enrolled -- the "who is working on what, right now, across the whole
/// fleet" view an operator needs without visiting each repository in turn.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FleetWorkItem {
    pub repository_id: String,
    pub task_id: String,
    pub owner_id: String,
    pub branch: String,
    pub lease_expires_at: SystemTime,
    pub paths: Vec<String>,
    pub symbols: Vec<String>,
}

/// One enrolled node's signing key, judged as of now rather than as of some
/// past envelope's acceptance -- the Bridge repository detail resource that
/// answers "is this repository's coordination about to lose its signer"
/// before it actually does.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SigningKeyStatus {
    pub signing_key_id: String,
    pub node_id: String,
    pub public_key_fingerprint: String,
    pub status: KeyResolution,
    pub expires_at: Option<SystemTime>,
}

/// Read-only access to Fleet summaries derived from Ackplane's accepted state.
pub struct FleetStore {
    client: Client,
}

/// Server-side filters for [`FleetStore::repositories`] (ADR-0112). Each
/// field is validated against its own allow-list by the Bridge handler, not
/// here -- this type only carries already-validated, opaque values through
/// to bound query parameters; an unrecognised `freshness`/`coordination`
/// value would otherwise match no row rather than erroring, which is why
/// the handler rejects it before it ever reaches this struct.
#[derive(Debug, Clone, Copy, Default)]
pub struct FleetFilter<'a> {
    /// Case-insensitive substring match on `repository_id`. Literal `%`/`_`
    /// must already be escaped by the caller (see `escape_like_pattern`)
    /// before it reaches here, so a repository named `my_repo` is not
    /// treated as a one-character wildcard match.
    pub q: Option<&'a str>,
    /// One of `"never_projected"`, `"lagging"`, `"fresh"`, or `None` for no
    /// freshness filter.
    pub freshness: Option<&'a str>,
    /// One of `"active"`, `"none"`, or `None` for no coordination filter.
    pub coordination: Option<&'a str>,
}

/// The column [`FleetStore::repositories`] orders by (ADR-0112). Deliberately
/// a small, closed enum rather than an arbitrary string: each variant maps to
/// exactly one compiled-in `ORDER BY` fragment, so a sort request can never
/// become part of the query's own text.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FleetSortField {
    RepositoryId,
    ActiveNodeCount,
    LastActivatedAt,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SortDirection {
    Ascending,
    Descending,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FleetSort {
    pub field: FleetSortField,
    pub direction: SortDirection,
}

impl FleetSort {
    /// The default sort when a caller asks for none: alphabetical by
    /// repository id, matching every existing Fleet response before this ADR.
    pub fn default_order() -> Self {
        Self {
            field: FleetSortField::RepositoryId,
            direction: SortDirection::Ascending,
        }
    }

    /// The literal `ORDER BY` fragment for this sort, always including
    /// `repository_id` as a tiebreaker so paging stays stable across pages
    /// when the primary sort column has duplicate values (e.g. two
    /// repositories with the same `active_node_count`).
    fn order_by_clause(self) -> &'static str {
        use FleetSortField::{ActiveNodeCount, LastActivatedAt, RepositoryId};
        use SortDirection::{Ascending, Descending};
        match (self.field, self.direction) {
            (RepositoryId, Ascending) => "ORDER BY request.repository_id ASC",
            (RepositoryId, Descending) => "ORDER BY request.repository_id DESC",
            (ActiveNodeCount, Ascending) => "ORDER BY count(*) ASC, request.repository_id ASC",
            (ActiveNodeCount, Descending) => "ORDER BY count(*) DESC, request.repository_id ASC",
            (LastActivatedAt, Ascending) => {
                "ORDER BY max(receipt.activated_at) ASC, request.repository_id ASC"
            }
            (LastActivatedAt, Descending) => {
                "ORDER BY max(receipt.activated_at) DESC, request.repository_id ASC"
            }
        }
    }
}

/// One page of the Fleet list (ADR-0112). `total` is the count matching
/// `q`/`freshness`/`coordination` across every page, not just this one, so a
/// caller can compute how many pages exist without a second round trip.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FleetPage {
    pub repositories: Vec<FleetRepository>,
    pub total: i64,
}

/// Server-side filters for [`FleetStore::fleet_work`] (ADR-0105 decision 5).
/// Same opaque-value contract as [`FleetFilter`]: values are validated
/// against their own allow-list by the Bridge handler, not here.
#[derive(Debug, Clone, Copy, Default)]
pub struct FleetWorkFilter<'a> {
    /// Case-insensitive substring match on `repository_id`. Literal `%`/`_`
    /// must already be escaped by the caller (see `escape_like_pattern`).
    pub repository_id: Option<&'a str>,
    /// Case-insensitive substring match on `owner_id` (the claiming agent).
    /// Same escaping requirement as `repository_id`.
    pub owner_id: Option<&'a str>,
}

/// The column [`FleetStore::fleet_work`] orders by (ADR-0105 decision 5).
/// A small, closed enum for the same reason as [`FleetSortField`]: each
/// variant maps to exactly one compiled-in `ORDER BY` fragment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FleetWorkSortField {
    LeaseExpiresAt,
    RepositoryId,
    OwnerId,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FleetWorkSort {
    pub field: FleetWorkSortField,
    pub direction: SortDirection,
}

impl FleetWorkSort {
    /// The default sort when a caller asks for none: soonest-expiring lease
    /// first, so an operator's first look lands on the work most likely to
    /// need attention.
    pub fn default_order() -> Self {
        Self {
            field: FleetWorkSortField::LeaseExpiresAt,
            direction: SortDirection::Ascending,
        }
    }

    /// The literal `ORDER BY` fragment for this sort, always including
    /// `task_id` as a tiebreaker so paging stays stable across pages when
    /// the primary sort column has duplicate values.
    fn order_by_clause(self) -> &'static str {
        use FleetWorkSortField::{LeaseExpiresAt, OwnerId, RepositoryId};
        use SortDirection::{Ascending, Descending};
        match (self.field, self.direction) {
            (LeaseExpiresAt, Ascending) => "ORDER BY lease_expires_at ASC, task_id ASC",
            (LeaseExpiresAt, Descending) => "ORDER BY lease_expires_at DESC, task_id ASC",
            (RepositoryId, Ascending) => "ORDER BY repository_id ASC, task_id ASC",
            (RepositoryId, Descending) => "ORDER BY repository_id DESC, task_id ASC",
            (OwnerId, Ascending) => "ORDER BY owner_id ASC, task_id ASC",
            (OwnerId, Descending) => "ORDER BY owner_id DESC, task_id ASC",
        }
    }
}

/// One page of the fleet-wide Agents/Work view (ADR-0105 decision 5).
/// `total` is the count matching `repository_id`/`owner_id` across every
/// page, not just this one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FleetWorkPage {
    pub items: Vec<FleetWorkItem>,
    pub total: i64,
}

/// Escape `%`, `_`, and `\\` in `input` for safe use inside a `LIKE`/`ILIKE`
/// pattern with `ESCAPE '\\'`, so a caller's literal wildcard-looking
/// characters (most commonly `_` in a repository name) match themselves
/// rather than acting as pattern metacharacters.
pub fn escape_like_pattern(input: &str) -> String {
    input
        .replace('\\', "\\\\")
        .replace('%', "\\%")
        .replace('_', "\\_")
}

impl FleetStore {
    /// Connect to the Ackplane read models needed for Fleet queries.
    pub async fn connect(database_url: &str) -> Result<Self, tokio_postgres::Error> {
        let (mut client, connection) = tokio_postgres::connect(database_url, NoTls).await?;
        tokio::spawn(async move {
            if let Err(error) = connection.await {
                tracing::error!(%error, "ackplane fleet connection closed with an error");
            }
        });
        crate::migration_lock::migrate_locked(
            &mut client,
            crate::migration_lock::key::ENROLLMENT,
            ENROLLMENT_MIGRATION,
        )
        .await?;
        crate::migration_lock::migrate_locked(
            &mut client,
            crate::migration_lock::key::PROJECTION,
            PROJECTION_MIGRATION,
        )
        .await?;
        crate::migration_lock::migrate_locked(
            &mut client,
            crate::migration_lock::key::LEDGER,
            LEDGER_MIGRATION,
        )
        .await?;
        crate::migration_lock::migrate_locked(
            &mut client,
            crate::migration_lock::key::CLAIM_DELEGATION,
            CLAIM_MIGRATION,
        )
        .await?;
        crate::migration_lock::migrate_locked(
            &mut client,
            crate::migration_lock::key::SIGNING_KEYS,
            SIGNING_KEYS_MIGRATION,
        )
        .await?;
        Ok(Self { client })
    }

    /// Return one page of repositories with an active enrollment receipt in
    /// one tenant, filtered, sorted, and paged server-side (ADR-0112).
    ///
    /// A missing projection state remains visible as `None`; it means the
    /// repository is enrolled but has not produced a graph projection yet.
    pub async fn repositories(
        &self,
        tenant_id: &str,
        filter: FleetFilter<'_>,
        sort: FleetSort,
        page: i64,
        page_size: i64,
    ) -> Result<FleetPage, tokio_postgres::Error> {
        let offset = (page - 1) * page_size;
        let query = format!(
            "SELECT request.repository_id, count(*)::BIGINT, max(receipt.activated_at), \
                    COALESCE(head.position, 0), state.stream_position, state.projected_at, \
                    COUNT(*) OVER()::BIGINT \
             FROM enrollment_requests AS request \
             INNER JOIN enrollment_receipts AS receipt \
                ON receipt.tenant_id = request.tenant_id \
               AND receipt.repository_id = request.repository_id \
               AND receipt.request_id = request.request_id \
             LEFT JOIN projection_state AS state \
                ON state.tenant_id = request.tenant_id \
               AND state.repository_id = request.repository_id \
             LEFT JOIN stream_heads AS head \
                ON head.tenant_id = request.tenant_id \
               AND head.repository_id = request.repository_id \
             WHERE request.tenant_id = $1 \
               AND ($2::text IS NULL OR request.repository_id ILIKE '%' || $2 || '%' ESCAPE '\\') \
             GROUP BY request.repository_id, head.position, \
                      state.stream_position, state.projected_at \
             HAVING ($3::text IS NULL \
                     OR ($3 = 'never_projected' AND state.stream_position IS NULL) \
                     OR ($3 = 'lagging' AND state.stream_position IS NOT NULL \
                         AND state.stream_position < COALESCE(head.position, 0)) \
                     OR ($3 = 'fresh' AND state.stream_position IS NOT NULL \
                         AND state.stream_position >= COALESCE(head.position, 0))) \
                 AND ($4::text IS NULL \
                      OR ($4 = 'active' AND count(*) > 0) \
                      OR ($4 = 'none' AND count(*) = 0)) \
             {order_by} \
             LIMIT $5 OFFSET $6",
            order_by = sort.order_by_clause(),
        );
        let rows = self
            .client
            .query(
                &query,
                &[
                    &tenant_id,
                    &filter.q,
                    &filter.freshness,
                    &filter.coordination,
                    &page_size,
                    &offset,
                ],
            )
            .await?;

        let total = rows.first().map(|row| row.get::<_, i64>(6)).unwrap_or(0);
        let repositories = rows
            .into_iter()
            .map(|row| {
                let ledger_stream_position: i64 = row.get(3);
                let projection_stream_position: Option<i64> = row.get(4);
                FleetRepository {
                    repository_id: row.get(0),
                    active_node_count: row.get(1),
                    last_activated_at: row.get(2),
                    ledger_stream_position,
                    freshness: classify_freshness(
                        ledger_stream_position,
                        projection_stream_position,
                    ),
                    projection_stream_position,
                    projection_updated_at: row.get(5),
                }
            })
            .collect();

        Ok(FleetPage {
            repositories,
            total,
        })
    }

    /// One repository's coordination, ledger, and projection state, scoped to
    /// a tenant (ADR-0095 decision 4). `None` when the repository has no
    /// active enrollment receipt in that tenant — a caller that cannot see a
    /// repository must never distinguish "not enrolled" from "enrolled in a
    /// different tenant"; both read the same way here.
    pub async fn repository(
        &self,
        tenant_id: &str,
        repository_id: &str,
    ) -> Result<Option<RepositoryDetail>, tokio_postgres::Error> {
        let row = self
            .client
            .query_opt(
                "SELECT request.repository_id, count(*)::BIGINT, max(receipt.activated_at), \
                        COALESCE(head.position, 0), \
                        state.stream_position, state.projected_at \
                 FROM enrollment_requests AS request \
                 INNER JOIN enrollment_receipts AS receipt \
                    ON receipt.tenant_id = request.tenant_id \
                   AND receipt.repository_id = request.repository_id \
                   AND receipt.request_id = request.request_id \
                 LEFT JOIN projection_state AS state \
                    ON state.tenant_id = request.tenant_id \
                   AND state.repository_id = request.repository_id \
                 LEFT JOIN stream_heads AS head \
                    ON head.tenant_id = request.tenant_id \
                   AND head.repository_id = request.repository_id \
                 WHERE request.tenant_id = $1 AND request.repository_id = $2 \
                 GROUP BY request.repository_id, head.position, \
                          state.stream_position, state.projected_at",
                &[&tenant_id, &repository_id],
            )
            .await?;

        let Some(row) = row else {
            return Ok(None);
        };

        let ledger_stream_position: i64 = row.get(3);
        let projection_stream_position: Option<i64> = row.get(4);
        let freshness = classify_freshness(ledger_stream_position, projection_stream_position);

        Ok(Some(RepositoryDetail {
            repository_id: row.get(0),
            active_node_count: row.get(1),
            last_activated_at: row.get(2),
            ledger_stream_position,
            projection_stream_position,
            projection_updated_at: row.get(5),
            freshness,
        }))
    }

    /// A repository's most recent accepted ledger records, newest first
    /// (ADR-0095 decision 4's timeline resource). Only accepted records are
    /// ever persisted (ADR-0086), so this names accepted positions, never
    /// rejections.
    ///
    /// Each event's `key_status` is judged as of now via the same
    /// `signing_keys::judge` rule `FleetStore::signing_keys` uses (ADR-0084
    /// decision 12) -- one repository-wide key fetch, not one query per
    /// event, since a handful of enrolled keys typically sign every event in
    /// a bounded timeline page.
    pub async fn timeline(
        &self,
        tenant_id: &str,
        repository_id: &str,
        limit: i64,
    ) -> Result<Vec<TimelineEvent>, SigningKeyError> {
        let rows = self
            .client
            .query(
                "SELECT stream_position, occurred_at, payload_type, producer_id, signing_key_id \
                 FROM ledger_records \
                 WHERE tenant_id = $1 AND repository_id = $2 \
                 ORDER BY stream_position DESC \
                 LIMIT $3",
                &[&tenant_id, &repository_id, &limit],
            )
            .await?;

        let keys_by_id: HashMap<String, _> =
            signing_keys::for_repository(&self.client, tenant_id, repository_id)
                .await?
                .into_iter()
                .map(|lifecycle| (lifecycle.record.signing_key_id.clone(), lifecycle))
                .collect();
        let now = SystemTime::now();

        Ok(rows
            .into_iter()
            .map(|row| {
                let signing_key_id: Option<String> = row.get(4);
                let key_status = signing_key_id.as_deref().map(|signing_key_id| {
                    match keys_by_id.get(signing_key_id) {
                        Some(lifecycle) => {
                            let binding = EnvelopeBinding {
                                signing_key_id: &lifecycle.record.signing_key_id,
                                tenant_id: &lifecycle.record.tenant_id,
                                repository_id: &lifecycle.record.repository_id,
                                producer_id: &lifecycle.record.node_id,
                                accepted_at: now,
                            };
                            signing_keys::judge(lifecycle, &binding)
                        }
                        None => KeyResolution::Unknown,
                    }
                });
                TimelineEvent {
                    stream_position: row.get(0),
                    occurred_at: row.get(1),
                    payload_type: row.get(2),
                    producer_id: row.get(3),
                    signing_key_id,
                    key_status,
                }
            })
            .collect())
    }

    /// Active delegated work for one tenant-scoped repository, ordered by the
    /// lease that expires first. Expired claims remain in the authoritative
    /// ledger for audit but are not current work.
    pub async fn active_work(
        &self,
        tenant_id: &str,
        repository_id: &str,
        now: SystemTime,
        limit: i64,
    ) -> Result<Option<Vec<ActiveWorkItem>>, tokio_postgres::Error> {
        if self.repository(tenant_id, repository_id).await?.is_none() {
            return Ok(None);
        }
        let rows = self
            .client
            .query(
                "SELECT task_id, owner_id, branch, lease_expires_at, paths, symbols \
                 FROM delegated_claims \
                 WHERE tenant_id = $1 AND repository_id = $2 AND lease_expires_at > $3 \
                 ORDER BY lease_expires_at ASC, task_id ASC \
                 LIMIT $4",
                &[&tenant_id, &repository_id, &now, &limit],
            )
            .await?;

        Ok(Some(
            rows.into_iter()
                .map(|row| ActiveWorkItem {
                    task_id: row.get(0),
                    owner_id: row.get(1),
                    branch: row.get(2),
                    lease_expires_at: row.get(3),
                    paths: row.get(4),
                    symbols: row.get(5),
                })
                .collect(),
        ))
    }

    /// Every stranded (lease-expired) delegated claim for one tenant-scoped
    /// repository, most-recently-expired last -- the complement of
    /// `active_work`'s exclusion, and the list `recover` (ADR-0111) needs
    /// but nothing previously exposed. An operator could recover a claim
    /// only by already knowing its task id; this is how they find one.
    pub async fn stranded_claims(
        &self,
        tenant_id: &str,
        repository_id: &str,
        now: SystemTime,
        limit: i64,
    ) -> Result<Option<Vec<ActiveWorkItem>>, tokio_postgres::Error> {
        if self.repository(tenant_id, repository_id).await?.is_none() {
            return Ok(None);
        }
        let rows = self
            .client
            .query(
                "SELECT task_id, owner_id, branch, lease_expires_at, paths, symbols \
                 FROM delegated_claims \
                 WHERE tenant_id = $1 AND repository_id = $2 AND lease_expires_at <= $3 \
                 ORDER BY lease_expires_at ASC, task_id ASC \
                 LIMIT $4",
                &[&tenant_id, &repository_id, &now, &limit],
            )
            .await?;

        Ok(Some(
            rows.into_iter()
                .map(|row| ActiveWorkItem {
                    task_id: row.get(0),
                    owner_id: row.get(1),
                    branch: row.get(2),
                    lease_expires_at: row.get(3),
                    paths: row.get(4),
                    symbols: row.get(5),
                })
                .collect(),
        ))
    }

    /// One page of every live delegated claim across ALL of a tenant's
    /// repositories (ADR-0105 decision 5), filtered, sorted, and paged
    /// server-side -- the cross-repository "who is working on what, right
    /// now" view a Bridge operator needs without visiting each repository's
    /// own claims list individually. Same expired-claim exclusion rule as
    /// `active_work`: an expired claim remains in the ledger for audit but
    /// is not current work.
    pub async fn fleet_work(
        &self,
        tenant_id: &str,
        filter: FleetWorkFilter<'_>,
        sort: FleetWorkSort,
        page: i64,
        page_size: i64,
        now: SystemTime,
    ) -> Result<FleetWorkPage, tokio_postgres::Error> {
        let offset = (page - 1) * page_size;
        let query = format!(
            "SELECT repository_id, task_id, owner_id, branch, lease_expires_at, paths, symbols, \
                    COUNT(*) OVER()::BIGINT \
             FROM delegated_claims \
             WHERE tenant_id = $1 AND lease_expires_at > $2 \
               AND ($3::text IS NULL OR repository_id ILIKE '%' || $3 || '%' ESCAPE '\\') \
               AND ($4::text IS NULL OR owner_id ILIKE '%' || $4 || '%' ESCAPE '\\') \
             {order_by} \
             LIMIT $5 OFFSET $6",
            order_by = sort.order_by_clause(),
        );
        let rows = self
            .client
            .query(
                &query,
                &[
                    &tenant_id,
                    &now,
                    &filter.repository_id,
                    &filter.owner_id,
                    &page_size,
                    &offset,
                ],
            )
            .await?;

        let total = rows.first().map(|row| row.get::<_, i64>(7)).unwrap_or(0);
        let items = rows
            .into_iter()
            .map(|row| FleetWorkItem {
                repository_id: row.get(0),
                task_id: row.get(1),
                owner_id: row.get(2),
                branch: row.get(3),
                lease_expires_at: row.get(4),
                paths: row.get(5),
                symbols: row.get(6),
            })
            .collect();
        Ok(FleetWorkPage { items, total })
    }

    /// One delegated claim's current owner and scope, regardless of whether
    /// its lease has expired (unlike `active_work`, which excludes expired
    /// rows because it answers a different question - "what is current
    /// work"). This answers what a recovery decision needs: the exact owner
    /// of a claim that may already be stranded, so `ackplane-bridge` can pass
    /// it as `ClaimRecoverRequest::expected_owner` without asking the caller
    /// to supply (and possibly mis-type) it.
    pub async fn claim_owner(
        &self,
        tenant_id: &str,
        repository_id: &str,
        task_id: &str,
    ) -> Result<Option<ActiveWorkItem>, tokio_postgres::Error> {
        let row = self
            .client
            .query_opt(
                "SELECT task_id, owner_id, branch, lease_expires_at, paths, symbols \
                 FROM delegated_claims \
                 WHERE tenant_id = $1 AND repository_id = $2 AND task_id = $3",
                &[&tenant_id, &repository_id, &task_id],
            )
            .await?;

        Ok(row.map(|row| ActiveWorkItem {
            task_id: row.get(0),
            owner_id: row.get(1),
            branch: row.get(2),
            lease_expires_at: row.get(3),
            paths: row.get(4),
            symbols: row.get(5),
        }))
    }

    /// Every signing key this repository has ever enrolled, judged as of now.
    ///
    /// Reuses `signing_keys::judge` -- the same rule an accepted envelope is
    /// checked against -- with a binding built from each record's own
    /// identity, so it always matches by construction; only the lifecycle
    /// timestamps compared against `now` can move the answer. This is
    /// deliberately not a second judgment invented for a health view.
    pub async fn signing_keys(
        &self,
        tenant_id: &str,
        repository_id: &str,
    ) -> Result<Option<Vec<SigningKeyStatus>>, SigningKeyError> {
        if self.repository(tenant_id, repository_id).await?.is_none() {
            return Ok(None);
        }
        let now = SystemTime::now();
        let keys = signing_keys::for_repository(&self.client, tenant_id, repository_id).await?;
        Ok(Some(
            keys.into_iter()
                .map(|lifecycle| {
                    let binding = EnvelopeBinding {
                        signing_key_id: &lifecycle.record.signing_key_id,
                        tenant_id: &lifecycle.record.tenant_id,
                        repository_id: &lifecycle.record.repository_id,
                        producer_id: &lifecycle.record.node_id,
                        accepted_at: now,
                    };
                    let status = signing_keys::judge(&lifecycle, &binding);
                    let record = lifecycle.record;
                    SigningKeyStatus {
                        signing_key_id: record.signing_key_id,
                        node_id: record.node_id,
                        public_key_fingerprint: record.public_key_fingerprint,
                        status,
                        expires_at: record.expires_at,
                    }
                })
                .collect(),
        ))
    }
}

#[cfg(test)]
mod tests {
    use std::time::{Duration, SystemTime};

    use super::*;
    use crate::{
        claim_store::{ClaimLeaseRequest, ClaimStore},
        ledger::{DedupKey, EventEnvelope, LedgerStore, ProvenanceClass},
        projection::{Projector, StructuralFact},
        test_support::{enroll_and_activate, enroll_and_activate_in, uuid_ish},
    };

    #[tokio::test]
    async fn an_enrolled_repository_without_a_projection_remains_visible_in_fleet() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let page = fleet
            .repositories(
                &tenant_id,
                FleetFilter::default(),
                FleetSort::default_order(),
                1,
                20,
            )
            .await
            .expect("query fleet repositories");

        assert_eq!(page.repositories.len(), 1);
        assert_eq!(page.total, 1);
        let repository = &page.repositories[0];
        assert_eq!(repository.repository_id, repository_id);
        assert_eq!(repository.active_node_count, 1);
        assert_eq!(repository.projection_stream_position, None);
        assert_eq!(repository.projection_updated_at, None);
    }

    #[tokio::test]
    async fn a_repository_not_enrolled_in_the_tenant_is_invisible_to_repository_detail() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");

        // Right repository, wrong tenant: must read exactly like "not
        // enrolled", never like a cross-tenant peek.
        let wrong_tenant = fleet
            .repository(&format!("{tenant_id}-other"), &repository_id)
            .await
            .expect("query repository detail");
        assert!(wrong_tenant.is_none());

        // Right tenant, a repository id nobody ever enrolled.
        let never_enrolled = fleet
            .repository(&tenant_id, &format!("{repository_id}-other"))
            .await
            .expect("query repository detail");
        assert!(never_enrolled.is_none());
    }

    #[tokio::test]
    async fn repository_detail_reports_lagging_when_the_ledger_outruns_the_projection() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;

        let mut ledger = LedgerStore::connect(&database_url)
            .await
            .expect("connect ledger store");
        let envelope = EventEnvelope {
            key: DedupKey {
                tenant_id: tenant_id.clone(),
                repository_id: repository_id.clone(),
                producer_id: format!("fleet-producer-{unique_id}"),
                producer_sequence: 1,
            },
            payload: b"{}".to_vec(),
            payload_digest: vec![1, 2, 3],
            schema_version: "v1".to_string(),
            occurred_at: SystemTime::now(),
            payload_type: "structural_fact".to_string(),
            previous_envelope_digest: None,
            signing_key_id: None,
            signature: None,
            provenance: ProvenanceClass::EnrolledNode,
        };
        ledger.append(&envelope).await.expect("append envelope");

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let detail = fleet
            .repository(&tenant_id, &repository_id)
            .await
            .expect("query repository detail")
            .expect("repository is enrolled");

        assert_eq!(detail.ledger_stream_position, 1);
        assert_eq!(detail.projection_stream_position, None);
        assert_eq!(detail.freshness, RepositoryFreshness::NeverProjected);

        let timeline = fleet
            .timeline(&tenant_id, &repository_id, 50)
            .await
            .expect("query repository timeline");
        assert_eq!(timeline.len(), 1);
        assert_eq!(timeline[0].stream_position, 1);
        assert_eq!(timeline[0].payload_type, "structural_fact");
        assert_eq!(timeline[0].producer_id, envelope.key.producer_id);
    }

    #[tokio::test]
    async fn repository_detail_reports_fresh_once_the_projection_catches_up() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;

        let mut ledger = LedgerStore::connect(&database_url)
            .await
            .expect("connect ledger store");
        let fact = StructuralFact {
            node_id: format!("artifact:fleet-{unique_id}.rs"),
            node_type: "artifact".to_string(),
            label: format!("fleet-{unique_id}.rs"),
            edges: Vec::new(),
        };
        let envelope = EventEnvelope {
            key: DedupKey {
                tenant_id: tenant_id.clone(),
                repository_id: repository_id.clone(),
                producer_id: format!("fleet-producer-{unique_id}"),
                producer_sequence: 1,
            },
            payload: serde_json::to_vec(&fact).expect("encode structural fact"),
            payload_digest: vec![4, 5, 6],
            schema_version: "v1".to_string(),
            occurred_at: SystemTime::now(),
            payload_type: "structural_fact".to_string(),
            previous_envelope_digest: None,
            signing_key_id: None,
            signature: None,
            provenance: ProvenanceClass::EnrolledNode,
        };
        ledger.append(&envelope).await.expect("append envelope");

        let mut projector = Projector::connect(&database_url)
            .await
            .expect("connect projector");
        projector
            .rebuild(&tenant_id, &repository_id)
            .await
            .expect("rebuild projection");

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let detail = fleet
            .repository(&tenant_id, &repository_id)
            .await
            .expect("query repository detail")
            .expect("repository is enrolled");

        assert_eq!(detail.ledger_stream_position, 1);
        assert_eq!(detail.projection_stream_position, Some(1));
        assert_eq!(detail.freshness, RepositoryFreshness::Fresh);
    }

    #[tokio::test]
    async fn active_work_is_tenant_scoped_and_excludes_expired_claims() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;
        let now = SystemTime::UNIX_EPOCH + Duration::from_secs(10_000);
        let mut claims = ClaimStore::connect(&database_url)
            .await
            .expect("connect claim store");

        for (task_id, owner_id, lease_secs) in [
            ("task:expired", "agent:expired", 30),
            ("task:active", "agent:active", 120),
        ] {
            claims
                .delegate(
                    &ClaimLeaseRequest {
                        tenant_id: tenant_id.clone(),
                        repository_id: repository_id.clone(),
                        task_id: task_id.to_string(),
                        owner_id: owner_id.to_string(),
                        branch: format!("work/{task_id}"),
                        lease: Duration::from_secs(lease_secs),
                        paths: vec![format!("src/{task_id}.rs")],
                        symbols: vec![format!("symbol:{task_id}")],
                    },
                    now,
                )
                .await
                .expect("delegate claim");
        }

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let active = fleet
            .active_work(
                &tenant_id,
                &repository_id,
                now + Duration::from_secs(31),
                50,
            )
            .await
            .expect("query active work");

        assert_eq!(
            active.expect("repository is enrolled"),
            vec![ActiveWorkItem {
                task_id: "task:active".to_string(),
                owner_id: "agent:active".to_string(),
                branch: "work/task:active".to_string(),
                lease_expires_at: now + Duration::from_secs(120),
                paths: vec!["src/task:active.rs".to_string()],
                symbols: vec!["symbol:task:active".to_string()],
            }]
        );
        assert!(fleet
            .active_work(
                &format!("{tenant_id}-other"),
                &repository_id,
                now + Duration::from_secs(31),
                50,
            )
            .await
            .expect("query wrong tenant")
            .is_none());
    }

    #[tokio::test]
    async fn stranded_claims_is_tenant_scoped_and_excludes_active_claims() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;
        let now = SystemTime::UNIX_EPOCH + Duration::from_secs(10_000);
        let mut claims = ClaimStore::connect(&database_url)
            .await
            .expect("connect claim store");

        for (task_id, owner_id, lease_secs) in [
            ("task:expired", "agent:expired", 30),
            ("task:active", "agent:active", 120),
        ] {
            claims
                .delegate(
                    &ClaimLeaseRequest {
                        tenant_id: tenant_id.clone(),
                        repository_id: repository_id.clone(),
                        task_id: task_id.to_string(),
                        owner_id: owner_id.to_string(),
                        branch: format!("work/{task_id}"),
                        lease: Duration::from_secs(lease_secs),
                        paths: vec![format!("src/{task_id}.rs")],
                        symbols: vec![format!("symbol:{task_id}")],
                    },
                    now,
                )
                .await
                .expect("delegate claim");
        }

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let stranded = fleet
            .stranded_claims(
                &tenant_id,
                &repository_id,
                now + Duration::from_secs(31),
                50,
            )
            .await
            .expect("query stranded claims");

        assert_eq!(
            stranded.expect("repository is enrolled"),
            vec![ActiveWorkItem {
                task_id: "task:expired".to_string(),
                owner_id: "agent:expired".to_string(),
                branch: "work/task:expired".to_string(),
                lease_expires_at: now + Duration::from_secs(30),
                paths: vec!["src/task:expired.rs".to_string()],
                symbols: vec!["symbol:task:expired".to_string()],
            }]
        );
        assert!(fleet
            .stranded_claims(
                &format!("{tenant_id}-other"),
                &repository_id,
                now + Duration::from_secs(31),
                50,
            )
            .await
            .expect("query wrong tenant")
            .is_none());
    }

    #[tokio::test]
    async fn fleet_work_aggregates_active_claims_across_every_repository_in_the_tenant() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let tenant_id = format!("fleet-work-tenant-{unique_id}");
        let repository_ids = [
            format!("fleet-work-repo-{unique_id}-a"),
            format!("fleet-work-repo-{unique_id}-b"),
        ];
        for (index, repository_id) in repository_ids.iter().enumerate() {
            enroll_and_activate_in(
                &database_url,
                &tenant_id,
                repository_id,
                &format!("{unique_id}-work-{index}"),
            )
            .await;
        }

        let now = SystemTime::UNIX_EPOCH + Duration::from_secs(10_000);
        let mut claims = ClaimStore::connect(&database_url)
            .await
            .expect("connect claim store");
        for (repository_id, task_id, owner_id, lease_secs) in [
            (&repository_ids[0], "task:expired", "agent:expired", 30),
            (&repository_ids[0], "task:repo-a", "agent:a", 120),
            (&repository_ids[1], "task:repo-b", "agent:b", 180),
        ] {
            claims
                .delegate(
                    &ClaimLeaseRequest {
                        tenant_id: tenant_id.clone(),
                        repository_id: repository_id.clone(),
                        task_id: task_id.to_string(),
                        owner_id: owner_id.to_string(),
                        branch: format!("work/{task_id}"),
                        lease: Duration::from_secs(lease_secs),
                        paths: vec![format!("src/{task_id}.rs")],
                        symbols: vec![format!("symbol:{task_id}")],
                    },
                    now,
                )
                .await
                .expect("delegate claim");
        }

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let page = fleet
            .fleet_work(
                &tenant_id,
                FleetWorkFilter::default(),
                FleetWorkSort::default_order(),
                1,
                50,
                now + Duration::from_secs(31),
            )
            .await
            .expect("query fleet work");

        assert_eq!(page.total, 2);
        assert_eq!(
            page.items,
            vec![
                FleetWorkItem {
                    repository_id: repository_ids[0].clone(),
                    task_id: "task:repo-a".to_string(),
                    owner_id: "agent:a".to_string(),
                    branch: "work/task:repo-a".to_string(),
                    lease_expires_at: now + Duration::from_secs(120),
                    paths: vec!["src/task:repo-a.rs".to_string()],
                    symbols: vec!["symbol:task:repo-a".to_string()],
                },
                FleetWorkItem {
                    repository_id: repository_ids[1].clone(),
                    task_id: "task:repo-b".to_string(),
                    owner_id: "agent:b".to_string(),
                    branch: "work/task:repo-b".to_string(),
                    lease_expires_at: now + Duration::from_secs(180),
                    paths: vec!["src/task:repo-b.rs".to_string()],
                    symbols: vec!["symbol:task:repo-b".to_string()],
                },
            ]
        );

        // A different tenant must see none of this tenant's active work.
        let other_tenant = fleet
            .fleet_work(
                &format!("{tenant_id}-other"),
                FleetWorkFilter::default(),
                FleetWorkSort::default_order(),
                1,
                50,
                now + Duration::from_secs(31),
            )
            .await
            .expect("query other tenant");
        assert_eq!(other_tenant.total, 0);
        assert!(other_tenant.items.is_empty());
    }

    #[tokio::test]
    async fn fleet_work_filters_by_repository_id_and_owner_id_substring() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let tenant_id = format!("fleet-work-filter-tenant-{unique_id}");
        let repository_ids = [
            format!("fleet-work-filter-repo-{unique_id}-a"),
            format!("fleet-work-filter-repo-{unique_id}-b"),
        ];
        for (index, repository_id) in repository_ids.iter().enumerate() {
            enroll_and_activate_in(
                &database_url,
                &tenant_id,
                repository_id,
                &format!("{unique_id}-filter-{index}"),
            )
            .await;
        }

        let now = SystemTime::UNIX_EPOCH + Duration::from_secs(10_000);
        let mut claims = ClaimStore::connect(&database_url)
            .await
            .expect("connect claim store");
        for (repository_id, task_id, owner_id) in [
            (&repository_ids[0], "task:alpha", "agent:carter"),
            (&repository_ids[1], "task:beta", "agent:delta"),
        ] {
            claims
                .delegate(
                    &ClaimLeaseRequest {
                        tenant_id: tenant_id.clone(),
                        repository_id: repository_id.clone(),
                        task_id: task_id.to_string(),
                        owner_id: owner_id.to_string(),
                        branch: format!("work/{task_id}"),
                        lease: Duration::from_secs(120),
                        paths: vec![],
                        symbols: vec![],
                    },
                    now,
                )
                .await
                .expect("delegate claim");
        }

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");

        let by_repository = fleet
            .fleet_work(
                &tenant_id,
                FleetWorkFilter {
                    repository_id: Some(&escape_like_pattern(&format!("{unique_id}-a"))),
                    owner_id: None,
                },
                FleetWorkSort::default_order(),
                1,
                50,
                now,
            )
            .await
            .expect("query filtered by repository_id");
        assert_eq!(by_repository.total, 1);
        assert_eq!(by_repository.items[0].task_id, "task:alpha");

        let by_owner = fleet
            .fleet_work(
                &tenant_id,
                FleetWorkFilter {
                    repository_id: None,
                    owner_id: Some("delta"),
                },
                FleetWorkSort::default_order(),
                1,
                50,
                now,
            )
            .await
            .expect("query filtered by owner_id");
        assert_eq!(by_owner.total, 1);
        assert_eq!(by_owner.items[0].task_id, "task:beta");
    }

    #[tokio::test]
    async fn fleet_work_sort_direction_reverses_the_default_order() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let tenant_id = format!("fleet-work-sort-tenant-{unique_id}");
        let repository_id = format!("fleet-work-sort-repo-{unique_id}");
        enroll_and_activate_in(
            &database_url,
            &tenant_id,
            &repository_id,
            &unique_id.to_string(),
        )
        .await;

        let now = SystemTime::UNIX_EPOCH + Duration::from_secs(10_000);
        let mut claims = ClaimStore::connect(&database_url)
            .await
            .expect("connect claim store");
        for (task_id, lease_secs) in [("task:soonest", 60), ("task:latest", 300)] {
            claims
                .delegate(
                    &ClaimLeaseRequest {
                        tenant_id: tenant_id.clone(),
                        repository_id: repository_id.clone(),
                        task_id: task_id.to_string(),
                        owner_id: "agent:sort".to_string(),
                        branch: format!("work/{task_id}"),
                        lease: Duration::from_secs(lease_secs),
                        paths: vec![],
                        symbols: vec![],
                    },
                    now,
                )
                .await
                .expect("delegate claim");
        }

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");

        let ascending = fleet
            .fleet_work(
                &tenant_id,
                FleetWorkFilter::default(),
                FleetWorkSort::default_order(),
                1,
                50,
                now,
            )
            .await
            .expect("query ascending");
        assert_eq!(ascending.items[0].task_id, "task:soonest");
        assert_eq!(ascending.items[1].task_id, "task:latest");

        let descending = fleet
            .fleet_work(
                &tenant_id,
                FleetWorkFilter::default(),
                FleetWorkSort {
                    field: FleetWorkSortField::LeaseExpiresAt,
                    direction: SortDirection::Descending,
                },
                1,
                50,
                now,
            )
            .await
            .expect("query descending");
        assert_eq!(descending.items[0].task_id, "task:latest");
        assert_eq!(descending.items[1].task_id, "task:soonest");
    }

    #[tokio::test]
    async fn signing_keys_reports_none_for_a_repository_that_is_not_enrolled() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");

        // Right repository, wrong tenant: must read exactly like "not
        // enrolled", never like a cross-tenant peek at another tenant's keys.
        assert!(fleet
            .signing_keys(&format!("{tenant_id}-other"), &repository_id)
            .await
            .expect("query wrong tenant")
            .is_none());

        // Right tenant, a repository id nobody ever enrolled.
        assert!(fleet
            .signing_keys(&tenant_id, &format!("{repository_id}-other"))
            .await
            .expect("query never-enrolled repository")
            .is_none());
    }

    /// `enroll_and_activate` already registers one key as a side effect of
    /// activation; a second key is registered directly and revoked, so the
    /// enrolled repository ends up with one resolved key and one revoked key
    /// -- proving `signing_keys` reports each key's OWN judged status rather
    /// than the whole repository's status collapsing to a single value.
    #[tokio::test]
    async fn signing_keys_judges_each_enrolled_key_independently_as_of_now() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;
        let activated_signing_key_id = format!("fleet-signing-key-{unique_id}");

        let (mut client, connection) =
            tokio_postgres::connect(&database_url, tokio_postgres::NoTls)
                .await
                .expect("test database connects");
        tokio::spawn(async move {
            let _ = connection.await;
        });

        let revoked_signing_key_id = format!("fleet-signing-key-revoked-{unique_id}");
        let revoked_record = signing_keys::SigningKeyRecord {
            signing_key_id: revoked_signing_key_id.clone(),
            tenant_id: tenant_id.clone(),
            repository_id: repository_id.clone(),
            node_id: format!("fleet-node-revoked-{unique_id}"),
            public_key: vec![9; 32],
            public_key_fingerprint: format!("ed25519:{revoked_signing_key_id}"),
            activated_at: SystemTime::now(),
            expires_at: None,
        };
        let transaction = client.transaction().await.expect("begin transaction");
        signing_keys::register(&transaction, &revoked_record)
            .await
            .expect("register second key");
        transaction.commit().await.expect("commit registration");

        let transaction = client.transaction().await.expect("begin transaction");
        signing_keys::revoke(
            &transaction,
            &signing_keys::KeyRevocation {
                signing_key_id: revoked_signing_key_id.clone(),
                reason: "fleet test revocation".to_owned(),
            },
            SystemTime::now(),
        )
        .await
        .expect("revoke second key");
        transaction.commit().await.expect("commit revocation");

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let keys = fleet
            .signing_keys(&tenant_id, &repository_id)
            .await
            .expect("query signing keys")
            .expect("repository is enrolled");

        assert_eq!(keys.len(), 2, "the activation key plus the revoked key");

        let activated = keys
            .iter()
            .find(|key| key.signing_key_id == activated_signing_key_id)
            .expect("the activation-issued key is present");
        assert!(
            matches!(activated.status, KeyResolution::Resolved(_)),
            "a freshly activated key must still be resolved: {:?}",
            activated.status
        );

        let revoked = keys
            .iter()
            .find(|key| key.signing_key_id == revoked_signing_key_id)
            .expect("the manually revoked key is present");
        assert_eq!(revoked.node_id, revoked_record.node_id);
        assert_eq!(
            revoked.public_key_fingerprint,
            revoked_record.public_key_fingerprint
        );
        assert_eq!(revoked.status, KeyResolution::Revoked);
        assert_eq!(revoked.expires_at, None);
    }

    /// A ledger record's own fields never change, but its `key_status`
    /// annotation is judged as of now (ADR-0084 decision 12): the same event
    /// reads `Resolved` while its signing key is healthy and `Revoked` once
    /// that key is later revoked, without the record itself being touched.
    #[tokio::test]
    async fn timeline_key_status_reflects_a_later_revocation_without_changing_the_record() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;
        let signing_key_id = format!("fleet-signing-key-{unique_id}");

        let mut ledger = LedgerStore::connect(&database_url)
            .await
            .expect("connect ledger store");
        let envelope = EventEnvelope {
            key: DedupKey {
                tenant_id: tenant_id.clone(),
                repository_id: repository_id.clone(),
                producer_id: format!("fleet-producer-{unique_id}"),
                producer_sequence: 1,
            },
            payload: b"{}".to_vec(),
            payload_digest: vec![1, 2, 3],
            schema_version: "v1".to_string(),
            occurred_at: SystemTime::now(),
            payload_type: "structural_fact".to_string(),
            previous_envelope_digest: None,
            signing_key_id: Some(signing_key_id.clone()),
            signature: None,
            provenance: ProvenanceClass::EnrolledNode,
        };
        ledger.append(&envelope).await.expect("append envelope");

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let before_revocation = fleet
            .timeline(&tenant_id, &repository_id, 50)
            .await
            .expect("query timeline before revocation");
        assert_eq!(before_revocation.len(), 1);
        assert_eq!(
            before_revocation[0].signing_key_id,
            Some(signing_key_id.clone())
        );
        assert!(
            matches!(
                before_revocation[0].key_status,
                Some(KeyResolution::Resolved(_))
            ),
            "a freshly activated key must still be resolved: {:?}",
            before_revocation[0].key_status
        );

        let (mut client, connection) =
            tokio_postgres::connect(&database_url, tokio_postgres::NoTls)
                .await
                .expect("test database connects");
        tokio::spawn(async move {
            let _ = connection.await;
        });
        let transaction = client.transaction().await.expect("begin transaction");
        signing_keys::revoke(
            &transaction,
            &signing_keys::KeyRevocation {
                signing_key_id: signing_key_id.clone(),
                reason: "timeline test revocation".to_owned(),
            },
            SystemTime::now(),
        )
        .await
        .expect("revoke the signing key");
        transaction.commit().await.expect("commit revocation");

        let after_revocation = fleet
            .timeline(&tenant_id, &repository_id, 50)
            .await
            .expect("query timeline after revocation");
        assert_eq!(after_revocation.len(), 1);
        // The underlying record is untouched: same position, same payload.
        assert_eq!(
            after_revocation[0].stream_position,
            before_revocation[0].stream_position
        );
        assert_eq!(
            after_revocation[0].payload_type,
            before_revocation[0].payload_type
        );
        assert_eq!(after_revocation[0].key_status, Some(KeyResolution::Revoked));
    }

    /// An event with no signing key at all (e.g. unverified-attribution
    /// provenance) must not be misreported as a healthy or unhealthy key --
    /// it has none, and `key_status` says so with `None` rather than
    /// `Unknown`, which is reserved for a `signing_key_id` that does not
    /// resolve to any registered key.
    #[tokio::test]
    async fn timeline_key_status_is_none_when_the_record_carries_no_signing_key() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let (tenant_id, repository_id) =
            enroll_and_activate(&database_url, &unique_id.to_string()).await;

        let mut ledger = LedgerStore::connect(&database_url)
            .await
            .expect("connect ledger store");
        let envelope = EventEnvelope {
            key: DedupKey {
                tenant_id: tenant_id.clone(),
                repository_id: repository_id.clone(),
                producer_id: format!("fleet-producer-{unique_id}"),
                producer_sequence: 1,
            },
            payload: b"{}".to_vec(),
            payload_digest: vec![1, 2, 3],
            schema_version: "v1".to_string(),
            occurred_at: SystemTime::now(),
            payload_type: "structural_fact".to_string(),
            previous_envelope_digest: None,
            signing_key_id: None,
            signature: None,
            provenance: ProvenanceClass::UnverifiedAttribution,
        };
        ledger.append(&envelope).await.expect("append envelope");

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");
        let timeline = fleet
            .timeline(&tenant_id, &repository_id, 50)
            .await
            .expect("query timeline");

        assert_eq!(timeline.len(), 1);
        assert_eq!(timeline[0].signing_key_id, None);
        assert_eq!(timeline[0].key_status, None);
    }

    /// Escaping is a pure function: no live database needed, and the exact
    /// property that keeps a repository named `my_repo` from being matched
    /// by a bare, unescaped `_` wildcard.
    #[test]
    fn escape_like_pattern_escapes_percent_underscore_and_backslash() {
        assert_eq!(escape_like_pattern("my_repo"), "my\\_repo");
        assert_eq!(escape_like_pattern("100%done"), "100\\%done");
        assert_eq!(escape_like_pattern(r"a\b"), r"a\\b");
        assert_eq!(escape_like_pattern("plain"), "plain");
    }

    #[test]
    fn fleet_sort_default_order_is_repository_id_ascending() {
        assert_eq!(
            FleetSort::default_order(),
            FleetSort {
                field: FleetSortField::RepositoryId,
                direction: SortDirection::Ascending,
            }
        );
    }

    #[test]
    fn fleet_sort_order_by_clause_always_carries_a_repository_id_tiebreaker() {
        let sorts = [
            FleetSortField::RepositoryId,
            FleetSortField::ActiveNodeCount,
            FleetSortField::LastActivatedAt,
        ];
        for field in sorts {
            for direction in [SortDirection::Ascending, SortDirection::Descending] {
                let clause = FleetSort { field, direction }.order_by_clause();
                assert!(
                    clause.contains("request.repository_id"),
                    "{field:?}/{direction:?} clause must break ties by repository_id: {clause}"
                );
                assert!(
                    clause.starts_with("ORDER BY"),
                    "not a valid ORDER BY: {clause}"
                );
            }
        }
    }

    #[test]
    fn fleet_work_sort_default_order_is_lease_expires_at_ascending() {
        assert_eq!(
            FleetWorkSort::default_order(),
            FleetWorkSort {
                field: FleetWorkSortField::LeaseExpiresAt,
                direction: SortDirection::Ascending,
            }
        );
    }

    #[test]
    fn fleet_work_sort_order_by_clause_always_carries_a_task_id_tiebreaker() {
        let sorts = [
            FleetWorkSortField::LeaseExpiresAt,
            FleetWorkSortField::RepositoryId,
            FleetWorkSortField::OwnerId,
        ];
        for field in sorts {
            for direction in [SortDirection::Ascending, SortDirection::Descending] {
                let clause = FleetWorkSort { field, direction }.order_by_clause();
                assert!(
                    clause.contains("task_id"),
                    "{field:?}/{direction:?} clause must break ties by task_id: {clause}"
                );
                assert!(
                    clause.starts_with("ORDER BY"),
                    "not a valid ORDER BY: {clause}"
                );
            }
        }
    }

    /// Real pagination against a real Postgres: three repositories enrolled
    /// under one shared tenant, a page smaller than the total, and the
    /// filtered total staying correct across both pages.
    #[tokio::test]
    async fn repositories_paginates_and_reports_the_true_total_across_pages() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let tenant_id = format!("fleet-page-tenant-{unique_id}");
        let repository_ids = [
            format!("fleet-page-repo-{unique_id}-a"),
            format!("fleet-page-repo-{unique_id}-b"),
            format!("fleet-page-repo-{unique_id}-c"),
        ];
        for (index, repository_id) in repository_ids.iter().enumerate() {
            enroll_and_activate_in(
                &database_url,
                &tenant_id,
                repository_id,
                &format!("{unique_id}-{index}"),
            )
            .await;
        }

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");

        let first_page = fleet
            .repositories(
                &tenant_id,
                FleetFilter::default(),
                FleetSort::default_order(),
                1,
                2,
            )
            .await
            .expect("query first page");
        assert_eq!(first_page.repositories.len(), 2);
        assert_eq!(
            first_page.total, 3,
            "total counts every match, not just this page"
        );
        assert_eq!(first_page.repositories[0].repository_id, repository_ids[0]);
        assert_eq!(first_page.repositories[1].repository_id, repository_ids[1]);

        let second_page = fleet
            .repositories(
                &tenant_id,
                FleetFilter::default(),
                FleetSort::default_order(),
                2,
                2,
            )
            .await
            .expect("query second page");
        assert_eq!(second_page.repositories.len(), 1);
        assert_eq!(second_page.total, 3);
        assert_eq!(second_page.repositories[0].repository_id, repository_ids[2]);

        // The coordination filter is a real predicate, not client-side: every
        // enrolled-and-activated repository has one active node, so "active"
        // matches all three and "none" matches zero.
        let active_only = fleet
            .repositories(
                &tenant_id,
                FleetFilter {
                    coordination: Some("active"),
                    ..Default::default()
                },
                FleetSort::default_order(),
                1,
                10,
            )
            .await
            .expect("query active-only");
        assert_eq!(active_only.total, 3);

        let none_only = fleet
            .repositories(
                &tenant_id,
                FleetFilter {
                    coordination: Some("none"),
                    ..Default::default()
                },
                FleetSort::default_order(),
                1,
                10,
            )
            .await
            .expect("query none-only");
        assert_eq!(none_only.total, 0);
        assert!(none_only.repositories.is_empty());
    }

    /// `q` is a real substring filter with real escaping: a repository whose
    /// id contains a literal `_` is found by its exact text, and is NOT
    /// falsely matched by substituting a different character for that `_` --
    /// which unescaped `ILIKE` would treat as "match any one character".
    #[tokio::test]
    async fn repositories_q_filter_escapes_literal_underscores() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let tenant_id = format!("fleet-q-tenant-{unique_id}");
        let repository_id = format!("fleet-q-repo-{unique_id}_under_score");
        enroll_and_activate_in(
            &database_url,
            &tenant_id,
            &repository_id,
            &unique_id.to_string(),
        )
        .await;

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");

        let exact_substring = format!("{unique_id}_under_score");
        let matched = fleet
            .repositories(
                &tenant_id,
                FleetFilter {
                    q: Some(&escape_like_pattern(&exact_substring)),
                    ..Default::default()
                },
                FleetSort::default_order(),
                1,
                10,
            )
            .await
            .expect("query with exact substring");
        assert_eq!(matched.total, 1);
        assert_eq!(matched.repositories[0].repository_id, repository_id);

        // Same string with the underscore swapped for a different character:
        // must NOT match, proving `_` was treated literally, not as a wildcard.
        let wrong_char_substring = format!("{unique_id}Xunder_score");
        let unmatched = fleet
            .repositories(
                &tenant_id,
                FleetFilter {
                    q: Some(&escape_like_pattern(&wrong_char_substring)),
                    ..Default::default()
                },
                FleetSort::default_order(),
                1,
                10,
            )
            .await
            .expect("query with a mismatched substring");
        assert_eq!(unmatched.total, 0);
        assert!(unmatched.repositories.is_empty());
    }

    /// Sorting is a real `ORDER BY`, not a client-side illusion: descending
    /// by repository id reverses the default ascending order.
    #[tokio::test]
    async fn repositories_sort_direction_reverses_the_default_order() {
        let Ok(database_url) = std::env::var("ACKPLANE_TEST_DATABASE_URL") else {
            eprintln!("skipping: ACKPLANE_TEST_DATABASE_URL is not set");
            return;
        };
        let unique_id = uuid_ish();
        let tenant_id = format!("fleet-sort-tenant-{unique_id}");
        let repository_ids = [
            format!("fleet-sort-repo-{unique_id}-a"),
            format!("fleet-sort-repo-{unique_id}-z"),
        ];
        for (index, repository_id) in repository_ids.iter().enumerate() {
            enroll_and_activate_in(
                &database_url,
                &tenant_id,
                repository_id,
                &format!("{unique_id}-sort-{index}"),
            )
            .await;
        }

        let fleet = FleetStore::connect(&database_url)
            .await
            .expect("connect fleet store");

        let ascending = fleet
            .repositories(
                &tenant_id,
                FleetFilter::default(),
                FleetSort::default_order(),
                1,
                10,
            )
            .await
            .expect("query ascending");
        assert_eq!(ascending.repositories[0].repository_id, repository_ids[0]);
        assert_eq!(ascending.repositories[1].repository_id, repository_ids[1]);

        let descending = fleet
            .repositories(
                &tenant_id,
                FleetFilter::default(),
                FleetSort {
                    field: FleetSortField::RepositoryId,
                    direction: SortDirection::Descending,
                },
                1,
                10,
            )
            .await
            .expect("query descending");
        assert_eq!(descending.repositories[0].repository_id, repository_ids[1]);
        assert_eq!(descending.repositories[1].repository_id, repository_ids[0]);
    }
}
