// Generated by AI (UnitTest MCP)
//! Structural guard for the tenant-scoped Live Feed SSE sub-router.

const LIVE_FEED_RS: &str = include_str!("../src/live_feed.rs");

#[test]
fn live_feed_route_is_registered_as_the_versioned_sse_endpoint() {
    assert!(
        LIVE_FEED_RS.contains(".route(\"/api/v1/live\", get(live_feed))"),
        "Live Feed must remain a versioned same-origin SSE route"
    );
}

#[test]
fn live_feed_authorizes_the_repository_before_opening_replay() {
    let body = function_body(LIVE_FEED_RS, "live_feed");
    let visibility = body
        .find("ensure_repository_visible(&state, &query.repository_id).await?")
        .expect("Live Feed must check tenant-scoped repository visibility");
    let replay = body
        .find(".replay_after(")
        .expect("Live Feed must replay durable events after authorization");

    assert!(
        visibility < replay,
        "Live Feed must authorize before it reads or replays a tenant cursor"
    );
}

fn function_body<'a>(source: &'a str, name: &str) -> &'a str {
    let marker = format!("async fn {name}(");
    let function_start = source
        .find(&marker)
        .unwrap_or_else(|| panic!("expected Live Feed handler {name}"));
    let body_start = source[function_start..]
        .find('{')
        .map(|offset| function_start + offset)
        .unwrap_or_else(|| panic!("expected opening brace for Live Feed handler {name}"));
    let body_end = balanced_braces(source, body_start)
        .unwrap_or_else(|| panic!("expected closing brace for Live Feed handler {name}"));
    &source[body_start..body_end]
}

fn balanced_braces(source: &str, open: usize) -> Option<usize> {
    let mut depth = 0_i32;
    for (offset, character) in source[open..].char_indices() {
        match character {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(open + offset + 1);
                }
            }
            _ => {}
        }
    }
    None
}
